// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <DataExchange/XCAFPrs/XCAFPrs_DataMapIteratorOfDataMapOfStyleShape.hxx>

#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <DataExchange/XCAFPrs/XCAFPrs_Style.hxx>
#include <ModelingData/TopoDS/TopoDS_Shape.hxx>
#include <DataExchange/XCAFPrs/XCAFPrs_DataMapOfStyleShape.hxx>
#include <DataExchange/XCAFPrs/XCAFPrs_DataMapNodeOfDataMapOfStyleShape.hxx>
 

#define TheKey XCAFPrs_Style
#define TheKey_hxx <DataExchange/XCAFPrs/XCAFPrs_Style.hxx>
#define TheItem TopoDS_Shape
#define TheItem_hxx <ModelingData/TopoDS/TopoDS_Shape.hxx>
#define Hasher XCAFPrs_Style
#define Hasher_hxx <DataExchange/XCAFPrs/XCAFPrs_Style.hxx>
#define TCollection_DataMapNode XCAFPrs_DataMapNodeOfDataMapOfStyleShape
#define TCollection_DataMapNode_hxx <DataExchange/XCAFPrs/XCAFPrs_DataMapNodeOfDataMapOfStyleShape.hxx>
#define TCollection_DataMapIterator XCAFPrs_DataMapIteratorOfDataMapOfStyleShape
#define TCollection_DataMapIterator_hxx <DataExchange/XCAFPrs/XCAFPrs_DataMapIteratorOfDataMapOfStyleShape.hxx>
#define Handle_TCollection_DataMapNode Handle_XCAFPrs_DataMapNodeOfDataMapOfStyleShape
#define TCollection_DataMapNode_Type_() XCAFPrs_DataMapNodeOfDataMapOfStyleShape_Type_()
#define TCollection_DataMap XCAFPrs_DataMapOfStyleShape
#define TCollection_DataMap_hxx <DataExchange/XCAFPrs/XCAFPrs_DataMapOfStyleShape.hxx>
#include <Foundation/TCollection/TCollection_DataMapIterator.gxx>

