// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _TopOpeBRepDS_SurfaceIterator_HeaderFile
#define _TopOpeBRepDS_SurfaceIterator_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineAlloc.hxx>
#include <Foundation/Standard/Standard_Macro.hxx>

#include <ModelingAlgorithms/TopOpeBRepDS/TopOpeBRepDS_InterferenceIterator.hxx>
#include <ModelingAlgorithms/TopOpeBRepDS/TopOpeBRepDS_ListOfInterference.hxx>
#include <Foundation/Standard/Standard_Integer.hxx>
#include <ModelingData/TopAbs/TopAbs_Orientation.hxx>
#include <ModelingData/TopAbs/TopAbs_State.hxx>



class TopOpeBRepDS_SurfaceIterator  : public TopOpeBRepDS_InterferenceIterator
{
public:

  DEFINE_STANDARD_ALLOC

  
  //! Creates an  iterator on the  Surfaces on solid
  //! described by the interferences in <L>.
  Standard_EXPORT TopOpeBRepDS_SurfaceIterator(const TopOpeBRepDS_ListOfInterference& L);
  
  //! Index of the surface in the data structure.
  Standard_EXPORT   Standard_Integer Current()  const;
  
  Standard_EXPORT   TopAbs_Orientation Orientation (const TopAbs_State S)  const;




protected:





private:





};







#endif // _TopOpeBRepDS_SurfaceIterator_HeaderFile
