// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Interface_Array1OfFileParameter.hxx>

#include <Foundation/Standard/Standard_RangeError.hxx>
#include <Foundation/Standard/Standard_DimensionMismatch.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_OutOfMemory.hxx>
#include <Interface_FileParameter.hxx>
 

#define Array1Item Interface_FileParameter
#define Array1Item_hxx <Interface_FileParameter.hxx>
#define TCollection_Array1 Interface_Array1OfFileParameter
#define TCollection_Array1_hxx <Interface_Array1OfFileParameter.hxx>
#include <Foundation/TCollection/TCollection_Array1.gxx>

