// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Mathematics/Collections/TColgp_SequenceOfPnt.hxx>

#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Mathematics/Primitives/gp_Pnt.hxx>
#include <Mathematics/Collections/TColgp_SequenceNodeOfSequenceOfPnt.hxx>
 

#define SeqItem gp_Pnt
#define SeqItem_hxx <Mathematics/Primitives/gp_Pnt.hxx>
#define TCollection_SequenceNode TColgp_SequenceNodeOfSequenceOfPnt
#define TCollection_SequenceNode_hxx <Mathematics/Collections/TColgp_SequenceNodeOfSequenceOfPnt.hxx>
#define Handle_TCollection_SequenceNode Handle_TColgp_SequenceNodeOfSequenceOfPnt
#define TCollection_SequenceNode_Type_() TColgp_SequenceNodeOfSequenceOfPnt_Type_()
#define TCollection_Sequence TColgp_SequenceOfPnt
#define TCollection_Sequence_hxx <Mathematics/Collections/TColgp_SequenceOfPnt.hxx>
#include <Foundation/TCollection/TCollection_Sequence.gxx>

