// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Mathematics/Collections/TColgp_Array1OfDir.hxx>

#include <Foundation/Standard/Standard_RangeError.hxx>
#include <Foundation/Standard/Standard_DimensionMismatch.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_OutOfMemory.hxx>
#include <Mathematics/Primitives/gp_Dir.hxx>
 

#define Array1Item gp_Dir
#define Array1Item_hxx <Mathematics/Primitives/gp_Dir.hxx>
#define TCollection_Array1 TColgp_Array1OfDir
#define TCollection_Array1_hxx <Mathematics/Collections/TColgp_Array1OfDir.hxx>
#include <Foundation/TCollection/TCollection_Array1.gxx>

