// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Mathematics/Collections/TColgp_HArray1OfLin2d.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <Foundation/Standard/Standard_RangeError.hxx>
#include <Foundation/Standard/Standard_DimensionMismatch.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_OutOfMemory.hxx>
#include <Mathematics/Primitives/gp_Lin2d.hxx>
#include <Mathematics/Collections/TColgp_Array1OfLin2d.hxx>

 


IMPLEMENT_STANDARD_TYPE(TColgp_HArray1OfLin2d)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(TColgp_HArray1OfLin2d)


IMPLEMENT_DOWNCAST(TColgp_HArray1OfLin2d,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(TColgp_HArray1OfLin2d)


#define ItemHArray1 gp_Lin2d
#define ItemHArray1_hxx <Mathematics/Primitives/gp_Lin2d.hxx>
#define TheArray1 TColgp_Array1OfLin2d
#define TheArray1_hxx <Mathematics/Collections/TColgp_Array1OfLin2d.hxx>
#define TCollection_HArray1 TColgp_HArray1OfLin2d
#define TCollection_HArray1_hxx <Mathematics/Collections/TColgp_HArray1OfLin2d.hxx>
#define Handle_TCollection_HArray1 Handle_TColgp_HArray1OfLin2d
#define TCollection_HArray1_Type_() TColgp_HArray1OfLin2d_Type_()
#include <Foundation/TCollection/TCollection_HArray1.gxx>

