// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Mathematics/Collections/TColgp_HArray1OfXYZ.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <Foundation/Standard/Standard_RangeError.hxx>
#include <Foundation/Standard/Standard_DimensionMismatch.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_OutOfMemory.hxx>
#include <Mathematics/Primitives/gp_XYZ.hxx>
#include <Mathematics/Collections/TColgp_Array1OfXYZ.hxx>

 


IMPLEMENT_STANDARD_TYPE(TColgp_HArray1OfXYZ)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(TColgp_HArray1OfXYZ)


IMPLEMENT_DOWNCAST(TColgp_HArray1OfXYZ,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(TColgp_HArray1OfXYZ)


#define ItemHArray1 gp_XYZ
#define ItemHArray1_hxx <Mathematics/Primitives/gp_XYZ.hxx>
#define TheArray1 TColgp_Array1OfXYZ
#define TheArray1_hxx <Mathematics/Collections/TColgp_Array1OfXYZ.hxx>
#define TCollection_HArray1 TColgp_HArray1OfXYZ
#define TCollection_HArray1_hxx <Mathematics/Collections/TColgp_HArray1OfXYZ.hxx>
#define Handle_TCollection_HArray1 Handle_TColgp_HArray1OfXYZ
#define TCollection_HArray1_Type_() TColgp_HArray1OfXYZ_Type_()
#include <Foundation/TCollection/TCollection_HArray1.gxx>

