// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Mathematics/Collections/TColgp_Array1OfPnt.hxx>

#include <Foundation/Standard/Standard_RangeError.hxx>
#include <Foundation/Standard/Standard_DimensionMismatch.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_OutOfMemory.hxx>
#include <gp_Pnt.hxx>
 

#define Array1Item gp_Pnt
#define Array1Item_hxx <gp_Pnt.hxx>
#define TCollection_Array1 TColgp_Array1OfPnt
#define TCollection_Array1_hxx <Mathematics/Collections/TColgp_Array1OfPnt.hxx>
#include <Foundation/TCollection/TCollection_Array1.gxx>

