// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Mathematics/Collections/TColgp_SequenceNodeOfSequenceOfXY.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <gp_XY.hxx>
#include <Mathematics/Collections/TColgp_SequenceOfXY.hxx>

 


IMPLEMENT_STANDARD_TYPE(TColgp_SequenceNodeOfSequenceOfXY)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(TColgp_SequenceNodeOfSequenceOfXY)


IMPLEMENT_DOWNCAST(TColgp_SequenceNodeOfSequenceOfXY,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(TColgp_SequenceNodeOfSequenceOfXY)


#define SeqItem gp_XY
#define SeqItem_hxx <gp_XY.hxx>
#define TCollection_SequenceNode TColgp_SequenceNodeOfSequenceOfXY
#define TCollection_SequenceNode_hxx <Mathematics/Collections/TColgp_SequenceNodeOfSequenceOfXY.hxx>
#define Handle_TCollection_SequenceNode Handle_TColgp_SequenceNodeOfSequenceOfXY
#define TCollection_SequenceNode_Type_() TColgp_SequenceNodeOfSequenceOfXY_Type_()
#define TCollection_Sequence TColgp_SequenceOfXY
#define TCollection_Sequence_hxx <Mathematics/Collections/TColgp_SequenceOfXY.hxx>
#include <Foundation/TCollection/TCollection_SequenceNode.gxx>

