// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Mathematics/Collections/TColgp_HArray2OfPnt.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <Foundation/Standard/Standard_RangeError.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_OutOfMemory.hxx>
#include <Foundation/Standard/Standard_DimensionMismatch.hxx>
#include <Mathematics/Primitives/gp_Pnt.hxx>
#include <Mathematics/Collections/TColgp_Array2OfPnt.hxx>

 


IMPLEMENT_STANDARD_TYPE(TColgp_HArray2OfPnt)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(TColgp_HArray2OfPnt)


IMPLEMENT_DOWNCAST(TColgp_HArray2OfPnt,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(TColgp_HArray2OfPnt)


#define ItemHArray2 gp_Pnt
#define ItemHArray2_hxx <Mathematics/Primitives/gp_Pnt.hxx>
#define TheArray2 TColgp_Array2OfPnt
#define TheArray2_hxx <Mathematics/Collections/TColgp_Array2OfPnt.hxx>
#define TCollection_HArray2 TColgp_HArray2OfPnt
#define TCollection_HArray2_hxx <Mathematics/Collections/TColgp_HArray2OfPnt.hxx>
#define Handle_TCollection_HArray2 Handle_TColgp_HArray2OfPnt
#define TCollection_HArray2_Type_() TColgp_HArray2OfPnt_Type_()
#include <Foundation/TCollection/TCollection_HArray2.gxx>

