cc_library(
    name = "Foundation",
    srcs = glob([
        "Standard/*.cxx",
        "Standard/*.hxx",
        "Standard/*.h",
        "NCollection/*.cxx",
        "NCollection/*.hxx",
        "Storage/*.cxx",
        "Storage/*.hxx",
        "OSD/*.cxx",
        "OSD/*.hxx",
        "FSD/*.cxx",
        "FSD/*.hxx",
    ]),
    hdrs = glob([
        "*/*.hxx",
        "*/*.h",
    ]),
    includes = [
        "inc",
        "Standard",
        "NCollection",
        "Storage",
        "OSD",
        "FSD",
    ]
)
