// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <TColGeom_SequenceNodeOfSequenceOfCurve.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <Geometry/Geom/Geom_Curve.hxx>
#include <TColGeom_SequenceOfCurve.hxx>

 


IMPLEMENT_STANDARD_TYPE(TColGeom_SequenceNodeOfSequenceOfCurve)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(TColGeom_SequenceNodeOfSequenceOfCurve)


IMPLEMENT_DOWNCAST(TColGeom_SequenceNodeOfSequenceOfCurve,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(TColGeom_SequenceNodeOfSequenceOfCurve)


#define SeqItem Handle(Geom_Curve)
#define SeqItem_hxx <Geometry/Geom/Geom_Curve.hxx>
#define TCollection_SequenceNode TColGeom_SequenceNodeOfSequenceOfCurve
#define TCollection_SequenceNode_hxx <TColGeom_SequenceNodeOfSequenceOfCurve.hxx>
#define Handle_TCollection_SequenceNode Handle_TColGeom_SequenceNodeOfSequenceOfCurve
#define TCollection_SequenceNode_Type_() TColGeom_SequenceNodeOfSequenceOfCurve_Type_()
#define TCollection_Sequence TColGeom_SequenceOfCurve
#define TCollection_Sequence_hxx <TColGeom_SequenceOfCurve.hxx>
#include <Foundation/TCollection/TCollection_SequenceNode.gxx>

