// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <DataExchange/StepData/StepData_Array1OfField.hxx>

#include <Foundation/Standard/Standard_RangeError.hxx>
#include <Foundation/Standard/Standard_DimensionMismatch.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_OutOfMemory.hxx>
#include <DataExchange/StepData/StepData_Field.hxx>
 

#define Array1Item StepData_Field
#define Array1Item_hxx <DataExchange/StepData/StepData_Field.hxx>
#define TCollection_Array1 StepData_Array1OfField
#define TCollection_Array1_hxx <DataExchange/StepData/StepData_Array1OfField.hxx>
#include <Foundation/TCollection/TCollection_Array1.gxx>

