// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <DataExchange/StepData/StepData_FileRecognizer.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <Foundation/Standard/Standard_Transient.hxx>
#include <DataExchange/StepData/StepData_FileRecognizer.hxx>
#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <Foundation/TCollection/TCollection_AsciiString.hxx>

 


IMPLEMENT_STANDARD_TYPE(StepData_FileRecognizer)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(StepData_FileRecognizer)


IMPLEMENT_DOWNCAST(StepData_FileRecognizer,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(StepData_FileRecognizer)


#define TheKey TCollection_AsciiString
#define TheKey_hxx <Foundation/TCollection/TCollection_AsciiString.hxx>
#define Handle_TheResul Handle_Standard_Transient
#define TheResul Standard_Transient
#define TheResul_hxx <Foundation/Standard/Standard_Transient.hxx>
#define Interface_Recognizer StepData_FileRecognizer
#define Interface_Recognizer_hxx <DataExchange/StepData/StepData_FileRecognizer.hxx>
#define Handle_Interface_Recognizer Handle_StepData_FileRecognizer
#define Interface_Recognizer_Type_() StepData_FileRecognizer_Type_()
#include <DataExchange/Interface/Interface_Recognizer.gxx>

