// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_TDataStd_DataMapNodeOfDataMapOfStringString_HeaderFile
#define _Handle_TDataStd_DataMapNodeOfDataMapOfStringString_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <Foundation/TCollection/Handle_TCollection_MapNode.hxx>

class Standard_Transient;
class Handle(Standard_Type);
class Handle(TCollection_MapNode);
class TDataStd_DataMapNodeOfDataMapOfStringString;

DEFINE_STANDARD_HANDLE(TDataStd_DataMapNodeOfDataMapOfStringString, TCollection_MapNode)

#endif // _Handle_TDataStd_DataMapNodeOfDataMapOfStringString_HeaderFile
