// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _TDataStd_ListIteratorOfListOfExtendedString_HeaderFile
#define _TDataStd_ListIteratorOfListOfExtendedString_HeaderFile

#include <OCAF/TDataStd/TDataStd_ListOfExtendedString.hxx>

typedef TDataStd_ListOfExtendedString::iterator TDataStd_ListIteratorOfListOfExtendedString;

#endif // _TDataStd_ListIteratorOfListOfExtendedString_HeaderFile
