// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ModelingAlgorithms/BRepAlgo/BRepAlgo_DataMapNodeOfDataMapOfShapeBoolean.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <ModelingData/TopoDS/TopoDS_Shape.hxx>
#include <ModelingData/TopTools/TopTools_ShapeMapHasher.hxx>
#include <ModelingAlgorithms/BRepAlgo/BRepAlgo_DataMapOfShapeBoolean.hxx>
#include <ModelingAlgorithms/BRepAlgo/BRepAlgo_DataMapIteratorOfDataMapOfShapeBoolean.hxx>

 


IMPLEMENT_STANDARD_TYPE(BRepAlgo_DataMapNodeOfDataMapOfShapeBoolean)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(BRepAlgo_DataMapNodeOfDataMapOfShapeBoolean)


IMPLEMENT_DOWNCAST(BRepAlgo_DataMapNodeOfDataMapOfShapeBoolean,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(BRepAlgo_DataMapNodeOfDataMapOfShapeBoolean)


#define TheKey TopoDS_Shape
#define TheKey_hxx <ModelingData/TopoDS/TopoDS_Shape.hxx>
#define TheItem Standard_Boolean
#define TheItem_hxx <Foundation/Standard/Standard_Boolean.hxx>
#define Hasher TopTools_ShapeMapHasher
#define Hasher_hxx <ModelingData/TopTools/TopTools_ShapeMapHasher.hxx>
#define TCollection_DataMapNode BRepAlgo_DataMapNodeOfDataMapOfShapeBoolean
#define TCollection_DataMapNode_hxx <ModelingAlgorithms/BRepAlgo/BRepAlgo_DataMapNodeOfDataMapOfShapeBoolean.hxx>
#define TCollection_DataMapIterator BRepAlgo_DataMapIteratorOfDataMapOfShapeBoolean
#define TCollection_DataMapIterator_hxx <ModelingAlgorithms/BRepAlgo/BRepAlgo_DataMapIteratorOfDataMapOfShapeBoolean.hxx>
#define Handle_TCollection_DataMapNode Handle_BRepAlgo_DataMapNodeOfDataMapOfShapeBoolean
#define TCollection_DataMapNode_Type_() BRepAlgo_DataMapNodeOfDataMapOfShapeBoolean_Type_()
#define TCollection_DataMap BRepAlgo_DataMapOfShapeBoolean
#define TCollection_DataMap_hxx <ModelingAlgorithms/BRepAlgo/BRepAlgo_DataMapOfShapeBoolean.hxx>
#include <Foundation/TCollection/TCollection_DataMapNode.gxx>

