// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _StepVisual_AnnotationTextOccurrence_HeaderFile
#define _StepVisual_AnnotationTextOccurrence_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <DataExchange/StepVisual/Handle_StepVisual_AnnotationTextOccurrence.hxx>

#include <DataExchange/StepVisual/StepVisual_AnnotationOccurrence.hxx>



class StepVisual_AnnotationTextOccurrence : public StepVisual_AnnotationOccurrence
{

public:

  
  //! Returns a AnnotationTextOccurrence
  Standard_EXPORT StepVisual_AnnotationTextOccurrence();




  DEFINE_STANDARD_RTTI(StepVisual_AnnotationTextOccurrence)

protected:




private: 




};







#endif // _StepVisual_AnnotationTextOccurrence_HeaderFile
