// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _StepVisual_HArray1OfCurveStyleFontPattern_HeaderFile
#define _StepVisual_HArray1OfCurveStyleFontPattern_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <Handle_StepVisual_HArray1OfCurveStyleFontPattern.hxx>

#include <DataExchange/StepVisual/StepVisual_Array1OfCurveStyleFontPattern.hxx>
#include <Foundation/MMgt/MMgt_TShared.hxx>
#include <Handle_StepVisual_CurveStyleFontPattern.hxx>
#include <Foundation/Standard/Standard_Integer.hxx>
class Standard_RangeError;
class Standard_DimensionMismatch;
class Standard_OutOfRange;
class Standard_OutOfMemory;
class StepVisual_CurveStyleFontPattern;
class StepVisual_Array1OfCurveStyleFontPattern;



class StepVisual_HArray1OfCurveStyleFontPattern : public MMgt_TShared
{

public:

  
    StepVisual_HArray1OfCurveStyleFontPattern(const Standard_Integer Low, const Standard_Integer Up);
  
    StepVisual_HArray1OfCurveStyleFontPattern(const Standard_Integer Low, const Standard_Integer Up, const Handle(StepVisual_CurveStyleFontPattern)& V);
  
      void Init (const Handle(StepVisual_CurveStyleFontPattern)& V) ;
  
      Standard_Integer Length()  const;
  
      Standard_Integer Lower()  const;
  
      Standard_Integer Upper()  const;
  
      void SetValue (const Standard_Integer Index, const Handle(StepVisual_CurveStyleFontPattern)& Value) ;
  
     const  Handle(StepVisual_CurveStyleFontPattern)& Value (const Standard_Integer Index)  const;
  
      Handle(StepVisual_CurveStyleFontPattern)& ChangeValue (const Standard_Integer Index) ;
  
     const  StepVisual_Array1OfCurveStyleFontPattern& Array1()  const;
  
      StepVisual_Array1OfCurveStyleFontPattern& ChangeArray1() ;




  DEFINE_STANDARD_RTTI(StepVisual_HArray1OfCurveStyleFontPattern)

protected:




private: 


  StepVisual_Array1OfCurveStyleFontPattern myArray;


};

#define ItemHArray1 Handle(StepVisual_CurveStyleFontPattern)
#define ItemHArray1_hxx <DataExchange/StepVisual/StepVisual_CurveStyleFontPattern.hxx>
#define TheArray1 StepVisual_Array1OfCurveStyleFontPattern
#define TheArray1_hxx <DataExchange/StepVisual/StepVisual_Array1OfCurveStyleFontPattern.hxx>
#define TCollection_HArray1 StepVisual_HArray1OfCurveStyleFontPattern
#define TCollection_HArray1_hxx <DataExchange/StepVisual/StepVisual_HArray1OfCurveStyleFontPattern.hxx>
#define Handle_TCollection_HArray1 Handle_StepVisual_HArray1OfCurveStyleFontPattern
#define TCollection_HArray1_Type_() StepVisual_HArray1OfCurveStyleFontPattern_Type_()

#include <Foundation/TCollection/TCollection_HArray1.lxx>

#undef ItemHArray1
#undef ItemHArray1_hxx
#undef TheArray1
#undef TheArray1_hxx
#undef TCollection_HArray1
#undef TCollection_HArray1_hxx
#undef Handle_TCollection_HArray1
#undef TCollection_HArray1_Type_




#endif // _StepVisual_HArray1OfCurveStyleFontPattern_HeaderFile
