// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _StepVisual_CameraModelD2_HeaderFile
#define _StepVisual_CameraModelD2_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <DataExchange/StepVisual/Handle_StepVisual_CameraModelD2.hxx>

#include <DataExchange/StepVisual/Handle_StepVisual_PlanarBox.hxx>
#include <Foundation/Standard/Standard_Boolean.hxx>
#include <DataExchange/StepVisual/StepVisual_CameraModel.hxx>
#include <Foundation/TCollection/Handle_TCollection_HAsciiString.hxx>
class StepVisual_PlanarBox;
class TCollection_HAsciiString;



class StepVisual_CameraModelD2 : public StepVisual_CameraModel
{

public:

  
  //! Returns a CameraModelD2
  Standard_EXPORT StepVisual_CameraModelD2();
  
  Standard_EXPORT virtual   void Init (const Handle(TCollection_HAsciiString)& aName) ;
  
  Standard_EXPORT virtual   void Init (const Handle(TCollection_HAsciiString)& aName, const Handle(StepVisual_PlanarBox)& aViewWindow, const Standard_Boolean aViewWindowClipping) ;
  
  Standard_EXPORT   void SetViewWindow (const Handle(StepVisual_PlanarBox)& aViewWindow) ;
  
  Standard_EXPORT   Handle(StepVisual_PlanarBox) ViewWindow()  const;
  
  Standard_EXPORT   void SetViewWindowClipping (const Standard_Boolean aViewWindowClipping) ;
  
  Standard_EXPORT   Standard_Boolean ViewWindowClipping()  const;




  DEFINE_STANDARD_RTTI(StepVisual_CameraModelD2)

protected:




private: 


  Handle(StepVisual_PlanarBox) viewWindow;
  Standard_Boolean viewWindowClipping;


};







#endif // _StepVisual_CameraModelD2_HeaderFile
