// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _StepVisual_CameraImage2dWithScale_HeaderFile
#define _StepVisual_CameraImage2dWithScale_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <Handle_StepVisual_CameraImage2dWithScale.hxx>

#include <DataExchange/StepVisual/StepVisual_CameraImage.hxx>



class StepVisual_CameraImage2dWithScale : public StepVisual_CameraImage
{

public:

  
  Standard_EXPORT StepVisual_CameraImage2dWithScale();




  DEFINE_STANDARD_RTTI(StepVisual_CameraImage2dWithScale)

protected:




private: 




};







#endif // _StepVisual_CameraImage2dWithScale_HeaderFile
