// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_Storage_StreamUnknownTypeError_HeaderFile
#define _Handle_Storage_StreamUnknownTypeError_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <Foundation/Storage/Handle_Storage_StreamReadError.hxx>

class Standard_Transient;
class Handle(Standard_Type);
class Handle(Storage_StreamReadError);
class Storage_StreamUnknownTypeError;

DEFINE_STANDARD_HANDLE(Storage_StreamUnknownTypeError, Storage_StreamReadError)

#endif // _Handle_Storage_StreamUnknownTypeError_HeaderFile
