// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Resource_NoSuchResource_HeaderFile
#define _Resource_NoSuchResource_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <Foundation/Standard/Standard_DefineException.hxx>
#include <Foundation/Standard/Standard_SStream.hxx>
#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <Foundation/Resource/Handle_Resource_NoSuchResource.hxx>

#if !defined No_Exception && !defined No_Resource_NoSuchResource
  #define Resource_NoSuchResource_Raise_if(CONDITION, MESSAGE) \
  if (CONDITION) Resource_NoSuchResource::Raise(MESSAGE);
#else
  #define Resource_NoSuchResource_Raise_if(CONDITION, MESSAGE)
#endif

DEFINE_STANDARD_EXCEPTION(Resource_NoSuchResource, Standard_NoSuchObject)

#endif // _Resource_NoSuchResource_HeaderFile
