// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_PGeom_Direction_HeaderFile
#define _Handle_PGeom_Direction_HeaderFile

#include <Foundation/Standard/Standard_Macro.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <Foundation/Standard/Standard.hxx>
#include <OCAF/PGeom/Handle_PGeom_Vector.hxx>

class Standard_Persistent;
class Handle(Standard_Type);
class Handle(PGeom_Vector);
class PGeom_Direction;

DEFINE_STANDARD_PHANDLE(PGeom_Direction,PGeom_Vector)

#endif
