// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _PGeom_VectorWithMagnitude_HeaderFile
#define _PGeom_VectorWithMagnitude_HeaderFile

#include <Foundation/Standard/Standard_Macro.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <Foundation/Standard/Standard.hxx>
#include <OCAF/PGeom/Handle_PGeom_VectorWithMagnitude.hxx>

#include <OCAF/PGeom/PGeom_Vector.hxx>
class gp_Vec;


class PGeom_VectorWithMagnitude : public PGeom_Vector
{

public:

  
  //! Creates a VectorWithMagnitude with default values.
  Standard_EXPORT PGeom_VectorWithMagnitude();
  
  //! Creates a VectorWithMagnitude with <aVec>.
  Standard_EXPORT PGeom_VectorWithMagnitude(const gp_Vec& aVec);

PGeom_VectorWithMagnitude(const Storage_stCONSTclCOM& a) : PGeom_Vector(a)
{
  
}



  DEFINE_STANDARD_RTTI(PGeom_VectorWithMagnitude)

protected:




private: 




};







#endif // _PGeom_VectorWithMagnitude_HeaderFile
