// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_STEPControl_ActorRead_HeaderFile
#define _Handle_STEPControl_ActorRead_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <DataExchange/Transfer/Handle_Transfer_ActorOfTransientProcess.hxx>

class Standard_Transient;
class Handle(Standard_Type);
class Handle(Transfer_ActorOfTransientProcess);
class STEPControl_ActorRead;

DEFINE_STANDARD_HANDLE(STEPControl_ActorRead, Transfer_ActorOfTransientProcess)

#endif // _Handle_STEPControl_ActorRead_HeaderFile
