// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <TDocStd_DataMapIteratorOfLabelIDMapDataMap.hxx>

#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <OCAF/TDF/TDF_Label.hxx>
#include <OCAF/TDF/TDF_IDMap.hxx>
#include <OCAF/TDF/TDF_LabelMapHasher.hxx>
#include <TDocStd_LabelIDMapDataMap.hxx>
#include <TDocStd_DataMapNodeOfLabelIDMapDataMap.hxx>
 

#define TheKey TDF_Label
#define TheKey_hxx <OCAF/TDF/TDF_Label.hxx>
#define TheItem TDF_IDMap
#define TheItem_hxx <OCAF/TDF/TDF_IDMap.hxx>
#define Hasher TDF_LabelMapHasher
#define Hasher_hxx <OCAF/TDF/TDF_LabelMapHasher.hxx>
#define TCollection_DataMapNode TDocStd_DataMapNodeOfLabelIDMapDataMap
#define TCollection_DataMapNode_hxx <TDocStd_DataMapNodeOfLabelIDMapDataMap.hxx>
#define TCollection_DataMapIterator TDocStd_DataMapIteratorOfLabelIDMapDataMap
#define TCollection_DataMapIterator_hxx <TDocStd_DataMapIteratorOfLabelIDMapDataMap.hxx>
#define Handle_TCollection_DataMapNode Handle_TDocStd_DataMapNodeOfLabelIDMapDataMap
#define TCollection_DataMapNode_Type_() TDocStd_DataMapNodeOfLabelIDMapDataMap_Type_()
#define TCollection_DataMap TDocStd_LabelIDMapDataMap
#define TCollection_DataMap_hxx <TDocStd_LabelIDMapDataMap.hxx>
#include <Foundation/TCollection/TCollection_DataMapIterator.gxx>

