// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <OCAF/TDocStd/TDocStd_DataMapNodeOfLabelIDMapDataMap.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <OCAF/TDF/TDF_Label.hxx>
#include <OCAF/TDF/TDF_IDMap.hxx>
#include <OCAF/TDF/TDF_LabelMapHasher.hxx>
#include <OCAF/TDocStd/TDocStd_LabelIDMapDataMap.hxx>
#include <OCAF/TDocStd/TDocStd_DataMapIteratorOfLabelIDMapDataMap.hxx>

 


IMPLEMENT_STANDARD_TYPE(TDocStd_DataMapNodeOfLabelIDMapDataMap)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(TDocStd_DataMapNodeOfLabelIDMapDataMap)


IMPLEMENT_DOWNCAST(TDocStd_DataMapNodeOfLabelIDMapDataMap,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(TDocStd_DataMapNodeOfLabelIDMapDataMap)


#define TheKey TDF_Label
#define TheKey_hxx <OCAF/TDF/TDF_Label.hxx>
#define TheItem TDF_IDMap
#define TheItem_hxx <OCAF/TDF/TDF_IDMap.hxx>
#define Hasher TDF_LabelMapHasher
#define Hasher_hxx <OCAF/TDF/TDF_LabelMapHasher.hxx>
#define TCollection_DataMapNode TDocStd_DataMapNodeOfLabelIDMapDataMap
#define TCollection_DataMapNode_hxx <OCAF/TDocStd/TDocStd_DataMapNodeOfLabelIDMapDataMap.hxx>
#define TCollection_DataMapIterator TDocStd_DataMapIteratorOfLabelIDMapDataMap
#define TCollection_DataMapIterator_hxx <OCAF/TDocStd/TDocStd_DataMapIteratorOfLabelIDMapDataMap.hxx>
#define Handle_TCollection_DataMapNode Handle_TDocStd_DataMapNodeOfLabelIDMapDataMap
#define TCollection_DataMapNode_Type_() TDocStd_DataMapNodeOfLabelIDMapDataMap_Type_()
#define TCollection_DataMap TDocStd_LabelIDMapDataMap
#define TCollection_DataMap_hxx <OCAF/TDocStd/TDocStd_LabelIDMapDataMap.hxx>
#include <Foundation/TCollection/TCollection_DataMapNode.gxx>

