// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Foundation/Message/Message_SequenceNodeOfSequenceOfPrinters.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <Foundation/Message/Message_Printer.hxx>
#include <Foundation/Message/Message_SequenceOfPrinters.hxx>

 


IMPLEMENT_STANDARD_TYPE(Message_SequenceNodeOfSequenceOfPrinters)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(Message_SequenceNodeOfSequenceOfPrinters)


IMPLEMENT_DOWNCAST(Message_SequenceNodeOfSequenceOfPrinters,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(Message_SequenceNodeOfSequenceOfPrinters)


#define SeqItem Handle(Message_Printer)
#define SeqItem_hxx <Foundation/Message/Message_Printer.hxx>
#define TCollection_SequenceNode Message_SequenceNodeOfSequenceOfPrinters
#define TCollection_SequenceNode_hxx <Foundation/Message/Message_SequenceNodeOfSequenceOfPrinters.hxx>
#define Handle_TCollection_SequenceNode Handle_Message_SequenceNodeOfSequenceOfPrinters
#define TCollection_SequenceNode_Type_() Message_SequenceNodeOfSequenceOfPrinters_Type_()
#define TCollection_Sequence Message_SequenceOfPrinters
#define TCollection_Sequence_hxx <Foundation/Message/Message_SequenceOfPrinters.hxx>
#include <TCollection_SequenceNode.gxx>

