// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Geometry/TColGeom2d/TColGeom2d_HSequenceOfBoundedCurve.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Geometry/Geom2d/Geom2d_BoundedCurve.hxx>
#include <Geometry/TColGeom2d/TColGeom2d_SequenceOfBoundedCurve.hxx>

 


IMPLEMENT_STANDARD_TYPE(TColGeom2d_HSequenceOfBoundedCurve)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(TColGeom2d_HSequenceOfBoundedCurve)


IMPLEMENT_DOWNCAST(TColGeom2d_HSequenceOfBoundedCurve,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(TColGeom2d_HSequenceOfBoundedCurve)


#define Item Handle(Geom2d_BoundedCurve)
#define Item_hxx <Geometry/Geom2d/Geom2d_BoundedCurve.hxx>
#define TheSequence TColGeom2d_SequenceOfBoundedCurve
#define TheSequence_hxx <Geometry/TColGeom2d/TColGeom2d_SequenceOfBoundedCurve.hxx>
#define TCollection_HSequence TColGeom2d_HSequenceOfBoundedCurve
#define TCollection_HSequence_hxx <Geometry/TColGeom2d/TColGeom2d_HSequenceOfBoundedCurve.hxx>
#define Handle_TCollection_HSequence Handle_TColGeom2d_HSequenceOfBoundedCurve
#define TCollection_HSequence_Type_() TColGeom2d_HSequenceOfBoundedCurve_Type_()
#include <Foundation/TCollection/TCollection_HSequence.gxx>

