// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _StepFEA_Surface3dElementRepresentation_HeaderFile
#define _StepFEA_Surface3dElementRepresentation_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <DataExchange/StepFEA/Handle_StepFEA_Surface3dElementRepresentation.hxx>

#include <DataExchange/StepFEA/Handle_StepFEA_FeaModel3d.hxx>
#include <DataExchange/StepElement/Handle_StepElement_Surface3dElementDescriptor.hxx>
#include <DataExchange/StepElement/Handle_StepElement_SurfaceElementProperty.hxx>
#include <DataExchange/StepElement/Handle_StepElement_ElementMaterial.hxx>
#include <DataExchange/StepFEA/StepFEA_ElementRepresentation.hxx>
#include <Foundation/TCollection/Handle_TCollection_HAsciiString.hxx>
#include <DataExchange/StepRepr/Handle_StepRepr_HArray1OfRepresentationItem.hxx>
#include <DataExchange/StepRepr/Handle_StepRepr_RepresentationContext.hxx>
#include <DataExchange/StepFEA/Handle_StepFEA_HArray1OfNodeRepresentation.hxx>
class StepFEA_FeaModel3d;
class StepElement_Surface3dElementDescriptor;
class StepElement_SurfaceElementProperty;
class StepElement_ElementMaterial;
class TCollection_HAsciiString;
class StepRepr_HArray1OfRepresentationItem;
class StepRepr_RepresentationContext;
class StepFEA_HArray1OfNodeRepresentation;


//! Representation of STEP entity Surface3dElementRepresentation
class StepFEA_Surface3dElementRepresentation : public StepFEA_ElementRepresentation
{

public:

  
  //! Empty constructor
  Standard_EXPORT StepFEA_Surface3dElementRepresentation();
  
  //! Initialize all fields (own and inherited)
  Standard_EXPORT   void Init (const Handle(TCollection_HAsciiString)& aRepresentation_Name, const Handle(StepRepr_HArray1OfRepresentationItem)& aRepresentation_Items, const Handle(StepRepr_RepresentationContext)& aRepresentation_ContextOfItems, const Handle(StepFEA_HArray1OfNodeRepresentation)& aElementRepresentation_NodeList, const Handle(StepFEA_FeaModel3d)& aModelRef, const Handle(StepElement_Surface3dElementDescriptor)& aElementDescriptor, const Handle(StepElement_SurfaceElementProperty)& aProperty, const Handle(StepElement_ElementMaterial)& aMaterial) ;
  
  //! Returns field ModelRef
  Standard_EXPORT   Handle(StepFEA_FeaModel3d) ModelRef()  const;
  
  //! Set field ModelRef
  Standard_EXPORT   void SetModelRef (const Handle(StepFEA_FeaModel3d)& ModelRef) ;
  
  //! Returns field ElementDescriptor
  Standard_EXPORT   Handle(StepElement_Surface3dElementDescriptor) ElementDescriptor()  const;
  
  //! Set field ElementDescriptor
  Standard_EXPORT   void SetElementDescriptor (const Handle(StepElement_Surface3dElementDescriptor)& ElementDescriptor) ;
  
  //! Returns field Property
  Standard_EXPORT   Handle(StepElement_SurfaceElementProperty) Property()  const;
  
  //! Set field Property
  Standard_EXPORT   void SetProperty (const Handle(StepElement_SurfaceElementProperty)& Property) ;
  
  //! Returns field Material
  Standard_EXPORT   Handle(StepElement_ElementMaterial) Material()  const;
  
  //! Set field Material
  Standard_EXPORT   void SetMaterial (const Handle(StepElement_ElementMaterial)& Material) ;




  DEFINE_STANDARD_RTTI(StepFEA_Surface3dElementRepresentation)

protected:




private: 


  Handle(StepFEA_FeaModel3d) theModelRef;
  Handle(StepElement_Surface3dElementDescriptor) theElementDescriptor;
  Handle(StepElement_SurfaceElementProperty) theProperty;
  Handle(StepElement_ElementMaterial) theMaterial;


};







#endif // _StepFEA_Surface3dElementRepresentation_HeaderFile
