// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_StepBasic_ConversionBasedUnitAndVolumeUnit_HeaderFile
#define _Handle_StepBasic_ConversionBasedUnitAndVolumeUnit_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <DataExchange/StepBasic/Handle_StepBasic_ConversionBasedUnit.hxx>

class Standard_Transient;
class Handle(Standard_Type);
class Handle(StepBasic_ConversionBasedUnit);
class StepBasic_ConversionBasedUnitAndVolumeUnit;

DEFINE_STANDARD_HANDLE(StepBasic_ConversionBasedUnitAndVolumeUnit, StepBasic_ConversionBasedUnit)

#endif // _Handle_StepBasic_ConversionBasedUnitAndVolumeUnit_HeaderFile
