// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <DataExchange/StepAP214/StepAP214_HArray1OfPersonAndOrganizationItem.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <Foundation/Standard/Standard_RangeError.hxx>
#include <Foundation/Standard/Standard_DimensionMismatch.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_OutOfMemory.hxx>
#include <DataExchange/StepAP214/StepAP214_PersonAndOrganizationItem.hxx>
#include <DataExchange/StepAP214/StepAP214_Array1OfPersonAndOrganizationItem.hxx>

 


IMPLEMENT_STANDARD_TYPE(StepAP214_HArray1OfPersonAndOrganizationItem)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(StepAP214_HArray1OfPersonAndOrganizationItem)


IMPLEMENT_DOWNCAST(StepAP214_HArray1OfPersonAndOrganizationItem,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(StepAP214_HArray1OfPersonAndOrganizationItem)


#define ItemHArray1 StepAP214_PersonAndOrganizationItem
#define ItemHArray1_hxx <DataExchange/StepAP214/StepAP214_PersonAndOrganizationItem.hxx>
#define TheArray1 StepAP214_Array1OfPersonAndOrganizationItem
#define TheArray1_hxx <DataExchange/StepAP214/StepAP214_Array1OfPersonAndOrganizationItem.hxx>
#define TCollection_HArray1 StepAP214_HArray1OfPersonAndOrganizationItem
#define TCollection_HArray1_hxx <DataExchange/StepAP214/StepAP214_HArray1OfPersonAndOrganizationItem.hxx>
#define Handle_TCollection_HArray1 Handle_StepAP214_HArray1OfPersonAndOrganizationItem
#define TCollection_HArray1_Type_() StepAP214_HArray1OfPersonAndOrganizationItem_Type_()
#include <Foundation/TCollection/TCollection_HArray1.gxx>

