// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _PColStd_VArrayTNodeOfFieldOfHArray2OfInteger_HeaderFile
#define _PColStd_VArrayTNodeOfFieldOfHArray2OfInteger_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineAlloc.hxx>
#include <Foundation/Standard/Standard_Macro.hxx>

#include <Foundation/Standard/Standard_Integer.hxx>
#include <Handle_PColStd_VArrayNodeOfFieldOfHArray2OfInteger.hxx>
#include <Foundation/Standard/Standard_Address.hxx>
class PColStd_FieldOfHArray2OfInteger;
class PColStd_VArrayNodeOfFieldOfHArray2OfInteger;



class PColStd_VArrayTNodeOfFieldOfHArray2OfInteger 
{
public:

  DEFINE_STANDARD_ALLOC

  
    PColStd_VArrayTNodeOfFieldOfHArray2OfInteger();
  
    PColStd_VArrayTNodeOfFieldOfHArray2OfInteger(const Standard_Integer& aValue);
  
      void SetValue (const Standard_Integer& aValue) ;
  
      Standard_Address Value()  const;




protected:





private:



  Standard_Integer myValue;


};

#define Item Standard_Integer
#define Item_hxx <Foundation/Standard/Standard_Integer.hxx>
#define DBC_VArrayNode PColStd_VArrayNodeOfFieldOfHArray2OfInteger
#define DBC_VArrayNode_hxx <OCAF/PColStd/PColStd_VArrayNodeOfFieldOfHArray2OfInteger.hxx>
#define DBC_VArrayTNode PColStd_VArrayTNodeOfFieldOfHArray2OfInteger
#define DBC_VArrayTNode_hxx <OCAF/PColStd/PColStd_VArrayTNodeOfFieldOfHArray2OfInteger.hxx>
#define Handle_DBC_VArrayNode Handle_PColStd_VArrayNodeOfFieldOfHArray2OfInteger
#define DBC_VArrayNode_Type_() PColStd_VArrayNodeOfFieldOfHArray2OfInteger_Type_()
#define DBC_VArray PColStd_FieldOfHArray2OfInteger
#define DBC_VArray_hxx <OCAF/PColStd/PColStd_FieldOfHArray2OfInteger.hxx>

#include <OCAF/DBC/DBC_VArrayTNode.lxx>

#undef Item
#undef Item_hxx
#undef DBC_VArrayNode
#undef DBC_VArrayNode_hxx
#undef DBC_VArrayTNode
#undef DBC_VArrayTNode_hxx
#undef Handle_DBC_VArrayNode
#undef DBC_VArrayNode_Type_
#undef DBC_VArray
#undef DBC_VArray_hxx




#endif // _PColStd_VArrayTNodeOfFieldOfHArray2OfInteger_HeaderFile
