// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Standard_ConstructionError.hxx>
#include <TopoDS_Shape.hxx>
#include <gp_Vec.hxx>
#include <gp_Dir.hxx>
#include <Sweep_NumShape.hxx>
#include <TopLoc_Location.hxx>
#include <BRepSweep_Prism.hxx>

 


