// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _HLRTest_Projector_HeaderFile
#define _HLRTest_Projector_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <Viewer/HLRTest/Handle_HLRTest_Projector.hxx>

#include <ModelingAlgorithms/HLRAlgo/HLRAlgo_Projector.hxx>
#include <Viewer/Draw/Draw_Drawable3D.hxx>
#include <Viewer/Draw/Handle_Draw_Drawable3D.hxx>
#include <Foundation/Standard/Standard_OStream.hxx>
#include <Viewer/Draw/Draw_Interpretor.hxx>
class HLRAlgo_Projector;
class Draw_Display;
class Draw_Drawable3D;


//! Draw Variable Projector to test.
class HLRTest_Projector : public Draw_Drawable3D
{

public:

  
  Standard_EXPORT HLRTest_Projector(const HLRAlgo_Projector& P);
  
     const  HLRAlgo_Projector& Projector()  const;
  
  //! Does nothhing,
  Standard_EXPORT   void DrawOn (Draw_Display& dis)  const;
  
  //! For variable copy.
  Standard_EXPORT virtual   Handle(Draw_Drawable3D) Copy()  const;
  
  //! For variable dump.
  Standard_EXPORT virtual   void Dump (Standard_OStream& S)  const;
  
  //! For variable whatis command. Set  as a result  the
  //! type of the variable.
  Standard_EXPORT virtual   void Whatis (Draw_Interpretor& I)  const;




  DEFINE_STANDARD_RTTI(HLRTest_Projector)

protected:




private: 


  HLRAlgo_Projector myProjector;


};


#include <Viewer/HLRTest/HLRTest_Projector.lxx>





#endif // _HLRTest_Projector_HeaderFile
