// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ModelingAlgorithms/IntCurve/IntCurve_MyImpParToolOfIntImpConicParConic.hxx>

#include <ModelingAlgorithms/IntCurve/IntCurve_IConicTool.hxx>
#include <ModelingAlgorithms/IntCurve/IntCurve_PConic.hxx>
#include <ModelingAlgorithms/IntCurve/IntCurve_PConicTool.hxx>
 

#define ImpTool IntCurve_IConicTool
#define ImpTool_hxx <ModelingAlgorithms/IntCurve/IntCurve_IConicTool.hxx>
#define ParCurve IntCurve_PConic
#define ParCurve_hxx <ModelingAlgorithms/IntCurve/IntCurve_PConic.hxx>
#define ParTool IntCurve_PConicTool
#define ParTool_hxx <ModelingAlgorithms/IntCurve/IntCurve_PConicTool.hxx>
#define IntImpParGen_ImpParTool IntCurve_MyImpParToolOfIntImpConicParConic
#define IntImpParGen_ImpParTool_hxx <ModelingAlgorithms/IntCurve/IntCurve_MyImpParToolOfIntImpConicParConic.hxx>
#include <IntImpParGen_ImpParTool.gxx>

