// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _StepRepr_DerivedShapeAspect_HeaderFile
#define _StepRepr_DerivedShapeAspect_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <DataExchange/StepRepr/Handle_StepRepr_DerivedShapeAspect.hxx>

#include <DataExchange/StepRepr/StepRepr_ShapeAspect.hxx>


//! Added for Dimensional Tolerances
class StepRepr_DerivedShapeAspect : public StepRepr_ShapeAspect
{

public:

  
  Standard_EXPORT StepRepr_DerivedShapeAspect();




  DEFINE_STANDARD_RTTI(StepRepr_DerivedShapeAspect)

protected:




private: 




};







#endif // _StepRepr_DerivedShapeAspect_HeaderFile
