// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_PBRep_PolygonOnSurface_HeaderFile
#define _Handle_PBRep_PolygonOnSurface_HeaderFile

#include <Foundation/Standard/Standard_Macro.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <Foundation/Standard/Standard.hxx>
#include <OCAF/PBRep/Handle_PBRep_CurveRepresentation.hxx>

class Standard_Persistent;
class Handle(Standard_Type);
class Handle(PBRep_CurveRepresentation);
class PBRep_PolygonOnSurface;

DEFINE_STANDARD_PHANDLE(PBRep_PolygonOnSurface,PBRep_CurveRepresentation)

#endif
