// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _StepDimTol_CylindricityTolerance_HeaderFile
#define _StepDimTol_CylindricityTolerance_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <DataExchange/StepDimTol/Handle_StepDimTol_CylindricityTolerance.hxx>

#include <DataExchange/StepDimTol/StepDimTol_GeometricTolerance.hxx>


//! Representation of STEP entity CylindricityTolerance
class StepDimTol_CylindricityTolerance : public StepDimTol_GeometricTolerance
{

public:

  
  //! Empty constructor
  Standard_EXPORT StepDimTol_CylindricityTolerance();




  DEFINE_STANDARD_RTTI(StepDimTol_CylindricityTolerance)

protected:




private: 




};







#endif // _StepDimTol_CylindricityTolerance_HeaderFile
