// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _StepDimTol_PerpendicularityTolerance_HeaderFile
#define _StepDimTol_PerpendicularityTolerance_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <DataExchange/StepDimTol/Handle_StepDimTol_PerpendicularityTolerance.hxx>

#include <DataExchange/StepDimTol/StepDimTol_GeometricToleranceWithDatumReference.hxx>


//! Representation of STEP entity PerpendicularityTolerance
class StepDimTol_PerpendicularityTolerance : public StepDimTol_GeometricToleranceWithDatumReference
{

public:

  
  //! Empty constructor
  Standard_EXPORT StepDimTol_PerpendicularityTolerance();




  DEFINE_STANDARD_RTTI(StepDimTol_PerpendicularityTolerance)

protected:




private: 




};







#endif // _StepDimTol_PerpendicularityTolerance_HeaderFile
