// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_BRep_CurveOnClosedSurface_HeaderFile
#define _Handle_BRep_CurveOnClosedSurface_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <ModelingData/BRep/Handle_BRep_CurveOnSurface.hxx>

class Standard_Transient;
class Handle(Standard_Type);
class Handle(BRep_CurveOnSurface);
class BRep_CurveOnClosedSurface;

DEFINE_STANDARD_HANDLE(BRep_CurveOnClosedSurface, BRep_CurveOnSurface)

#endif // _Handle_BRep_CurveOnClosedSurface_HeaderFile
