// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_PTopoDS_Wire_HeaderFile
#define _Handle_PTopoDS_Wire_HeaderFile

#include <Foundation/Standard/Standard_Macro.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <Foundation/Standard/Standard.hxx>
#include <OCAF/PTopoDS/Handle_PTopoDS_HShape.hxx>

class Standard_Persistent;
class Handle(Standard_Type);
class Handle(PTopoDS_HShape);
class PTopoDS_Wire;

DEFINE_STANDARD_PHANDLE(PTopoDS_Wire,PTopoDS_HShape)

#endif
