// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _PTopoDS_Solid_HeaderFile
#define _PTopoDS_Solid_HeaderFile

#include <Foundation/Standard/Standard_Macro.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <Foundation/Standard/Standard.hxx>
#include <OCAF/PTopoDS/Handle_PTopoDS_Solid.hxx>

#include <OCAF/PTopoDS/PTopoDS_HShape.hxx>


class PTopoDS_Solid : public PTopoDS_HShape
{

public:

  
  Standard_EXPORT PTopoDS_Solid();

PTopoDS_Solid(const Storage_stCONSTclCOM& a) : PTopoDS_HShape(a)
{
  
}



  DEFINE_STANDARD_RTTI(PTopoDS_Solid)

protected:




private: 




};







#endif // _PTopoDS_Solid_HeaderFile
