// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <DataExchange/TransferBRep/TransferBRep_SequenceNodeOfSequenceOfTransferResultInfo.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <DataExchange/TransferBRep/TransferBRep_TransferResultInfo.hxx>
#include <DataExchange/TransferBRep/TransferBRep_SequenceOfTransferResultInfo.hxx>

 


IMPLEMENT_STANDARD_TYPE(TransferBRep_SequenceNodeOfSequenceOfTransferResultInfo)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(TransferBRep_SequenceNodeOfSequenceOfTransferResultInfo)


IMPLEMENT_DOWNCAST(TransferBRep_SequenceNodeOfSequenceOfTransferResultInfo,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(TransferBRep_SequenceNodeOfSequenceOfTransferResultInfo)


#define SeqItem Handle(TransferBRep_TransferResultInfo)
#define SeqItem_hxx <DataExchange/TransferBRep/TransferBRep_TransferResultInfo.hxx>
#define TCollection_SequenceNode TransferBRep_SequenceNodeOfSequenceOfTransferResultInfo
#define TCollection_SequenceNode_hxx <DataExchange/TransferBRep/TransferBRep_SequenceNodeOfSequenceOfTransferResultInfo.hxx>
#define Handle_TCollection_SequenceNode Handle_TransferBRep_SequenceNodeOfSequenceOfTransferResultInfo
#define TCollection_SequenceNode_Type_() TransferBRep_SequenceNodeOfSequenceOfTransferResultInfo_Type_()
#define TCollection_Sequence TransferBRep_SequenceOfTransferResultInfo
#define TCollection_Sequence_hxx <DataExchange/TransferBRep/TransferBRep_SequenceOfTransferResultInfo.hxx>
#include <Foundation/TCollection/TCollection_SequenceNode.gxx>

