// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <OCAF/TNaming/TNaming_ListIteratorOfListOfMapOfShape.hxx>

#include <Foundation/Standard/Standard_NoMoreObject.hxx>
#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <OCAF/TNaming/TNaming_ListOfMapOfShape.hxx>
#include <ModelingData/TopTools/TopTools_MapOfShape.hxx>
#include <OCAF/TNaming/TNaming_ListNodeOfListOfMapOfShape.hxx>
 

#define Item TopTools_MapOfShape
#define Item_hxx <ModelingData/TopTools/TopTools_MapOfShape.hxx>
#define TCollection_ListNode TNaming_ListNodeOfListOfMapOfShape
#define TCollection_ListNode_hxx <OCAF/TNaming/TNaming_ListNodeOfListOfMapOfShape.hxx>
#define TCollection_ListIterator TNaming_ListIteratorOfListOfMapOfShape
#define TCollection_ListIterator_hxx <OCAF/TNaming/TNaming_ListIteratorOfListOfMapOfShape.hxx>
#define Handle_TCollection_ListNode Handle_TNaming_ListNodeOfListOfMapOfShape
#define TCollection_ListNode_Type_() TNaming_ListNodeOfListOfMapOfShape_Type_()
#define TCollection_List TNaming_ListOfMapOfShape
#define TCollection_List_hxx <OCAF/TNaming/TNaming_ListOfMapOfShape.hxx>
#include <Foundation/TCollection/TCollection_ListIterator.gxx>

