// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _TopOpeBRepTool_HBoxTool_HeaderFile
#define _TopOpeBRepTool_HBoxTool_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <Handle_TopOpeBRepTool_HBoxTool.hxx>

#include <ModelingAlgorithms/TopOpeBRepTool/TopOpeBRepTool_IndexedDataMapOfShapeBox.hxx>
#include <Foundation/MMgt/MMgt_TShared.hxx>
#include <ModelingData/TopAbs/TopAbs_ShapeEnum.hxx>
#include <Foundation/Standard/Standard_Integer.hxx>
#include <Foundation/Standard/Standard_Boolean.hxx>
class TopoDS_Shape;
class Bnd_Box;
class TopOpeBRepTool_IndexedDataMapOfShapeBox;



class TopOpeBRepTool_HBoxTool : public MMgt_TShared
{

public:

  
  Standard_EXPORT TopOpeBRepTool_HBoxTool();
  
  Standard_EXPORT   void Clear() ;
  
  Standard_EXPORT   void AddBoxes (const TopoDS_Shape& S, const TopAbs_ShapeEnum TS, const TopAbs_ShapeEnum TA = TopAbs_SHAPE) ;
  
  Standard_EXPORT   void AddBox (const TopoDS_Shape& S) ;
  
  Standard_EXPORT static   void ComputeBox (const TopoDS_Shape& S, Bnd_Box& B) ;
  
  Standard_EXPORT static   void ComputeBoxOnVertices (const TopoDS_Shape& S, Bnd_Box& B) ;
  
  Standard_EXPORT static   void DumpB (const Bnd_Box& B) ;
  
  Standard_EXPORT  const  Bnd_Box& Box (const TopoDS_Shape& S) ;
  
  Standard_EXPORT  const  Bnd_Box& Box (const Standard_Integer I)  const;
  
  Standard_EXPORT   Standard_Boolean HasBox (const TopoDS_Shape& S)  const;
  
  Standard_EXPORT  const  TopoDS_Shape& Shape (const Standard_Integer I)  const;
  
  Standard_EXPORT   Standard_Integer Index (const TopoDS_Shape& S)  const;
  
  Standard_EXPORT   Standard_Integer Extent()  const;
  
  Standard_EXPORT   TopOpeBRepTool_IndexedDataMapOfShapeBox& ChangeIMS() ;
  
  Standard_EXPORT  const  TopOpeBRepTool_IndexedDataMapOfShapeBox& IMS()  const;




  DEFINE_STANDARD_RTTI(TopOpeBRepTool_HBoxTool)

protected:




private: 


  TopOpeBRepTool_IndexedDataMapOfShapeBox myIMS;


};







#endif // _TopOpeBRepTool_HBoxTool_HeaderFile
