// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _TopoDS_UnCompatibleShapes_HeaderFile
#define _TopoDS_UnCompatibleShapes_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <Foundation/Standard/Standard_DefineException.hxx>
#include <Foundation/Standard/Standard_SStream.hxx>
#include <Foundation/Standard/Standard_DomainError.hxx>
#include <ModelingData/TopoDS/Handle_TopoDS_UnCompatibleShapes.hxx>

#if !defined No_Exception && !defined No_TopoDS_UnCompatibleShapes
  #define TopoDS_UnCompatibleShapes_Raise_if(CONDITION, MESSAGE) \
  if (CONDITION) TopoDS_UnCompatibleShapes::Raise(MESSAGE);
#else
  #define TopoDS_UnCompatibleShapes_Raise_if(CONDITION, MESSAGE)
#endif

DEFINE_STANDARD_EXCEPTION(TopoDS_UnCompatibleShapes, Standard_DomainError)

#endif // _TopoDS_UnCompatibleShapes_HeaderFile
