// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <MAT2d_DataMapOfIntegerPnt2d.hxx>

#include <Foundation/Standard/Standard_DomainError.hxx>
#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <Mathematics/Primitives/gp_Pnt2d.hxx>
#include <Foundation/TColStd/TColStd_MapIntegerHasher.hxx>
#include <MAT2d_DataMapNodeOfDataMapOfIntegerPnt2d.hxx>
#include <MAT2d_DataMapIteratorOfDataMapOfIntegerPnt2d.hxx>
 

#define TheKey Standard_Integer
#define TheKey_hxx <Foundation/Standard/Standard_Integer.hxx>
#define TheItem gp_Pnt2d
#define TheItem_hxx <Mathematics/Primitives/gp_Pnt2d.hxx>
#define Hasher TColStd_MapIntegerHasher
#define Hasher_hxx <Foundation/TColStd/TColStd_MapIntegerHasher.hxx>
#define TCollection_DataMapNode MAT2d_DataMapNodeOfDataMapOfIntegerPnt2d
#define TCollection_DataMapNode_hxx <MAT2d_DataMapNodeOfDataMapOfIntegerPnt2d.hxx>
#define TCollection_DataMapIterator MAT2d_DataMapIteratorOfDataMapOfIntegerPnt2d
#define TCollection_DataMapIterator_hxx <MAT2d_DataMapIteratorOfDataMapOfIntegerPnt2d.hxx>
#define Handle_TCollection_DataMapNode Handle_MAT2d_DataMapNodeOfDataMapOfIntegerPnt2d
#define TCollection_DataMapNode_Type_() MAT2d_DataMapNodeOfDataMapOfIntegerPnt2d_Type_()
#define TCollection_DataMap MAT2d_DataMapOfIntegerPnt2d
#define TCollection_DataMap_hxx <MAT2d_DataMapOfIntegerPnt2d.hxx>
#include <Foundation/TCollection/TCollection_DataMap.gxx>

