// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ModelingAlgorithms/MAT2d/MAT2d_DataMapIteratorOfDataMapOfIntegerSequenceOfConnexion.hxx>

#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <ModelingAlgorithms/MAT2d/MAT2d_SequenceOfConnexion.hxx>
#include <Foundation/TColStd/TColStd_MapIntegerHasher.hxx>
#include <ModelingAlgorithms/MAT2d/MAT2d_DataMapOfIntegerSequenceOfConnexion.hxx>
#include <ModelingAlgorithms/MAT2d/MAT2d_DataMapNodeOfDataMapOfIntegerSequenceOfConnexion.hxx>
 

#define TheKey Standard_Integer
#define TheKey_hxx <Foundation/Standard/Standard_Integer.hxx>
#define TheItem MAT2d_SequenceOfConnexion
#define TheItem_hxx <ModelingAlgorithms/MAT2d/MAT2d_SequenceOfConnexion.hxx>
#define Hasher TColStd_MapIntegerHasher
#define Hasher_hxx <Foundation/TColStd/TColStd_MapIntegerHasher.hxx>
#define TCollection_DataMapNode MAT2d_DataMapNodeOfDataMapOfIntegerSequenceOfConnexion
#define TCollection_DataMapNode_hxx <ModelingAlgorithms/MAT2d/MAT2d_DataMapNodeOfDataMapOfIntegerSequenceOfConnexion.hxx>
#define TCollection_DataMapIterator MAT2d_DataMapIteratorOfDataMapOfIntegerSequenceOfConnexion
#define TCollection_DataMapIterator_hxx <ModelingAlgorithms/MAT2d/MAT2d_DataMapIteratorOfDataMapOfIntegerSequenceOfConnexion.hxx>
#define Handle_TCollection_DataMapNode Handle_MAT2d_DataMapNodeOfDataMapOfIntegerSequenceOfConnexion
#define TCollection_DataMapNode_Type_() MAT2d_DataMapNodeOfDataMapOfIntegerSequenceOfConnexion_Type_()
#define TCollection_DataMap MAT2d_DataMapOfIntegerSequenceOfConnexion
#define TCollection_DataMap_hxx <ModelingAlgorithms/MAT2d/MAT2d_DataMapOfIntegerSequenceOfConnexion.hxx>
#include <Foundation/TCollection/TCollection_DataMapIterator.gxx>

