// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ModelingAlgorithms/Contap/Contap_TheSequenceOfPoint.hxx>

#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <ModelingAlgorithms/Contap/Contap_Point.hxx>
#include <ModelingAlgorithms/Contap/Contap_SequenceNodeOfTheSequenceOfPoint.hxx>
 

#define SeqItem Contap_Point
#define SeqItem_hxx <ModelingAlgorithms/Contap/Contap_Point.hxx>
#define TCollection_SequenceNode Contap_SequenceNodeOfTheSequenceOfPoint
#define TCollection_SequenceNode_hxx <ModelingAlgorithms/Contap/Contap_SequenceNodeOfTheSequenceOfPoint.hxx>
#define Handle_TCollection_SequenceNode Handle_Contap_SequenceNodeOfTheSequenceOfPoint
#define TCollection_SequenceNode_Type_() Contap_SequenceNodeOfTheSequenceOfPoint_Type_()
#define TCollection_Sequence Contap_TheSequenceOfPoint
#define TCollection_Sequence_hxx <ModelingAlgorithms/Contap/Contap_TheSequenceOfPoint.hxx>
#include <Foundation/TCollection/TCollection_Sequence.gxx>

