// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <DataExchange/IGESDraw/IGESDraw_HArray1OfConnectPoint.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <Foundation/Standard/Standard_RangeError.hxx>
#include <Foundation/Standard/Standard_DimensionMismatch.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_OutOfMemory.hxx>
#include <DataExchange/IGESDraw/IGESDraw_ConnectPoint.hxx>
#include <DataExchange/IGESDraw/IGESDraw_Array1OfConnectPoint.hxx>

 


IMPLEMENT_STANDARD_TYPE(IGESDraw_HArray1OfConnectPoint)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(IGESDraw_HArray1OfConnectPoint)


IMPLEMENT_DOWNCAST(IGESDraw_HArray1OfConnectPoint,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(IGESDraw_HArray1OfConnectPoint)


#define ItemHArray1 Handle(IGESDraw_ConnectPoint)
#define ItemHArray1_hxx <DataExchange/IGESDraw/IGESDraw_ConnectPoint.hxx>
#define TheArray1 IGESDraw_Array1OfConnectPoint
#define TheArray1_hxx <DataExchange/IGESDraw/IGESDraw_Array1OfConnectPoint.hxx>
#define TCollection_HArray1 IGESDraw_HArray1OfConnectPoint
#define TCollection_HArray1_hxx <DataExchange/IGESDraw/IGESDraw_HArray1OfConnectPoint.hxx>
#define Handle_TCollection_HArray1 Handle_IGESDraw_HArray1OfConnectPoint
#define TCollection_HArray1_Type_() IGESDraw_HArray1OfConnectPoint_Type_()
#include <Foundation/TCollection/TCollection_HArray1.gxx>

