// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <StepGeom_CartesianTransformationOperator2d.hxx>
#include <gp_Trsf2d.hxx>
#include <StepToGeom_MakeTransformation2d.hxx>

 


