// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _IntSurf_ListIteratorOfListOfPntOn2S_HeaderFile
#define _IntSurf_ListIteratorOfListOfPntOn2S_HeaderFile

#include <ModelingAlgorithms/IntSurf/IntSurf_ListOfPntOn2S.hxx>

typedef IntSurf_ListOfPntOn2S::iterator IntSurf_ListIteratorOfListOfPntOn2S;

#endif // _IntSurf_ListIteratorOfListOfPntOn2S_HeaderFile
