// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ModelingAlgorithms/Plate/Plate_SequenceOfPinpointConstraint.hxx>

#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <ModelingAlgorithms/Plate/Plate_PinpointConstraint.hxx>
#include <ModelingAlgorithms/Plate/Plate_SequenceNodeOfSequenceOfPinpointConstraint.hxx>
 

#define SeqItem Plate_PinpointConstraint
#define SeqItem_hxx <ModelingAlgorithms/Plate/Plate_PinpointConstraint.hxx>
#define TCollection_SequenceNode Plate_SequenceNodeOfSequenceOfPinpointConstraint
#define TCollection_SequenceNode_hxx <ModelingAlgorithms/Plate/Plate_SequenceNodeOfSequenceOfPinpointConstraint.hxx>
#define Handle_TCollection_SequenceNode Handle_Plate_SequenceNodeOfSequenceOfPinpointConstraint
#define TCollection_SequenceNode_Type_() Plate_SequenceNodeOfSequenceOfPinpointConstraint_Type_()
#define TCollection_Sequence Plate_SequenceOfPinpointConstraint
#define TCollection_Sequence_hxx <ModelingAlgorithms/Plate/Plate_SequenceOfPinpointConstraint.hxx>
#include <Foundation/TCollection/TCollection_Sequence.gxx>

