// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ModelingAlgorithms/TopOpeBRepDS/TopOpeBRepDS_ListNodeOfListOfInterference.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <ModelingAlgorithms/TopOpeBRepDS/TopOpeBRepDS_Interference.hxx>
#include <ModelingAlgorithms/TopOpeBRepDS/TopOpeBRepDS_ListOfInterference.hxx>
#include <ModelingAlgorithms/TopOpeBRepDS/TopOpeBRepDS_ListIteratorOfListOfInterference.hxx>

 


IMPLEMENT_STANDARD_TYPE(TopOpeBRepDS_ListNodeOfListOfInterference)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(TopOpeBRepDS_ListNodeOfListOfInterference)


IMPLEMENT_DOWNCAST(TopOpeBRepDS_ListNodeOfListOfInterference,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(TopOpeBRepDS_ListNodeOfListOfInterference)


#define Item Handle(TopOpeBRepDS_Interference)
#define Item_hxx <ModelingAlgorithms/TopOpeBRepDS/TopOpeBRepDS_Interference.hxx>
#define TCollection_ListNode TopOpeBRepDS_ListNodeOfListOfInterference
#define TCollection_ListNode_hxx <ModelingAlgorithms/TopOpeBRepDS/TopOpeBRepDS_ListNodeOfListOfInterference.hxx>
#define TCollection_ListIterator TopOpeBRepDS_ListIteratorOfListOfInterference
#define TCollection_ListIterator_hxx <ModelingAlgorithms/TopOpeBRepDS/TopOpeBRepDS_ListIteratorOfListOfInterference.hxx>
#define Handle_TCollection_ListNode Handle_TopOpeBRepDS_ListNodeOfListOfInterference
#define TCollection_ListNode_Type_() TopOpeBRepDS_ListNodeOfListOfInterference_Type_()
#define TCollection_List TopOpeBRepDS_ListOfInterference
#define TCollection_List_hxx <ModelingAlgorithms/TopOpeBRepDS/TopOpeBRepDS_ListOfInterference.hxx>
#include <Foundation/TCollection/TCollection_ListNode.gxx>

