// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <TopOpeBRepDS_Array1OfDataMapOfIntegerListOfInterference.hxx>

#include <Foundation/Standard/Standard_RangeError.hxx>
#include <Foundation/Standard/Standard_DimensionMismatch.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_OutOfMemory.hxx>
#include <TopOpeBRepDS_DataMapOfIntegerListOfInterference.hxx>
 

#define Array1Item TopOpeBRepDS_DataMapOfIntegerListOfInterference
#define Array1Item_hxx <TopOpeBRepDS_DataMapOfIntegerListOfInterference.hxx>
#define TCollection_Array1 TopOpeBRepDS_Array1OfDataMapOfIntegerListOfInterference
#define TCollection_Array1_hxx <TopOpeBRepDS_Array1OfDataMapOfIntegerListOfInterference.hxx>
#include <Foundation/TCollection/TCollection_Array1.gxx>

