// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _ChFiDS_ListIteratorOfRegularities_HeaderFile
#define _ChFiDS_ListIteratorOfRegularities_HeaderFile

#include <ModelingAlgorithms/ChFiDS/ChFiDS_Regularities.hxx>

typedef ChFiDS_Regularities::iterator ChFiDS_ListIteratorOfRegularities;

#endif // _ChFiDS_ListIteratorOfRegularities_HeaderFile
