// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Visualization/Graphic3d/Graphic3d_Array1OfVertex.hxx>

#include <Foundation/Standard/Standard_RangeError.hxx>
#include <Foundation/Standard/Standard_DimensionMismatch.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_OutOfMemory.hxx>
 

#define Array1Item Graphic3d_Vertex
#define Array1Item_hxx <Visualization/Graphic3d/Graphic3d_Vertex.hxx>
#define TCollection_Array1 Graphic3d_Array1OfVertex
#define TCollection_Array1_hxx <Visualization/Graphic3d/Graphic3d_Array1OfVertex.hxx>
#include <Foundation/TCollection/TCollection_Array1.gxx>

