// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <TFunction_Array1OfDataMapOfGUIDDriver.hxx>

#include <Foundation/Standard/Standard_RangeError.hxx>
#include <Foundation/Standard/Standard_DimensionMismatch.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_OutOfMemory.hxx>
#include <TFunction_DataMapOfGUIDDriver.hxx>
 

#define Array1Item TFunction_DataMapOfGUIDDriver
#define Array1Item_hxx <TFunction_DataMapOfGUIDDriver.hxx>
#define TCollection_Array1 TFunction_Array1OfDataMapOfGUIDDriver
#define TCollection_Array1_hxx <TFunction_Array1OfDataMapOfGUIDDriver.hxx>
#include <Foundation/TCollection/TCollection_Array1.gxx>

