// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <OCAF/TFunction/TFunction_HArray1OfDataMapOfGUIDDriver.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <Foundation/Standard/Standard_RangeError.hxx>
#include <Foundation/Standard/Standard_DimensionMismatch.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_OutOfMemory.hxx>
#include <OCAF/TFunction/TFunction_DataMapOfGUIDDriver.hxx>
#include <OCAF/TFunction/TFunction_Array1OfDataMapOfGUIDDriver.hxx>

 


IMPLEMENT_STANDARD_TYPE(TFunction_HArray1OfDataMapOfGUIDDriver)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(TFunction_HArray1OfDataMapOfGUIDDriver)


IMPLEMENT_DOWNCAST(TFunction_HArray1OfDataMapOfGUIDDriver,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(TFunction_HArray1OfDataMapOfGUIDDriver)


#define ItemHArray1 TFunction_DataMapOfGUIDDriver
#define ItemHArray1_hxx <OCAF/TFunction/TFunction_DataMapOfGUIDDriver.hxx>
#define TheArray1 TFunction_Array1OfDataMapOfGUIDDriver
#define TheArray1_hxx <OCAF/TFunction/TFunction_Array1OfDataMapOfGUIDDriver.hxx>
#define TCollection_HArray1 TFunction_HArray1OfDataMapOfGUIDDriver
#define TCollection_HArray1_hxx <OCAF/TFunction/TFunction_HArray1OfDataMapOfGUIDDriver.hxx>
#define Handle_TCollection_HArray1 Handle_TFunction_HArray1OfDataMapOfGUIDDriver
#define TCollection_HArray1_Type_() TFunction_HArray1OfDataMapOfGUIDDriver_Type_()
#include <Foundation/TCollection/TCollection_HArray1.gxx>

