// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <MeshVS_DataMapNodeOfDataMapOfIntegerTwoColors.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <Foundation/TColStd/TColStd_MapIntegerHasher.hxx>
#include <MeshVS_DataMapOfIntegerTwoColors.hxx>
#include <MeshVS_DataMapIteratorOfDataMapOfIntegerTwoColors.hxx>

 


IMPLEMENT_STANDARD_TYPE(MeshVS_DataMapNodeOfDataMapOfIntegerTwoColors)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(MeshVS_DataMapNodeOfDataMapOfIntegerTwoColors)


IMPLEMENT_DOWNCAST(MeshVS_DataMapNodeOfDataMapOfIntegerTwoColors,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(MeshVS_DataMapNodeOfDataMapOfIntegerTwoColors)


#define TheKey Standard_Integer
#define TheKey_hxx <Foundation/Standard/Standard_Integer.hxx>
#define TheItem MeshVS_TwoColors
#define TheItem_hxx <MeshVS_TwoColors.hxx>
#define Hasher TColStd_MapIntegerHasher
#define Hasher_hxx <Foundation/TColStd/TColStd_MapIntegerHasher.hxx>
#define TCollection_DataMapNode MeshVS_DataMapNodeOfDataMapOfIntegerTwoColors
#define TCollection_DataMapNode_hxx <MeshVS_DataMapNodeOfDataMapOfIntegerTwoColors.hxx>
#define TCollection_DataMapIterator MeshVS_DataMapIteratorOfDataMapOfIntegerTwoColors
#define TCollection_DataMapIterator_hxx <MeshVS_DataMapIteratorOfDataMapOfIntegerTwoColors.hxx>
#define Handle_TCollection_DataMapNode Handle_MeshVS_DataMapNodeOfDataMapOfIntegerTwoColors
#define TCollection_DataMapNode_Type_() MeshVS_DataMapNodeOfDataMapOfIntegerTwoColors_Type_()
#define TCollection_DataMap MeshVS_DataMapOfIntegerTwoColors
#define TCollection_DataMap_hxx <MeshVS_DataMapOfIntegerTwoColors.hxx>
#include <Foundation/TCollection/TCollection_DataMapNode.gxx>

