// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Visualization/MeshVS/MeshVS_DataMapNodeOfDataMapOfIntegerColor.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <Foundation/Quantity/Quantity_Color.hxx>
#include <Foundation/TColStd/TColStd_MapIntegerHasher.hxx>
#include <Visualization/MeshVS/MeshVS_DataMapOfIntegerColor.hxx>
#include <Visualization/MeshVS/MeshVS_DataMapIteratorOfDataMapOfIntegerColor.hxx>

 


IMPLEMENT_STANDARD_TYPE(MeshVS_DataMapNodeOfDataMapOfIntegerColor)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(MeshVS_DataMapNodeOfDataMapOfIntegerColor)


IMPLEMENT_DOWNCAST(MeshVS_DataMapNodeOfDataMapOfIntegerColor,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(MeshVS_DataMapNodeOfDataMapOfIntegerColor)


#define TheKey Standard_Integer
#define TheKey_hxx <Foundation/Standard/Standard_Integer.hxx>
#define TheItem Quantity_Color
#define TheItem_hxx <Foundation/Quantity/Quantity_Color.hxx>
#define Hasher TColStd_MapIntegerHasher
#define Hasher_hxx <Foundation/TColStd/TColStd_MapIntegerHasher.hxx>
#define TCollection_DataMapNode MeshVS_DataMapNodeOfDataMapOfIntegerColor
#define TCollection_DataMapNode_hxx <Visualization/MeshVS/MeshVS_DataMapNodeOfDataMapOfIntegerColor.hxx>
#define TCollection_DataMapIterator MeshVS_DataMapIteratorOfDataMapOfIntegerColor
#define TCollection_DataMapIterator_hxx <Visualization/MeshVS/MeshVS_DataMapIteratorOfDataMapOfIntegerColor.hxx>
#define Handle_TCollection_DataMapNode Handle_MeshVS_DataMapNodeOfDataMapOfIntegerColor
#define TCollection_DataMapNode_Type_() MeshVS_DataMapNodeOfDataMapOfIntegerColor_Type_()
#define TCollection_DataMap MeshVS_DataMapOfIntegerColor
#define TCollection_DataMap_hxx <Visualization/MeshVS/MeshVS_DataMapOfIntegerColor.hxx>
#include <Foundation/TCollection/TCollection_DataMapNode.gxx>

