// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Visualization/MeshVS/MeshVS_DataMapIteratorOfDataMapOfIntegerBoolean.hxx>

#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <Foundation/TColStd/TColStd_MapIntegerHasher.hxx>
#include <Visualization/MeshVS/MeshVS_DataMapOfIntegerBoolean.hxx>
#include <Visualization/MeshVS/MeshVS_DataMapNodeOfDataMapOfIntegerBoolean.hxx>
 

#define TheKey Standard_Integer
#define TheKey_hxx <Foundation/Standard/Standard_Integer.hxx>
#define TheItem Standard_Boolean
#define TheItem_hxx <Foundation/Standard/Standard_Boolean.hxx>
#define Hasher TColStd_MapIntegerHasher
#define Hasher_hxx <Foundation/TColStd/TColStd_MapIntegerHasher.hxx>
#define TCollection_DataMapNode MeshVS_DataMapNodeOfDataMapOfIntegerBoolean
#define TCollection_DataMapNode_hxx <Visualization/MeshVS/MeshVS_DataMapNodeOfDataMapOfIntegerBoolean.hxx>
#define TCollection_DataMapIterator MeshVS_DataMapIteratorOfDataMapOfIntegerBoolean
#define TCollection_DataMapIterator_hxx <Visualization/MeshVS/MeshVS_DataMapIteratorOfDataMapOfIntegerBoolean.hxx>
#define Handle_TCollection_DataMapNode Handle_MeshVS_DataMapNodeOfDataMapOfIntegerBoolean
#define TCollection_DataMapNode_Type_() MeshVS_DataMapNodeOfDataMapOfIntegerBoolean_Type_()
#define TCollection_DataMap MeshVS_DataMapOfIntegerBoolean
#define TCollection_DataMap_hxx <Visualization/MeshVS/MeshVS_DataMapOfIntegerBoolean.hxx>
#include <Foundation/TCollection/TCollection_DataMapIterator.gxx>

