// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _PCDM_DriverError_HeaderFile
#define _PCDM_DriverError_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <Foundation/Standard/Standard_DefineException.hxx>
#include <Foundation/Standard/Standard_SStream.hxx>
#include <Foundation/Standard/Standard_Failure.hxx>
#include <OCAF/PCDM/Handle_PCDM_DriverError.hxx>

#if !defined No_Exception && !defined No_PCDM_DriverError
  #define PCDM_DriverError_Raise_if(CONDITION, MESSAGE) \
  if (CONDITION) PCDM_DriverError::Raise(MESSAGE);
#else
  #define PCDM_DriverError_Raise_if(CONDITION, MESSAGE)
#endif

DEFINE_STANDARD_EXCEPTION(PCDM_DriverError, Standard_Failure)

#endif // _PCDM_DriverError_HeaderFile
