// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <DataExchange/STEPCAFControl/STEPCAFControl_DataMapOfLabelShape.hxx>

#include <Foundation/Standard/Standard_DomainError.hxx>
#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <OCAF/TDF/TDF_Label.hxx>
#include <ModelingData/TopoDS/TopoDS_Shape.hxx>
#include <OCAF/TDF/TDF_LabelMapHasher.hxx>
#include <DataExchange/STEPCAFControl/STEPCAFControl_DataMapNodeOfDataMapOfLabelShape.hxx>
#include <DataExchange/STEPCAFControl/STEPCAFControl_DataMapIteratorOfDataMapOfLabelShape.hxx>
 

#define TheKey TDF_Label
#define TheKey_hxx <OCAF/TDF/TDF_Label.hxx>
#define TheItem TopoDS_Shape
#define TheItem_hxx <ModelingData/TopoDS/TopoDS_Shape.hxx>
#define Hasher TDF_LabelMapHasher
#define Hasher_hxx <OCAF/TDF/TDF_LabelMapHasher.hxx>
#define TCollection_DataMapNode STEPCAFControl_DataMapNodeOfDataMapOfLabelShape
#define TCollection_DataMapNode_hxx <DataExchange/STEPCAFControl/STEPCAFControl_DataMapNodeOfDataMapOfLabelShape.hxx>
#define TCollection_DataMapIterator STEPCAFControl_DataMapIteratorOfDataMapOfLabelShape
#define TCollection_DataMapIterator_hxx <DataExchange/STEPCAFControl/STEPCAFControl_DataMapIteratorOfDataMapOfLabelShape.hxx>
#define Handle_TCollection_DataMapNode Handle_STEPCAFControl_DataMapNodeOfDataMapOfLabelShape
#define TCollection_DataMapNode_Type_() STEPCAFControl_DataMapNodeOfDataMapOfLabelShape_Type_()
#define TCollection_DataMap STEPCAFControl_DataMapOfLabelShape
#define TCollection_DataMap_hxx <DataExchange/STEPCAFControl/STEPCAFControl_DataMapOfLabelShape.hxx>
#include <Foundation/TCollection/TCollection_DataMap.gxx>

