// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <DataExchange/STEPCAFControl/STEPCAFControl_IteratorOfDictionaryOfExternFile.hxx>

#include <DataExchange/STEPCAFControl/STEPCAFControl_DictionaryOfExternFile.hxx>
#include <DataExchange/STEPCAFControl/STEPCAFControl_StackItemOfDictionaryOfExternFile.hxx>
#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <DataExchange/STEPCAFControl/STEPCAFControl_ExternFile.hxx>
#include <Foundation/TCollection/TCollection_AsciiString.hxx>
 

#define TheItem Handle(STEPCAFControl_ExternFile)
#define TheItem_hxx <DataExchange/STEPCAFControl/STEPCAFControl_ExternFile.hxx>
#define Dico_Iterator STEPCAFControl_IteratorOfDictionaryOfExternFile
#define Dico_Iterator_hxx <DataExchange/STEPCAFControl/STEPCAFControl_IteratorOfDictionaryOfExternFile.hxx>
#define Dico_StackItem STEPCAFControl_StackItemOfDictionaryOfExternFile
#define Dico_StackItem_hxx <DataExchange/STEPCAFControl/STEPCAFControl_StackItemOfDictionaryOfExternFile.hxx>
#define Handle_Dico_StackItem Handle_STEPCAFControl_StackItemOfDictionaryOfExternFile
#define Dico_StackItem_Type_() STEPCAFControl_StackItemOfDictionaryOfExternFile_Type_()
#define Dico_Dictionary STEPCAFControl_DictionaryOfExternFile
#define Dico_Dictionary_hxx <DataExchange/STEPCAFControl/STEPCAFControl_DictionaryOfExternFile.hxx>
#define Handle_Dico_Dictionary Handle_STEPCAFControl_DictionaryOfExternFile
#define Dico_Dictionary_Type_() STEPCAFControl_DictionaryOfExternFile_Type_()
#include <Foundation/Dico/Dico_Iterator.gxx>

