// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <TColQuantity_Array1OfLength.hxx>

#include <Foundation/Standard/Standard_RangeError.hxx>
#include <Foundation/Standard/Standard_DimensionMismatch.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_OutOfMemory.hxx>
 

#define Array1Item Quantity_Length
#define Array1Item_hxx <Foundation/Quantity/Quantity_Length.hxx>
#define TCollection_Array1 TColQuantity_Array1OfLength
#define TCollection_Array1_hxx <TColQuantity_Array1OfLength.hxx>
#include <Foundation/TCollection/TCollection_Array1.gxx>

