// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _RWStepShape_RWEdgeLoop_HeaderFile
#define _RWStepShape_RWEdgeLoop_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineAlloc.hxx>
#include <Foundation/Standard/Standard_Macro.hxx>

#include <DataExchange/StepData/Handle_StepData_StepReaderData.hxx>
#include <Foundation/Standard/Standard_Integer.hxx>
#include <DataExchange/Interface/Handle_Interface_Check.hxx>
#include <DataExchange/StepShape/Handle_StepShape_EdgeLoop.hxx>
class StepData_StepReaderData;
class Interface_Check;
class StepShape_EdgeLoop;
class StepData_StepWriter;
class Interface_EntityIterator;
class Interface_ShareTool;


//! Read & Write Module for EdgeLoop
//! Check added by CKY , 7-OCT-1996
class RWStepShape_RWEdgeLoop 
{
public:

  DEFINE_STANDARD_ALLOC

  
  Standard_EXPORT RWStepShape_RWEdgeLoop();
  
  Standard_EXPORT   void ReadStep (const Handle(StepData_StepReaderData)& data, const Standard_Integer num, Handle(Interface_Check)& ach, const Handle(StepShape_EdgeLoop)& ent)  const;
  
  Standard_EXPORT   void WriteStep (StepData_StepWriter& SW, const Handle(StepShape_EdgeLoop)& ent)  const;
  
  Standard_EXPORT   void Share (const Handle(StepShape_EdgeLoop)& ent, Interface_EntityIterator& iter)  const;
  
  Standard_EXPORT   void Check (const Handle(StepShape_EdgeLoop)& ent, const Interface_ShareTool& shares, Handle(Interface_Check)& ach)  const;




protected:





private:





};







#endif // _RWStepShape_RWEdgeLoop_HeaderFile
