// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _PDataStd_Tick_HeaderFile
#define _PDataStd_Tick_HeaderFile

#include <Foundation/Standard/Standard_Macro.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <Foundation/Standard/Standard.hxx>
#include <Handle_PDataStd_Tick.hxx>

#include <OCAF/PDF/PDF_Attribute.hxx>


class PDataStd_Tick : public PDF_Attribute
{

public:

  
  Standard_EXPORT PDataStd_Tick();

PDataStd_Tick(const Storage_stCONSTclCOM& a) : PDF_Attribute(a)
{
  
}



  DEFINE_STANDARD_RTTI(PDataStd_Tick)

protected:




private: 




};







#endif // _PDataStd_Tick_HeaderFile
