// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <DataExchange/StepBasic/StepBasic_HArray1OfDocument.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <Foundation/Standard/Standard_RangeError.hxx>
#include <Foundation/Standard/Standard_DimensionMismatch.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_OutOfMemory.hxx>
#include <DataExchange/StepBasic/StepBasic_Document.hxx>
#include <DataExchange/StepBasic/StepBasic_Array1OfDocument.hxx>

 


IMPLEMENT_STANDARD_TYPE(StepBasic_HArray1OfDocument)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(StepBasic_HArray1OfDocument)


IMPLEMENT_DOWNCAST(StepBasic_HArray1OfDocument,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(StepBasic_HArray1OfDocument)


#define ItemHArray1 Handle(StepBasic_Document)
#define ItemHArray1_hxx <DataExchange/StepBasic/StepBasic_Document.hxx>
#define TheArray1 StepBasic_Array1OfDocument
#define TheArray1_hxx <DataExchange/StepBasic/StepBasic_Array1OfDocument.hxx>
#define TCollection_HArray1 StepBasic_HArray1OfDocument
#define TCollection_HArray1_hxx <DataExchange/StepBasic/StepBasic_HArray1OfDocument.hxx>
#define Handle_TCollection_HArray1 Handle_StepBasic_HArray1OfDocument
#define TCollection_HArray1_Type_() StepBasic_HArray1OfDocument_Type_()
#include <Foundation/TCollection/TCollection_HArray1.gxx>

