// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ModelingAlgorithms/TopOpeBRepTool/TopOpeBRepTool_DataMapIteratorOfDataMapOfOrientedShapeC2DF.hxx>

#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <ModelingData/TopoDS/TopoDS_Shape.hxx>
#include <ModelingAlgorithms/TopOpeBRepTool/TopOpeBRepTool_C2DF.hxx>
#include <ModelingData/TopTools/TopTools_OrientedShapeMapHasher.hxx>
#include <ModelingAlgorithms/TopOpeBRepTool/TopOpeBRepTool_DataMapOfOrientedShapeC2DF.hxx>
#include <ModelingAlgorithms/TopOpeBRepTool/TopOpeBRepTool_DataMapNodeOfDataMapOfOrientedShapeC2DF.hxx>
 

#define TheKey TopoDS_Shape
#define TheKey_hxx <ModelingData/TopoDS/TopoDS_Shape.hxx>
#define TheItem TopOpeBRepTool_C2DF
#define TheItem_hxx <ModelingAlgorithms/TopOpeBRepTool/TopOpeBRepTool_C2DF.hxx>
#define Hasher TopTools_OrientedShapeMapHasher
#define Hasher_hxx <ModelingData/TopTools/TopTools_OrientedShapeMapHasher.hxx>
#define TCollection_DataMapNode TopOpeBRepTool_DataMapNodeOfDataMapOfOrientedShapeC2DF
#define TCollection_DataMapNode_hxx <ModelingAlgorithms/TopOpeBRepTool/TopOpeBRepTool_DataMapNodeOfDataMapOfOrientedShapeC2DF.hxx>
#define TCollection_DataMapIterator TopOpeBRepTool_DataMapIteratorOfDataMapOfOrientedShapeC2DF
#define TCollection_DataMapIterator_hxx <ModelingAlgorithms/TopOpeBRepTool/TopOpeBRepTool_DataMapIteratorOfDataMapOfOrientedShapeC2DF.hxx>
#define Handle_TCollection_DataMapNode Handle_TopOpeBRepTool_DataMapNodeOfDataMapOfOrientedShapeC2DF
#define TCollection_DataMapNode_Type_() TopOpeBRepTool_DataMapNodeOfDataMapOfOrientedShapeC2DF_Type_()
#define TCollection_DataMap TopOpeBRepTool_DataMapOfOrientedShapeC2DF
#define TCollection_DataMap_hxx <ModelingAlgorithms/TopOpeBRepTool/TopOpeBRepTool_DataMapOfOrientedShapeC2DF.hxx>
#include <Foundation/TCollection/TCollection_DataMapIterator.gxx>

