// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <TopoDS_Shape.hxx>
#include <TopOpeBRepDS_HDataStructure.hxx>
#include <TopTools_ListOfShape.hxx>
#include <TopOpeBRepBuild_HBuilder.hxx>
#include <BRepAlgo_DSAccess.hxx>
#include <BRepAlgo_BooleanOperations.hxx>

 


