// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Mathematics/BoundingVolumes/Bnd_B3f.hxx>

#include <Mathematics/Primitives/gp_XYZ.hxx>
#include <Mathematics/Primitives/gp_Pnt.hxx>
#include <Mathematics/Primitives/gp_Trsf.hxx>
#include <Mathematics/Primitives/gp_Ax1.hxx>
#include <Mathematics/Primitives/gp_Ax3.hxx>
 

#define RealType Standard_ShortReal
#define RealType_hxx <Foundation/Standard/Standard_ShortReal.hxx>
#define Bnd_B3x Bnd_B3f
#define Bnd_B3x_hxx <Mathematics/BoundingVolumes/Bnd_B3f.hxx>
#include <Mathematics/BoundingVolumes/Bnd_B3x.gxx>

