// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ModelingAlgorithms/BRepFill/BRepFill_DataMapOfOrientedShapeListOfShape.hxx>

#include <Foundation/Standard/Standard_DomainError.hxx>
#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <ModelingData/TopoDS/TopoDS_Shape.hxx>
#include <ModelingData/TopTools/TopTools_ListOfShape.hxx>
#include <ModelingData/TopTools/TopTools_OrientedShapeMapHasher.hxx>
#include <ModelingAlgorithms/BRepFill/BRepFill_DataMapNodeOfDataMapOfOrientedShapeListOfShape.hxx>
#include <ModelingAlgorithms/BRepFill/BRepFill_DataMapIteratorOfDataMapOfOrientedShapeListOfShape.hxx>
 

#define TheKey TopoDS_Shape
#define TheKey_hxx <ModelingData/TopoDS/TopoDS_Shape.hxx>
#define TheItem TopTools_ListOfShape
#define TheItem_hxx <ModelingData/TopTools/TopTools_ListOfShape.hxx>
#define Hasher TopTools_OrientedShapeMapHasher
#define Hasher_hxx <ModelingData/TopTools/TopTools_OrientedShapeMapHasher.hxx>
#define TCollection_DataMapNode BRepFill_DataMapNodeOfDataMapOfOrientedShapeListOfShape
#define TCollection_DataMapNode_hxx <ModelingAlgorithms/BRepFill/BRepFill_DataMapNodeOfDataMapOfOrientedShapeListOfShape.hxx>
#define TCollection_DataMapIterator BRepFill_DataMapIteratorOfDataMapOfOrientedShapeListOfShape
#define TCollection_DataMapIterator_hxx <ModelingAlgorithms/BRepFill/BRepFill_DataMapIteratorOfDataMapOfOrientedShapeListOfShape.hxx>
#define Handle_TCollection_DataMapNode Handle_BRepFill_DataMapNodeOfDataMapOfOrientedShapeListOfShape
#define TCollection_DataMapNode_Type_() BRepFill_DataMapNodeOfDataMapOfOrientedShapeListOfShape_Type_()
#define TCollection_DataMap BRepFill_DataMapOfOrientedShapeListOfShape
#define TCollection_DataMap_hxx <ModelingAlgorithms/BRepFill/BRepFill_DataMapOfOrientedShapeListOfShape.hxx>
#include <Foundation/TCollection/TCollection_DataMap.gxx>

