// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ModelingAlgorithms/BRepFill/BRepFill_IndexedDataMapOfOrientedShapeListOfShape.hxx>

#include <Foundation/Standard/Standard_DomainError.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <ModelingData/TopoDS/TopoDS_Shape.hxx>
#include <ModelingData/TopTools/TopTools_ListOfShape.hxx>
#include <ModelingData/TopTools/TopTools_OrientedShapeMapHasher.hxx>
#include <ModelingAlgorithms/BRepFill/BRepFill_IndexedDataMapNodeOfIndexedDataMapOfOrientedShapeListOfShape.hxx>
 

#define TheKey TopoDS_Shape
#define TheKey_hxx <ModelingData/TopoDS/TopoDS_Shape.hxx>
#define TheItem TopTools_ListOfShape
#define TheItem_hxx <ModelingData/TopTools/TopTools_ListOfShape.hxx>
#define Hasher TopTools_OrientedShapeMapHasher
#define Hasher_hxx <ModelingData/TopTools/TopTools_OrientedShapeMapHasher.hxx>
#define TCollection_IndexedDataMapNode BRepFill_IndexedDataMapNodeOfIndexedDataMapOfOrientedShapeListOfShape
#define TCollection_IndexedDataMapNode_hxx <ModelingAlgorithms/BRepFill/BRepFill_IndexedDataMapNodeOfIndexedDataMapOfOrientedShapeListOfShape.hxx>
#define Handle_TCollection_IndexedDataMapNode Handle_BRepFill_IndexedDataMapNodeOfIndexedDataMapOfOrientedShapeListOfShape
#define TCollection_IndexedDataMapNode_Type_() BRepFill_IndexedDataMapNodeOfIndexedDataMapOfOrientedShapeListOfShape_Type_()
#define TCollection_IndexedDataMap BRepFill_IndexedDataMapOfOrientedShapeListOfShape
#define TCollection_IndexedDataMap_hxx <ModelingAlgorithms/BRepFill/BRepFill_IndexedDataMapOfOrientedShapeListOfShape.hxx>
#include <Foundation/TCollection/TCollection_IndexedDataMap.gxx>

