// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <BRepFill_DataMapNodeOfDataMapOfShapeSequenceOfReal.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <ModelingData/TopoDS/TopoDS_Shape.hxx>
#include <Foundation/TColStd/TColStd_SequenceOfReal.hxx>
#include <ModelingData/TopTools/TopTools_ShapeMapHasher.hxx>
#include <BRepFill_DataMapOfShapeSequenceOfReal.hxx>
#include <BRepFill_DataMapIteratorOfDataMapOfShapeSequenceOfReal.hxx>

 


IMPLEMENT_STANDARD_TYPE(BRepFill_DataMapNodeOfDataMapOfShapeSequenceOfReal)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(BRepFill_DataMapNodeOfDataMapOfShapeSequenceOfReal)


IMPLEMENT_DOWNCAST(BRepFill_DataMapNodeOfDataMapOfShapeSequenceOfReal,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(BRepFill_DataMapNodeOfDataMapOfShapeSequenceOfReal)


#define TheKey TopoDS_Shape
#define TheKey_hxx <ModelingData/TopoDS/TopoDS_Shape.hxx>
#define TheItem TColStd_SequenceOfReal
#define TheItem_hxx <Foundation/TColStd/TColStd_SequenceOfReal.hxx>
#define Hasher TopTools_ShapeMapHasher
#define Hasher_hxx <ModelingData/TopTools/TopTools_ShapeMapHasher.hxx>
#define TCollection_DataMapNode BRepFill_DataMapNodeOfDataMapOfShapeSequenceOfReal
#define TCollection_DataMapNode_hxx <BRepFill_DataMapNodeOfDataMapOfShapeSequenceOfReal.hxx>
#define TCollection_DataMapIterator BRepFill_DataMapIteratorOfDataMapOfShapeSequenceOfReal
#define TCollection_DataMapIterator_hxx <BRepFill_DataMapIteratorOfDataMapOfShapeSequenceOfReal.hxx>
#define Handle_TCollection_DataMapNode Handle_BRepFill_DataMapNodeOfDataMapOfShapeSequenceOfReal
#define TCollection_DataMapNode_Type_() BRepFill_DataMapNodeOfDataMapOfShapeSequenceOfReal_Type_()
#define TCollection_DataMap BRepFill_DataMapOfShapeSequenceOfReal
#define TCollection_DataMap_hxx <BRepFill_DataMapOfShapeSequenceOfReal.hxx>
#include <Foundation/TCollection/TCollection_DataMapNode.gxx>

