// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <StepAP214_HArray1OfAutoDesignDatedItem.hxx>
#include <StepBasic_Date.hxx>
#include <StepBasic_DateRole.hxx>
#include <StepAP214_AutoDesignDatedItem.hxx>
#include <StepAP214_AutoDesignNominalDateAssignment.hxx>

#include <Standard_Type.hxx>


 


IMPLEMENT_STANDARD_TYPE(StepAP214_AutoDesignNominalDateAssignment)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(StepBasic_DateAssignment),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(StepAP214_AutoDesignNominalDateAssignment)


IMPLEMENT_DOWNCAST(StepAP214_AutoDesignNominalDateAssignment,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(StepAP214_AutoDesignNominalDateAssignment)



