// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ModelingAlgorithms/IntCurveSurface/IntCurveSurface_ThePolygonToolOfHInter.hxx>

#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Mathematics/Primitives/gp_Pnt.hxx>
#include <ModelingAlgorithms/IntCurveSurface/IntCurveSurface_ThePolygonOfHInter.hxx>
#include <Mathematics/BoundingVolumes/Bnd_Box.hxx>
 

#define ThePoint gp_Pnt
#define ThePoint_hxx <Mathematics/Primitives/gp_Pnt.hxx>
#define ThePolygon IntCurveSurface_ThePolygonOfHInter
#define ThePolygon_hxx <ModelingAlgorithms/IntCurveSurface/IntCurveSurface_ThePolygonOfHInter.hxx>
#define TheBoundingBox Bnd_Box
#define TheBoundingBox_hxx <Mathematics/BoundingVolumes/Bnd_Box.hxx>
#define IntCurveSurface_PolygonTool IntCurveSurface_ThePolygonToolOfHInter
#define IntCurveSurface_PolygonTool_hxx <ModelingAlgorithms/IntCurveSurface/IntCurveSurface_ThePolygonToolOfHInter.hxx>
#include <ModelingAlgorithms/IntCurveSurface/IntCurveSurface_PolygonTool.gxx>

