// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <GccEnt_BadQualifier.hxx>
#include <StdFail_NotDone.hxx>
#include <Geom2dGcc_IsParallel.hxx>
#include <Geom2dGcc_QCurve.hxx>
#include <gp_Lin2d.hxx>
#include <gp_Pnt2d.hxx>
#include <Geom2dGcc_Lin2dTanOblIter.hxx>

 


