// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ModelingAlgorithms/BRepClass/BRepClass_FacePassiveClassifier.hxx>

#include <Foundation/Standard/Standard_DomainError.hxx>
#include <ModelingAlgorithms/BRepClass/BRepClass_Edge.hxx>
#include <ModelingAlgorithms/BRepClass/BRepClass_Intersector.hxx>
#include <Mathematics/Primitives/gp_Lin2d.hxx>
 

#define TheEdge BRepClass_Edge
#define TheEdge_hxx <ModelingAlgorithms/BRepClass/BRepClass_Edge.hxx>
#define TheIntersector BRepClass_Intersector
#define TheIntersector_hxx <ModelingAlgorithms/BRepClass/BRepClass_Intersector.hxx>
#define TopClass_Classifier2d BRepClass_FacePassiveClassifier
#define TopClass_Classifier2d_hxx <ModelingAlgorithms/BRepClass/BRepClass_FacePassiveClassifier.hxx>
#include <ModelingAlgorithms/TopClass/TopClass_Classifier2d.gxx>

