// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <DataExchange/Transfer/Transfer_SequenceNodeOfSequenceOfFinder.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <DataExchange/Transfer/Transfer_Finder.hxx>
#include <DataExchange/Transfer/Transfer_SequenceOfFinder.hxx>

 


IMPLEMENT_STANDARD_TYPE(Transfer_SequenceNodeOfSequenceOfFinder)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(Transfer_SequenceNodeOfSequenceOfFinder)


IMPLEMENT_DOWNCAST(Transfer_SequenceNodeOfSequenceOfFinder,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(Transfer_SequenceNodeOfSequenceOfFinder)


#define SeqItem Handle(Transfer_Finder)
#define SeqItem_hxx <DataExchange/Transfer/Transfer_Finder.hxx>
#define TCollection_SequenceNode Transfer_SequenceNodeOfSequenceOfFinder
#define TCollection_SequenceNode_hxx <DataExchange/Transfer/Transfer_SequenceNodeOfSequenceOfFinder.hxx>
#define Handle_TCollection_SequenceNode Handle_Transfer_SequenceNodeOfSequenceOfFinder
#define TCollection_SequenceNode_Type_() Transfer_SequenceNodeOfSequenceOfFinder_Type_()
#define TCollection_Sequence Transfer_SequenceOfFinder
#define TCollection_Sequence_hxx <DataExchange/Transfer/Transfer_SequenceOfFinder.hxx>
#include <Foundation/TCollection/TCollection_SequenceNode.gxx>

