// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <DataExchange/Transfer/Transfer_ActorOfProcessForFinder.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <DataExchange/Transfer/Transfer_ActorOfProcessForFinder.hxx>
#include <Foundation/Standard/Standard_DomainError.hxx>
#include <DataExchange/Transfer/Transfer_Finder.hxx>
#include <DataExchange/Transfer/Transfer_FindHasher.hxx>
#include <DataExchange/Transfer/Transfer_HSequenceOfFinder.hxx>
#include <DataExchange/Transfer/Transfer_ProcessForFinder.hxx>
#include <DataExchange/Transfer/Transfer_TransferMapOfProcessForFinder.hxx>
#include <DataExchange/Transfer/Transfer_IndexedDataMapNodeOfTransferMapOfProcessForFinder.hxx>
#include <DataExchange/Transfer/Transfer_IteratorOfProcessForFinder.hxx>
#include <DataExchange/Transfer/Transfer_Binder.hxx>
#include <DataExchange/Transfer/Transfer_SimpleBinderOfTransient.hxx>
#include <Foundation/Standard/Standard_Transient.hxx>

 


IMPLEMENT_STANDARD_TYPE(Transfer_ActorOfProcessForFinder)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(Transfer_ActorOfProcessForFinder)


IMPLEMENT_DOWNCAST(Transfer_ActorOfProcessForFinder,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(Transfer_ActorOfProcessForFinder)


#define TheStart Handle(Transfer_Finder)
#define TheStart_hxx <DataExchange/Transfer/Transfer_Finder.hxx>
#define TheMapHasher Transfer_FindHasher
#define TheMapHasher_hxx <DataExchange/Transfer/Transfer_FindHasher.hxx>
#define Handle_TheList Handle_Transfer_HSequenceOfFinder
#define TheList Transfer_HSequenceOfFinder
#define TheList_hxx <DataExchange/Transfer/Transfer_HSequenceOfFinder.hxx>
#define Transfer_TransferMap Transfer_TransferMapOfProcessForFinder
#define Transfer_TransferMap_hxx <DataExchange/Transfer/Transfer_TransferMapOfProcessForFinder.hxx>
#define Transfer_IndexedDataMapNodeOfTransferMap Transfer_IndexedDataMapNodeOfTransferMapOfProcessForFinder
#define Transfer_IndexedDataMapNodeOfTransferMap_hxx <DataExchange/Transfer/Transfer_IndexedDataMapNodeOfTransferMapOfProcessForFinder.hxx>
#define Transfer_IndexedDataMapNodeOfTransferMap Transfer_IndexedDataMapNodeOfTransferMapOfProcessForFinder
#define Transfer_IndexedDataMapNodeOfTransferMap_hxx <DataExchange/Transfer/Transfer_IndexedDataMapNodeOfTransferMapOfProcessForFinder.hxx>
#define Transfer_Iterator Transfer_IteratorOfProcessForFinder
#define Transfer_Iterator_hxx <DataExchange/Transfer/Transfer_IteratorOfProcessForFinder.hxx>
#define Transfer_Actor Transfer_ActorOfProcessForFinder
#define Transfer_Actor_hxx <DataExchange/Transfer/Transfer_ActorOfProcessForFinder.hxx>
#define Handle_Transfer_IndexedDataMapNodeOfTransferMap Handle_Transfer_IndexedDataMapNodeOfTransferMapOfProcessForFinder
#define Transfer_IndexedDataMapNodeOfTransferMap_Type_() Transfer_IndexedDataMapNodeOfTransferMapOfProcessForFinder_Type_()
#define Handle_Transfer_IndexedDataMapNodeOfTransferMap Handle_Transfer_IndexedDataMapNodeOfTransferMapOfProcessForFinder
#define Transfer_IndexedDataMapNodeOfTransferMap_Type_() Transfer_IndexedDataMapNodeOfTransferMapOfProcessForFinder_Type_()
#define Handle_Transfer_Actor Handle_Transfer_ActorOfProcessForFinder
#define Transfer_Actor_Type_() Transfer_ActorOfProcessForFinder_Type_()
#define Transfer_TransferProcess Transfer_ProcessForFinder
#define Transfer_TransferProcess_hxx <DataExchange/Transfer/Transfer_ProcessForFinder.hxx>
#define Handle_Transfer_TransferProcess Handle_Transfer_ProcessForFinder
#define Transfer_TransferProcess_Type_() Transfer_ProcessForFinder_Type_()
#include <DataExchange/Transfer/Transfer_Actor.gxx>

