// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ModelingAlgorithms/IntSurf/IntSurf_ListOfPntOn2S.hxx>

#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <ModelingAlgorithms/IntSurf/IntSurf_ListIteratorOfListOfPntOn2S.hxx>
#include <ModelingAlgorithms/IntSurf/IntSurf_PntOn2S.hxx>
#include <ModelingAlgorithms/IntSurf/IntSurf_ListNodeOfListOfPntOn2S.hxx>
 

#define Item IntSurf_PntOn2S
#define Item_hxx <ModelingAlgorithms/IntSurf/IntSurf_PntOn2S.hxx>
#define TCollection_ListNode IntSurf_ListNodeOfListOfPntOn2S
#define TCollection_ListNode_hxx <ModelingAlgorithms/IntSurf/IntSurf_ListNodeOfListOfPntOn2S.hxx>
#define TCollection_ListIterator IntSurf_ListIteratorOfListOfPntOn2S
#define TCollection_ListIterator_hxx <ModelingAlgorithms/IntSurf/IntSurf_ListIteratorOfListOfPntOn2S.hxx>
#define Handle_TCollection_ListNode Handle_IntSurf_ListNodeOfListOfPntOn2S
#define TCollection_ListNode_Type_() IntSurf_ListNodeOfListOfPntOn2S_Type_()
#define TCollection_List IntSurf_ListOfPntOn2S
#define TCollection_List_hxx <ModelingAlgorithms/IntSurf/IntSurf_ListOfPntOn2S.hxx>
#include <Foundation/TCollection/TCollection_List.gxx>

