// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ModelingAlgorithms/IntRes2d/IntRes2d_SequenceOfIntersectionPoint.hxx>

#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <ModelingAlgorithms/IntRes2d/IntRes2d_IntersectionPoint.hxx>
#include <ModelingAlgorithms/IntRes2d/IntRes2d_SequenceNodeOfSequenceOfIntersectionPoint.hxx>
 

#define SeqItem IntRes2d_IntersectionPoint
#define SeqItem_hxx <ModelingAlgorithms/IntRes2d/IntRes2d_IntersectionPoint.hxx>
#define TCollection_SequenceNode IntRes2d_SequenceNodeOfSequenceOfIntersectionPoint
#define TCollection_SequenceNode_hxx <ModelingAlgorithms/IntRes2d/IntRes2d_SequenceNodeOfSequenceOfIntersectionPoint.hxx>
#define Handle_TCollection_SequenceNode Handle_IntRes2d_SequenceNodeOfSequenceOfIntersectionPoint
#define TCollection_SequenceNode_Type_() IntRes2d_SequenceNodeOfSequenceOfIntersectionPoint_Type_()
#define TCollection_Sequence IntRes2d_SequenceOfIntersectionPoint
#define TCollection_Sequence_hxx <ModelingAlgorithms/IntRes2d/IntRes2d_SequenceOfIntersectionPoint.hxx>
#include <Foundation/TCollection/TCollection_Sequence.gxx>

