// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <TopTools_DataMapNodeOfDataMapOfIntegerShape.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <ModelingData/TopoDS/TopoDS_Shape.hxx>
#include <Foundation/TColStd/TColStd_MapIntegerHasher.hxx>
#include <TopTools_DataMapOfIntegerShape.hxx>
#include <TopTools_DataMapIteratorOfDataMapOfIntegerShape.hxx>

 


IMPLEMENT_STANDARD_TYPE(TopTools_DataMapNodeOfDataMapOfIntegerShape)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(TopTools_DataMapNodeOfDataMapOfIntegerShape)


IMPLEMENT_DOWNCAST(TopTools_DataMapNodeOfDataMapOfIntegerShape,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(TopTools_DataMapNodeOfDataMapOfIntegerShape)


#define TheKey Standard_Integer
#define TheKey_hxx <Foundation/Standard/Standard_Integer.hxx>
#define TheItem TopoDS_Shape
#define TheItem_hxx <ModelingData/TopoDS/TopoDS_Shape.hxx>
#define Hasher TColStd_MapIntegerHasher
#define Hasher_hxx <Foundation/TColStd/TColStd_MapIntegerHasher.hxx>
#define TCollection_DataMapNode TopTools_DataMapNodeOfDataMapOfIntegerShape
#define TCollection_DataMapNode_hxx <TopTools_DataMapNodeOfDataMapOfIntegerShape.hxx>
#define TCollection_DataMapIterator TopTools_DataMapIteratorOfDataMapOfIntegerShape
#define TCollection_DataMapIterator_hxx <TopTools_DataMapIteratorOfDataMapOfIntegerShape.hxx>
#define Handle_TCollection_DataMapNode Handle_TopTools_DataMapNodeOfDataMapOfIntegerShape
#define TCollection_DataMapNode_Type_() TopTools_DataMapNodeOfDataMapOfIntegerShape_Type_()
#define TCollection_DataMap TopTools_DataMapOfIntegerShape
#define TCollection_DataMap_hxx <TopTools_DataMapOfIntegerShape.hxx>
#include <Foundation/TCollection/TCollection_DataMapNode.gxx>

