// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _MAT_TListNodeOfListOfBisector_HeaderFile
#define _MAT_TListNodeOfListOfBisector_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <ModelingAlgorithms/MAT/Handle_MAT_TListNodeOfListOfBisector.hxx>

#include <ModelingAlgorithms/MAT/Handle_MAT_TListNodeOfListOfBisector.hxx>
#include <ModelingAlgorithms/MAT/Handle_MAT_Bisector.hxx>
#include <Foundation/MMgt/MMgt_TShared.hxx>
#include <ModelingAlgorithms/MAT/Handle_MAT_ListOfBisector.hxx>
class MAT_Bisector;
class MAT_ListOfBisector;



class MAT_TListNodeOfListOfBisector : public MMgt_TShared
{

public:

  
    MAT_TListNodeOfListOfBisector();
  
    MAT_TListNodeOfListOfBisector(const Handle(MAT_Bisector)& anitem);
  
      Handle(MAT_Bisector) GetItem()  const;
  
      Handle(MAT_TListNodeOfListOfBisector) Next()  const;
  
      Handle(MAT_TListNodeOfListOfBisector) Previous()  const;
  
      void SetItem (const Handle(MAT_Bisector)& anitem) ;
  
      void Next (const Handle(MAT_TListNodeOfListOfBisector)& atlistnode) ;
  
      void Previous (const Handle(MAT_TListNodeOfListOfBisector)& atlistnode) ;
  
  Standard_EXPORT   void Dummy()  const;




  DEFINE_STANDARD_RTTI(MAT_TListNodeOfListOfBisector)

protected:




private: 


  Handle(MAT_TListNodeOfListOfBisector) thenext;
  Handle(MAT_TListNodeOfListOfBisector) theprevious;
  Handle(MAT_Bisector) theitem;


};

#define Item Handle(MAT_Bisector)
#define Item_hxx <ModelingAlgorithms/MAT/MAT_Bisector.hxx>
#define MAT_TListNode MAT_TListNodeOfListOfBisector
#define MAT_TListNode_hxx <ModelingAlgorithms/MAT/MAT_TListNodeOfListOfBisector.hxx>
#define Handle_MAT_TListNode Handle_MAT_TListNodeOfListOfBisector
#define MAT_TListNode_Type_() MAT_TListNodeOfListOfBisector_Type_()
#define MAT_TList MAT_ListOfBisector
#define MAT_TList_hxx <ModelingAlgorithms/MAT/MAT_ListOfBisector.hxx>
#define Handle_MAT_TList Handle_MAT_ListOfBisector
#define MAT_TList_Type_() MAT_ListOfBisector_Type_()

#include <ModelingAlgorithms/MAT/MAT_TListNode.lxx>

#undef Item
#undef Item_hxx
#undef MAT_TListNode
#undef MAT_TListNode_hxx
#undef Handle_MAT_TListNode
#undef MAT_TListNode_Type_
#undef MAT_TList
#undef MAT_TList_hxx
#undef Handle_MAT_TList
#undef MAT_TList_Type_




#endif // _MAT_TListNodeOfListOfBisector_HeaderFile
