// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ModelingData/BRepAdaptor/BRepAdaptor_Array1OfCurve.hxx>

#include <Foundation/Standard/Standard_RangeError.hxx>
#include <Foundation/Standard/Standard_DimensionMismatch.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_OutOfMemory.hxx>
#include <ModelingData/BRepAdaptor/BRepAdaptor_Curve.hxx>
 

#define Array1Item BRepAdaptor_Curve
#define Array1Item_hxx <ModelingData/BRepAdaptor/BRepAdaptor_Curve.hxx>
#define TCollection_Array1 BRepAdaptor_Array1OfCurve
#define TCollection_Array1_hxx <ModelingData/BRepAdaptor/BRepAdaptor_Array1OfCurve.hxx>
#include <Foundation/TCollection/TCollection_Array1.gxx>

