// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ModelingAlgorithms/ChFiDS/ChFiDS_ListOfStripe.hxx>

#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <ModelingAlgorithms/ChFiDS/ChFiDS_ListIteratorOfListOfStripe.hxx>
#include <ModelingAlgorithms/ChFiDS/ChFiDS_Stripe.hxx>
#include <ModelingAlgorithms/ChFiDS/ChFiDS_ListNodeOfListOfStripe.hxx>
 

#define Item Handle(ChFiDS_Stripe)
#define Item_hxx <ModelingAlgorithms/ChFiDS/ChFiDS_Stripe.hxx>
#define TCollection_ListNode ChFiDS_ListNodeOfListOfStripe
#define TCollection_ListNode_hxx <ModelingAlgorithms/ChFiDS/ChFiDS_ListNodeOfListOfStripe.hxx>
#define TCollection_ListIterator ChFiDS_ListIteratorOfListOfStripe
#define TCollection_ListIterator_hxx <ModelingAlgorithms/ChFiDS/ChFiDS_ListIteratorOfListOfStripe.hxx>
#define Handle_TCollection_ListNode Handle_ChFiDS_ListNodeOfListOfStripe
#define TCollection_ListNode_Type_() ChFiDS_ListNodeOfListOfStripe_Type_()
#define TCollection_List ChFiDS_ListOfStripe
#define TCollection_List_hxx <ModelingAlgorithms/ChFiDS/ChFiDS_ListOfStripe.hxx>
#include <Foundation/TCollection/TCollection_List.gxx>

