// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Foundation/SortTools/SortTools_StraightInsertionSortOfReal.hxx>

#include <Foundation/TColStd/TColStd_Array1OfReal.hxx>
#include <Foundation/TCollection/TCollection_CompareOfReal.hxx>
 

#define Item Standard_Real
#define Item_hxx <Foundation/Standard/Standard_Real.hxx>
#define Array TColStd_Array1OfReal
#define Array_hxx <Foundation/TColStd/TColStd_Array1OfReal.hxx>
#define Comparator TCollection_CompareOfReal
#define Comparator_hxx <Foundation/TCollection/TCollection_CompareOfReal.hxx>
#define SortTools_StraightInsertionSort SortTools_StraightInsertionSortOfReal
#define SortTools_StraightInsertionSort_hxx <Foundation/SortTools/SortTools_StraightInsertionSortOfReal.hxx>
#include <Foundation/SortTools/SortTools_StraightInsertionSort.gxx>

