// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <DataExchange/StepVisual/StepVisual_Array1OfInvisibleItem.hxx>

#include <Foundation/Standard/Standard_RangeError.hxx>
#include <Foundation/Standard/Standard_DimensionMismatch.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_OutOfMemory.hxx>
#include <DataExchange/StepVisual/StepVisual_InvisibleItem.hxx>
 

#define Array1Item StepVisual_InvisibleItem
#define Array1Item_hxx <DataExchange/StepVisual/StepVisual_InvisibleItem.hxx>
#define TCollection_Array1 StepVisual_Array1OfInvisibleItem
#define TCollection_Array1_hxx <DataExchange/StepVisual/StepVisual_Array1OfInvisibleItem.hxx>
#include <Foundation/TCollection/TCollection_Array1.gxx>

