// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ModelingAlgorithms/LocOpe/LocOpe_DataMapNodeOfDataMapOfShapePnt.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <ModelingData/TopoDS/TopoDS_Shape.hxx>
#include <Mathematics/Primitives/gp_Pnt.hxx>
#include <ModelingData/TopTools/TopTools_ShapeMapHasher.hxx>
#include <ModelingAlgorithms/LocOpe/LocOpe_DataMapOfShapePnt.hxx>
#include <ModelingAlgorithms/LocOpe/LocOpe_DataMapIteratorOfDataMapOfShapePnt.hxx>

 


IMPLEMENT_STANDARD_TYPE(LocOpe_DataMapNodeOfDataMapOfShapePnt)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(LocOpe_DataMapNodeOfDataMapOfShapePnt)


IMPLEMENT_DOWNCAST(LocOpe_DataMapNodeOfDataMapOfShapePnt,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(LocOpe_DataMapNodeOfDataMapOfShapePnt)


#define TheKey TopoDS_Shape
#define TheKey_hxx <ModelingData/TopoDS/TopoDS_Shape.hxx>
#define TheItem gp_Pnt
#define TheItem_hxx <Mathematics/Primitives/gp_Pnt.hxx>
#define Hasher TopTools_ShapeMapHasher
#define Hasher_hxx <ModelingData/TopTools/TopTools_ShapeMapHasher.hxx>
#define TCollection_DataMapNode LocOpe_DataMapNodeOfDataMapOfShapePnt
#define TCollection_DataMapNode_hxx <ModelingAlgorithms/LocOpe/LocOpe_DataMapNodeOfDataMapOfShapePnt.hxx>
#define TCollection_DataMapIterator LocOpe_DataMapIteratorOfDataMapOfShapePnt
#define TCollection_DataMapIterator_hxx <ModelingAlgorithms/LocOpe/LocOpe_DataMapIteratorOfDataMapOfShapePnt.hxx>
#define Handle_TCollection_DataMapNode Handle_LocOpe_DataMapNodeOfDataMapOfShapePnt
#define TCollection_DataMapNode_Type_() LocOpe_DataMapNodeOfDataMapOfShapePnt_Type_()
#define TCollection_DataMap LocOpe_DataMapOfShapePnt
#define TCollection_DataMap_hxx <ModelingAlgorithms/LocOpe/LocOpe_DataMapOfShapePnt.hxx>
#include <Foundation/TCollection/TCollection_DataMapNode.gxx>

