// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_MDF_ARDriverHSequence_HeaderFile
#define _Handle_MDF_ARDriverHSequence_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <Foundation/MMgt/Handle_MMgt_TShared.hxx>

class Standard_Transient;
class Handle(Standard_Type);
class Handle(MMgt_TShared);
class MDF_ARDriverHSequence;

DEFINE_STANDARD_HANDLE(MDF_ARDriverHSequence, MMgt_TShared)

#endif // _Handle_MDF_ARDriverHSequence_HeaderFile
