// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ModelingAlgorithms/HLRBRep/HLRBRep_ListIteratorOfListOfBPnt2D.hxx>

#include <Foundation/Standard/Standard_NoMoreObject.hxx>
#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <ModelingAlgorithms/HLRBRep/HLRBRep_ListOfBPnt2D.hxx>
#include <ModelingAlgorithms/HLRBRep/HLRBRep_BiPnt2D.hxx>
#include <ModelingAlgorithms/HLRBRep/HLRBRep_ListNodeOfListOfBPnt2D.hxx>
 

#define Item HLRBRep_BiPnt2D
#define Item_hxx <ModelingAlgorithms/HLRBRep/HLRBRep_BiPnt2D.hxx>
#define TCollection_ListNode HLRBRep_ListNodeOfListOfBPnt2D
#define TCollection_ListNode_hxx <ModelingAlgorithms/HLRBRep/HLRBRep_ListNodeOfListOfBPnt2D.hxx>
#define TCollection_ListIterator HLRBRep_ListIteratorOfListOfBPnt2D
#define TCollection_ListIterator_hxx <ModelingAlgorithms/HLRBRep/HLRBRep_ListIteratorOfListOfBPnt2D.hxx>
#define Handle_TCollection_ListNode Handle_HLRBRep_ListNodeOfListOfBPnt2D
#define TCollection_ListNode_Type_() HLRBRep_ListNodeOfListOfBPnt2D_Type_()
#define TCollection_List HLRBRep_ListOfBPnt2D
#define TCollection_List_hxx <ModelingAlgorithms/HLRBRep/HLRBRep_ListOfBPnt2D.hxx>
#include <Foundation/TCollection/TCollection_ListIterator.gxx>

