// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ModelingAlgorithms/HLRBRep/HLRBRep_MyImpParToolOfTheIntersectorOfTheIntConicCurveOfCInter.hxx>

#include <ModelingAlgorithms/IntCurve/IntCurve_IConicTool.hxx>
#include <ModelingAlgorithms/HLRBRep/HLRBRep_CurveTool.hxx>
 

#define ImpTool IntCurve_IConicTool
#define ImpTool_hxx <ModelingAlgorithms/IntCurve/IntCurve_IConicTool.hxx>
#define ParCurve Standard_Address
#define ParCurve_hxx <Foundation/Standard/Standard_Address.hxx>
#define ParTool HLRBRep_CurveTool
#define ParTool_hxx <ModelingAlgorithms/HLRBRep/HLRBRep_CurveTool.hxx>
#define IntImpParGen_ImpParTool HLRBRep_MyImpParToolOfTheIntersectorOfTheIntConicCurveOfCInter
#define IntImpParGen_ImpParTool_hxx <ModelingAlgorithms/HLRBRep/HLRBRep_MyImpParToolOfTheIntersectorOfTheIntConicCurveOfCInter.hxx>
#include <ModelingAlgorithms/IntImpParGen/IntImpParGen_ImpParTool.gxx>

