// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ModelingAlgorithms/IntTools/IntTools_ListIteratorOfListOfBox.hxx>

#include <Foundation/Standard/Standard_NoMoreObject.hxx>
#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <ModelingAlgorithms/IntTools/IntTools_ListOfBox.hxx>
#include <Mathematics/BoundingVolumes/Bnd_Box.hxx>
#include <ModelingAlgorithms/IntTools/IntTools_ListNodeOfListOfBox.hxx>
 

#define Item Bnd_Box
#define Item_hxx <Mathematics/BoundingVolumes/Bnd_Box.hxx>
#define TCollection_ListNode IntTools_ListNodeOfListOfBox
#define TCollection_ListNode_hxx <ModelingAlgorithms/IntTools/IntTools_ListNodeOfListOfBox.hxx>
#define TCollection_ListIterator IntTools_ListIteratorOfListOfBox
#define TCollection_ListIterator_hxx <ModelingAlgorithms/IntTools/IntTools_ListIteratorOfListOfBox.hxx>
#define Handle_TCollection_ListNode Handle_IntTools_ListNodeOfListOfBox
#define TCollection_ListNode_Type_() IntTools_ListNodeOfListOfBox_Type_()
#define TCollection_List IntTools_ListOfBox
#define TCollection_List_hxx <ModelingAlgorithms/IntTools/IntTools_ListOfBox.hxx>
#include <Foundation/TCollection/TCollection_ListIterator.gxx>

