// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ModelingAlgorithms/IntTools/IntTools_SequenceNodeOfSequenceOfRoots.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <ModelingAlgorithms/IntTools/IntTools_Root.hxx>
#include <ModelingAlgorithms/IntTools/IntTools_SequenceOfRoots.hxx>

 


IMPLEMENT_STANDARD_TYPE(IntTools_SequenceNodeOfSequenceOfRoots)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(IntTools_SequenceNodeOfSequenceOfRoots)


IMPLEMENT_DOWNCAST(IntTools_SequenceNodeOfSequenceOfRoots,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(IntTools_SequenceNodeOfSequenceOfRoots)


#define SeqItem IntTools_Root
#define SeqItem_hxx <ModelingAlgorithms/IntTools/IntTools_Root.hxx>
#define TCollection_SequenceNode IntTools_SequenceNodeOfSequenceOfRoots
#define TCollection_SequenceNode_hxx <ModelingAlgorithms/IntTools/IntTools_SequenceNodeOfSequenceOfRoots.hxx>
#define Handle_TCollection_SequenceNode Handle_IntTools_SequenceNodeOfSequenceOfRoots
#define TCollection_SequenceNode_Type_() IntTools_SequenceNodeOfSequenceOfRoots_Type_()
#define TCollection_Sequence IntTools_SequenceOfRoots
#define TCollection_Sequence_hxx <ModelingAlgorithms/IntTools/IntTools_SequenceOfRoots.hxx>
#include <Foundation/TCollection/TCollection_SequenceNode.gxx>

