// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _AdvApprox_PrefCutting_HeaderFile
#define _AdvApprox_PrefCutting_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineAlloc.hxx>
#include <Foundation/Standard/Standard_Macro.hxx>

#include <Foundation/TColStd/TColStd_Array1OfReal.hxx>
#include <Geometry/AdvApprox/AdvApprox_Cutting.hxx>
#include <Foundation/Standard/Standard_Boolean.hxx>
#include <Foundation/Standard/Standard_Real.hxx>
class TColStd_Array1OfReal;



//! inherits class Cutting; contains a list of preferential points (di)i
//! if Cutting is necessary in [a,b], we cut at the di nearest from (a+b)/2.
class AdvApprox_PrefCutting  : public AdvApprox_Cutting
{
public:

  DEFINE_STANDARD_ALLOC

  
  Standard_EXPORT AdvApprox_PrefCutting(const TColStd_Array1OfReal& CutPnts);
  
  Standard_EXPORT virtual   Standard_Boolean Value (const Standard_Real a, const Standard_Real b, Standard_Real& cuttingvalue)  const;




protected:





private:



  TColStd_Array1OfReal myPntOfCutting;


};







#endif // _AdvApprox_PrefCutting_HeaderFile
