// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_PTopoDS_TWire_HeaderFile
#define _Handle_PTopoDS_TWire_HeaderFile

#include <Foundation/Standard/Standard_Macro.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <Foundation/Standard/Standard.hxx>
#include <Handle_PTopoDS_TShape.hxx>

class Standard_Persistent;
class Handle(Standard_Type);
class Handle(PTopoDS_TShape);
class PTopoDS_TWire;

DEFINE_STANDARD_PHANDLE(PTopoDS_TWire,PTopoDS_TShape)

#endif
