// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_StepRepr_AssemblyComponentUsage_HeaderFile
#define _Handle_StepRepr_AssemblyComponentUsage_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <Handle_StepRepr_ProductDefinitionUsage.hxx>

class Standard_Transient;
class Handle(Standard_Type);
class Handle(StepRepr_ProductDefinitionUsage);
class StepRepr_AssemblyComponentUsage;

DEFINE_STANDARD_HANDLE(StepRepr_AssemblyComponentUsage, StepRepr_ProductDefinitionUsage)

#endif // _Handle_StepRepr_AssemblyComponentUsage_HeaderFile
