// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_PCDM_Document_HeaderFile
#define _Handle_PCDM_Document_HeaderFile

#include <Foundation/Standard/Standard_Macro.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <Foundation/Standard/Standard.hxx>
#include <Handle_Standard_Persistent.hxx>

class Standard_Persistent;
class Handle(Standard_Type);
class Handle(Standard_Persistent);
class PCDM_Document;

DEFINE_STANDARD_PHANDLE(PCDM_Document,Standard_Persistent)

#endif
