// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _PTopoDS_TWire1_HeaderFile
#define _PTopoDS_TWire1_HeaderFile

#include <Foundation/Standard/Standard_Macro.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <Foundation/Standard/Standard.hxx>
#include <Handle_PTopoDS_TWire1.hxx>

#include <ModelingData/TopAbs/TopAbs_ShapeEnum.hxx>
#include <PTopoDS_TShape1.hxx>


class PTopoDS_TWire1 : public PTopoDS_TShape1
{

public:

  
  Standard_EXPORT PTopoDS_TWire1();
  
  Standard_EXPORT   TopAbs_ShapeEnum ShapeType()  const;

PTopoDS_TWire1(const Storage_stCONSTclCOM& a) : PTopoDS_TShape1(a)
{
  
}



  DEFINE_STANDARD_RTTI(PTopoDS_TWire1)

protected:




private: 




};







#endif // _PTopoDS_TWire1_HeaderFile
