// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <DataExchange/StepAP203/StepAP203_HArray1OfStartRequestItem.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <Foundation/Standard/Standard_RangeError.hxx>
#include <Foundation/Standard/Standard_DimensionMismatch.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_OutOfMemory.hxx>
#include <DataExchange/StepAP203/StepAP203_StartRequestItem.hxx>
#include <DataExchange/StepAP203/StepAP203_Array1OfStartRequestItem.hxx>

 


IMPLEMENT_STANDARD_TYPE(StepAP203_HArray1OfStartRequestItem)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(StepAP203_HArray1OfStartRequestItem)


IMPLEMENT_DOWNCAST(StepAP203_HArray1OfStartRequestItem,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(StepAP203_HArray1OfStartRequestItem)


#define ItemHArray1 StepAP203_StartRequestItem
#define ItemHArray1_hxx <DataExchange/StepAP203/StepAP203_StartRequestItem.hxx>
#define TheArray1 StepAP203_Array1OfStartRequestItem
#define TheArray1_hxx <DataExchange/StepAP203/StepAP203_Array1OfStartRequestItem.hxx>
#define TCollection_HArray1 StepAP203_HArray1OfStartRequestItem
#define TCollection_HArray1_hxx <DataExchange/StepAP203/StepAP203_HArray1OfStartRequestItem.hxx>
#define Handle_TCollection_HArray1 Handle_StepAP203_HArray1OfStartRequestItem
#define TCollection_HArray1_Type_() StepAP203_HArray1OfStartRequestItem_Type_()
#include <Foundation/TCollection/TCollection_HArray1.gxx>

