// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <DataExchange/StepAP203/StepAP203_Array1OfWorkItem.hxx>

#include <Foundation/Standard/Standard_RangeError.hxx>
#include <Foundation/Standard/Standard_DimensionMismatch.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_OutOfMemory.hxx>
#include <DataExchange/StepAP203/StepAP203_WorkItem.hxx>
 

#define Array1Item StepAP203_WorkItem
#define Array1Item_hxx <DataExchange/StepAP203/StepAP203_WorkItem.hxx>
#define TCollection_Array1 StepAP203_Array1OfWorkItem
#define TCollection_Array1_hxx <DataExchange/StepAP203/StepAP203_Array1OfWorkItem.hxx>
#include <Foundation/TCollection/TCollection_Array1.gxx>

