// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <OCAF/PPoly/PPoly_VArrayTNodeOfFieldOfHArray1OfTriangle.hxx>

#include <OCAF/PPoly/PPoly_Triangle.hxx>
#include <OCAF/PPoly/PPoly_FieldOfHArray1OfTriangle.hxx>
#include <OCAF/PPoly/PPoly_VArrayNodeOfFieldOfHArray1OfTriangle.hxx>
 

#define Item PPoly_Triangle
#define Item_hxx <OCAF/PPoly/PPoly_Triangle.hxx>
#define DBC_VArrayNode PPoly_VArrayNodeOfFieldOfHArray1OfTriangle
#define DBC_VArrayNode_hxx <OCAF/PPoly/PPoly_VArrayNodeOfFieldOfHArray1OfTriangle.hxx>
#define DBC_VArrayTNode PPoly_VArrayTNodeOfFieldOfHArray1OfTriangle
#define DBC_VArrayTNode_hxx <OCAF/PPoly/PPoly_VArrayTNodeOfFieldOfHArray1OfTriangle.hxx>
#define Handle_DBC_VArrayNode Handle_PPoly_VArrayNodeOfFieldOfHArray1OfTriangle
#define DBC_VArrayNode_Type_() PPoly_VArrayNodeOfFieldOfHArray1OfTriangle_Type_()
#define DBC_VArray PPoly_FieldOfHArray1OfTriangle
#define DBC_VArray_hxx <OCAF/PPoly/PPoly_FieldOfHArray1OfTriangle.hxx>
#include <OCAF/DBC/DBC_VArrayTNode.gxx>

