// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <DataExchange/STEPSelections/STEPSelections_SequenceNodeOfSequenceOfAssemblyComponent.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <DataExchange/STEPSelections/STEPSelections_AssemblyComponent.hxx>
#include <DataExchange/STEPSelections/STEPSelections_SequenceOfAssemblyComponent.hxx>

 


IMPLEMENT_STANDARD_TYPE(STEPSelections_SequenceNodeOfSequenceOfAssemblyComponent)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(STEPSelections_SequenceNodeOfSequenceOfAssemblyComponent)


IMPLEMENT_DOWNCAST(STEPSelections_SequenceNodeOfSequenceOfAssemblyComponent,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(STEPSelections_SequenceNodeOfSequenceOfAssemblyComponent)


#define SeqItem Handle(STEPSelections_AssemblyComponent)
#define SeqItem_hxx <DataExchange/STEPSelections/STEPSelections_AssemblyComponent.hxx>
#define TCollection_SequenceNode STEPSelections_SequenceNodeOfSequenceOfAssemblyComponent
#define TCollection_SequenceNode_hxx <DataExchange/STEPSelections/STEPSelections_SequenceNodeOfSequenceOfAssemblyComponent.hxx>
#define Handle_TCollection_SequenceNode Handle_STEPSelections_SequenceNodeOfSequenceOfAssemblyComponent
#define TCollection_SequenceNode_Type_() STEPSelections_SequenceNodeOfSequenceOfAssemblyComponent_Type_()
#define TCollection_Sequence STEPSelections_SequenceOfAssemblyComponent
#define TCollection_Sequence_hxx <DataExchange/STEPSelections/STEPSelections_SequenceOfAssemblyComponent.hxx>
#include <Foundation/TCollection/TCollection_SequenceNode.gxx>

