// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <OCAF/TDF/TDF_LabelDataMap.hxx>

#include <Foundation/Standard/Standard_DomainError.hxx>
#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <OCAF/TDF/TDF_Label.hxx>
#include <OCAF/TDF/TDF_LabelMapHasher.hxx>
#include <OCAF/TDF/TDF_DataMapNodeOfLabelDataMap.hxx>
#include <OCAF/TDF/TDF_DataMapIteratorOfLabelDataMap.hxx>
 

#define TheKey TDF_Label
#define TheKey_hxx <OCAF/TDF/TDF_Label.hxx>
#define TheItem TDF_Label
#define TheItem_hxx <OCAF/TDF/TDF_Label.hxx>
#define Hasher TDF_LabelMapHasher
#define Hasher_hxx <OCAF/TDF/TDF_LabelMapHasher.hxx>
#define TCollection_DataMapNode TDF_DataMapNodeOfLabelDataMap
#define TCollection_DataMapNode_hxx <OCAF/TDF/TDF_DataMapNodeOfLabelDataMap.hxx>
#define TCollection_DataMapIterator TDF_DataMapIteratorOfLabelDataMap
#define TCollection_DataMapIterator_hxx <OCAF/TDF/TDF_DataMapIteratorOfLabelDataMap.hxx>
#define Handle_TCollection_DataMapNode Handle_TDF_DataMapNodeOfLabelDataMap
#define TCollection_DataMapNode_Type_() TDF_DataMapNodeOfLabelDataMap_Type_()
#define TCollection_DataMap TDF_LabelDataMap
#define TCollection_DataMap_hxx <OCAF/TDF/TDF_LabelDataMap.hxx>
#include <Foundation/TCollection/TCollection_DataMap.gxx>

