// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <OCAF/TDF/TDF_ListIteratorOfLabelList.hxx>

#include <Foundation/Standard/Standard_NoMoreObject.hxx>
#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <OCAF/TDF/TDF_LabelList.hxx>
#include <OCAF/TDF/TDF_Label.hxx>
#include <OCAF/TDF/TDF_ListNodeOfLabelList.hxx>
 

#define Item TDF_Label
#define Item_hxx <OCAF/TDF/TDF_Label.hxx>
#define TCollection_ListNode TDF_ListNodeOfLabelList
#define TCollection_ListNode_hxx <OCAF/TDF/TDF_ListNodeOfLabelList.hxx>
#define TCollection_ListIterator TDF_ListIteratorOfLabelList
#define TCollection_ListIterator_hxx <OCAF/TDF/TDF_ListIteratorOfLabelList.hxx>
#define Handle_TCollection_ListNode Handle_TDF_ListNodeOfLabelList
#define TCollection_ListNode_Type_() TDF_ListNodeOfLabelList_Type_()
#define TCollection_List TDF_LabelList
#define TCollection_List_hxx <OCAF/TDF/TDF_LabelList.hxx>
#include <Foundation/TCollection/TCollection_ListIterator.gxx>

