// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_Geom2d_Conic_HeaderFile
#define _Handle_Geom2d_Conic_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <Geometry/Geom2d/Handle_Geom2d_Curve.hxx>

class Standard_Transient;
class Handle(Standard_Type);
class Handle(Geom2d_Curve);
class Geom2d_Conic;

DEFINE_STANDARD_HANDLE(Geom2d_Conic, Geom2d_Curve)

#endif // _Handle_Geom2d_Conic_HeaderFile
