// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Foundation/TColStd/TColStd_SequenceOfAsciiString.hxx>

#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/TCollection/TCollection_AsciiString.hxx>
#include <Foundation/TColStd/TColStd_SequenceNodeOfSequenceOfAsciiString.hxx>
 

#define SeqItem TCollection_AsciiString
#define SeqItem_hxx <Foundation/TCollection/TCollection_AsciiString.hxx>
#define TCollection_SequenceNode TColStd_SequenceNodeOfSequenceOfAsciiString
#define TCollection_SequenceNode_hxx <Foundation/TColStd/TColStd_SequenceNodeOfSequenceOfAsciiString.hxx>
#define Handle_TCollection_SequenceNode Handle_TColStd_SequenceNodeOfSequenceOfAsciiString
#define TCollection_SequenceNode_Type_() TColStd_SequenceNodeOfSequenceOfAsciiString_Type_()
#define TCollection_Sequence TColStd_SequenceOfAsciiString
#define TCollection_Sequence_hxx <Foundation/TColStd/TColStd_SequenceOfAsciiString.hxx>
#include <Foundation/TCollection/TCollection_Sequence.gxx>

