// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Foundation/TColStd/TColStd_Array1OfExtendedString.hxx>

#include <Foundation/Standard/Standard_RangeError.hxx>
#include <Foundation/Standard/Standard_DimensionMismatch.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_OutOfMemory.hxx>
#include <Foundation/TCollection/TCollection_ExtendedString.hxx>
 

#define Array1Item TCollection_ExtendedString
#define Array1Item_hxx <Foundation/TCollection/TCollection_ExtendedString.hxx>
#define TCollection_Array1 TColStd_Array1OfExtendedString
#define TCollection_Array1_hxx <Foundation/TColStd/TColStd_Array1OfExtendedString.hxx>
#include <Foundation/TCollection/TCollection_Array1.gxx>

