// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <TColStd_Array2OfTransient.hxx>

#include <Foundation/Standard/Standard_RangeError.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_OutOfMemory.hxx>
#include <Foundation/Standard/Standard_DimensionMismatch.hxx>
#include <Foundation/Standard/Standard_Transient.hxx>
 

#define Array2Item Handle(Standard_Transient)
#define Array2Item_hxx <Foundation/Standard/Standard_Transient.hxx>
#define TCollection_Array2 TColStd_Array2OfTransient
#define TCollection_Array2_hxx <TColStd_Array2OfTransient.hxx>
#include <Foundation/TCollection/TCollection_Array2.gxx>

