// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Foundation/TColStd/TColStd_HArray1OfBoolean.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <Foundation/Standard/Standard_RangeError.hxx>
#include <Foundation/Standard/Standard_DimensionMismatch.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_OutOfMemory.hxx>
#include <Foundation/TColStd/TColStd_Array1OfBoolean.hxx>

 


IMPLEMENT_STANDARD_TYPE(TColStd_HArray1OfBoolean)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(TColStd_HArray1OfBoolean)


IMPLEMENT_DOWNCAST(TColStd_HArray1OfBoolean,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(TColStd_HArray1OfBoolean)


#define ItemHArray1 Standard_Boolean
#define ItemHArray1_hxx <Foundation/Standard/Standard_Boolean.hxx>
#define TheArray1 TColStd_Array1OfBoolean
#define TheArray1_hxx <Foundation/TColStd/TColStd_Array1OfBoolean.hxx>
#define TCollection_HArray1 TColStd_HArray1OfBoolean
#define TCollection_HArray1_hxx <Foundation/TColStd/TColStd_HArray1OfBoolean.hxx>
#define Handle_TCollection_HArray1 Handle_TColStd_HArray1OfBoolean
#define TCollection_HArray1_Type_() TColStd_HArray1OfBoolean_Type_()
#include <Foundation/TCollection/TCollection_HArray1.gxx>

