// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Foundation/TColStd/TColStd_SequenceOfReal.hxx>

#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/TColStd/TColStd_SequenceNodeOfSequenceOfReal.hxx>
 

#define SeqItem Standard_Real
#define SeqItem_hxx <Foundation/Standard/Standard_Real.hxx>
#define TCollection_SequenceNode TColStd_SequenceNodeOfSequenceOfReal
#define TCollection_SequenceNode_hxx <Foundation/TColStd/TColStd_SequenceNodeOfSequenceOfReal.hxx>
#define Handle_TCollection_SequenceNode Handle_TColStd_SequenceNodeOfSequenceOfReal
#define TCollection_SequenceNode_Type_() TColStd_SequenceNodeOfSequenceOfReal_Type_()
#define TCollection_Sequence TColStd_SequenceOfReal
#define TCollection_Sequence_hxx <Foundation/TColStd/TColStd_SequenceOfReal.hxx>
#include <Foundation/TCollection/TCollection_Sequence.gxx>

