// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Foundation/TColStd/TColStd_MapOfReal.hxx>

#include <Foundation/TColStd/TColStd_MapRealHasher.hxx>
#include <Foundation/TColStd/TColStd_StdMapNodeOfMapOfReal.hxx>
#include <Foundation/TColStd/TColStd_MapIteratorOfMapOfReal.hxx>
 

#define TheKey Standard_Real
#define TheKey_hxx <Foundation/Standard/Standard_Real.hxx>
#define Hasher TColStd_MapRealHasher
#define Hasher_hxx <Foundation/TColStd/TColStd_MapRealHasher.hxx>
#define TCollection_StdMapNode TColStd_StdMapNodeOfMapOfReal
#define TCollection_StdMapNode_hxx <Foundation/TColStd/TColStd_StdMapNodeOfMapOfReal.hxx>
#define TCollection_MapIterator TColStd_MapIteratorOfMapOfReal
#define TCollection_MapIterator_hxx <Foundation/TColStd/TColStd_MapIteratorOfMapOfReal.hxx>
#define Handle_TCollection_StdMapNode Handle_TColStd_StdMapNodeOfMapOfReal
#define TCollection_StdMapNode_Type_() TColStd_StdMapNodeOfMapOfReal_Type_()
#define TCollection_Map TColStd_MapOfReal
#define TCollection_Map_hxx <Foundation/TColStd/TColStd_MapOfReal.hxx>
#include <Foundation/TCollection/TCollection_Map.gxx>

