// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Geometry/AppDef/AppDef_MyGradientbisOfBSplineCompute.hxx>

#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/StdFail/StdFail_NotDone.hxx>
#include <Geometry/AppDef/AppDef_MultiLine.hxx>
#include <Geometry/AppDef/AppDef_MyLineTool.hxx>
#include <Geometry/AppDef/AppDef_ParLeastSquareOfMyGradientbisOfBSplineCompute.hxx>
#include <Geometry/AppDef/AppDef_ResConstraintOfMyGradientbisOfBSplineCompute.hxx>
#include <Geometry/AppDef/AppDef_ParFunctionOfMyGradientbisOfBSplineCompute.hxx>
#include <Geometry/AppDef/AppDef_Gradient_BFGSOfMyGradientbisOfBSplineCompute.hxx>
#include <Geometry/AppParCurves/AppParCurves_HArray1OfConstraintCouple.hxx>
#include <Geometry/AppParCurves/AppParCurves_MultiCurve.hxx>
 

#define MultiLine AppDef_MultiLine
#define MultiLine_hxx <Geometry/AppDef/AppDef_MultiLine.hxx>
#define ToolLine AppDef_MyLineTool
#define ToolLine_hxx <Geometry/AppDef/AppDef_MyLineTool.hxx>
#define AppParCurves_ParLeastSquare AppDef_ParLeastSquareOfMyGradientbisOfBSplineCompute
#define AppParCurves_ParLeastSquare_hxx <Geometry/AppDef/AppDef_ParLeastSquareOfMyGradientbisOfBSplineCompute.hxx>
#define AppParCurves_ResConstraint AppDef_ResConstraintOfMyGradientbisOfBSplineCompute
#define AppParCurves_ResConstraint_hxx <Geometry/AppDef/AppDef_ResConstraintOfMyGradientbisOfBSplineCompute.hxx>
#define AppParCurves_ParFunction AppDef_ParFunctionOfMyGradientbisOfBSplineCompute
#define AppParCurves_ParFunction_hxx <Geometry/AppDef/AppDef_ParFunctionOfMyGradientbisOfBSplineCompute.hxx>
#define AppParCurves_Gradient_BFGS AppDef_Gradient_BFGSOfMyGradientbisOfBSplineCompute
#define AppParCurves_Gradient_BFGS_hxx <Geometry/AppDef/AppDef_Gradient_BFGSOfMyGradientbisOfBSplineCompute.hxx>
#define AppParCurves_Gradient AppDef_MyGradientbisOfBSplineCompute
#define AppParCurves_Gradient_hxx <Geometry/AppDef/AppDef_MyGradientbisOfBSplineCompute.hxx>
#include <Geometry/AppParCurves/AppParCurves_Gradient.gxx>

