// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_MXCAFDoc_DimTolToolRetrievalDriver_HeaderFile
#define _Handle_MXCAFDoc_DimTolToolRetrievalDriver_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <OCAF/MDF/Handle_MDF_ARDriver.hxx>

class Standard_Transient;
class Handle(Standard_Type);
class Handle(MDF_ARDriver);
class MXCAFDoc_DimTolToolRetrievalDriver;

DEFINE_STANDARD_HANDLE(MXCAFDoc_DimTolToolRetrievalDriver, MDF_ARDriver)

#endif // _Handle_MXCAFDoc_DimTolToolRetrievalDriver_HeaderFile
