// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _SelectBasics_ListIteratorOfListOfBox2d_HeaderFile
#define _SelectBasics_ListIteratorOfListOfBox2d_HeaderFile

#include <Visualization/SelectBasics/SelectBasics_ListOfBox2d.hxx>

typedef SelectBasics_ListOfBox2d::iterator SelectBasics_ListIteratorOfListOfBox2d;

#endif // _SelectBasics_ListIteratorOfListOfBox2d_HeaderFile
