// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _SelectBasics_ListOfBox2d_HeaderFile
#define _SelectBasics_ListOfBox2d_HeaderFile

#include <vector>

#include <Mathematics/BoundingVolumes/Bnd_Box2d.hxx>

typedef std::vector<Bnd_Box2d> SelectBasics_ListOfBox2d;

#endif // _SelectBasics_ListOfBox2d_HeaderFile
