// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Visualization/Visual3d/Visual3d_SequenceOfLight.hxx>

#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Visualization/Visual3d/Visual3d_Light.hxx>
#include <Visualization/Visual3d/Visual3d_SequenceNodeOfSequenceOfLight.hxx>
 

#define SeqItem Handle(Visual3d_Light)
#define SeqItem_hxx <Visualization/Visual3d/Visual3d_Light.hxx>
#define TCollection_SequenceNode Visual3d_SequenceNodeOfSequenceOfLight
#define TCollection_SequenceNode_hxx <Visualization/Visual3d/Visual3d_SequenceNodeOfSequenceOfLight.hxx>
#define Handle_TCollection_SequenceNode Handle_Visual3d_SequenceNodeOfSequenceOfLight
#define TCollection_SequenceNode_Type_() Visual3d_SequenceNodeOfSequenceOfLight_Type_()
#define TCollection_Sequence Visual3d_SequenceOfLight
#define TCollection_Sequence_hxx <Visualization/Visual3d/Visual3d_SequenceOfLight.hxx>
#include <Foundation/TCollection/TCollection_Sequence.gxx>

