// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Visualization/Visual3d/Visual3d_SequenceNodeOfSequenceOfLight.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <Visualization/Visual3d/Visual3d_Light.hxx>
#include <Visualization/Visual3d/Visual3d_SequenceOfLight.hxx>

 


IMPLEMENT_STANDARD_TYPE(Visual3d_SequenceNodeOfSequenceOfLight)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(Visual3d_SequenceNodeOfSequenceOfLight)


IMPLEMENT_DOWNCAST(Visual3d_SequenceNodeOfSequenceOfLight,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(Visual3d_SequenceNodeOfSequenceOfLight)


#define SeqItem Handle(Visual3d_Light)
#define SeqItem_hxx <Visualization/Visual3d/Visual3d_Light.hxx>
#define TCollection_SequenceNode Visual3d_SequenceNodeOfSequenceOfLight
#define TCollection_SequenceNode_hxx <Visualization/Visual3d/Visual3d_SequenceNodeOfSequenceOfLight.hxx>
#define Handle_TCollection_SequenceNode Handle_Visual3d_SequenceNodeOfSequenceOfLight
#define TCollection_SequenceNode_Type_() Visual3d_SequenceNodeOfSequenceOfLight_Type_()
#define TCollection_Sequence Visual3d_SequenceOfLight
#define TCollection_Sequence_hxx <Visualization/Visual3d/Visual3d_SequenceOfLight.hxx>
#include <Foundation/TCollection/TCollection_SequenceNode.gxx>

