// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <OCAF/MDF/MDF_ASDriverSequence.hxx>

#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <OCAF/MDF/MDF_ASDriver.hxx>
#include <OCAF/MDF/MDF_SequenceNodeOfASDriverSequence.hxx>
 

#define SeqItem Handle(MDF_ASDriver)
#define SeqItem_hxx <OCAF/MDF/MDF_ASDriver.hxx>
#define TCollection_SequenceNode MDF_SequenceNodeOfASDriverSequence
#define TCollection_SequenceNode_hxx <OCAF/MDF/MDF_SequenceNodeOfASDriverSequence.hxx>
#define Handle_TCollection_SequenceNode Handle_MDF_SequenceNodeOfASDriverSequence
#define TCollection_SequenceNode_Type_() MDF_SequenceNodeOfASDriverSequence_Type_()
#define TCollection_Sequence MDF_ASDriverSequence
#define TCollection_Sequence_hxx <OCAF/MDF/MDF_ASDriverSequence.hxx>
#include <Foundation/TCollection/TCollection_Sequence.gxx>

