// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <OCAF/MDF/MDF_DataMapNodeOfTypeDriverListMapOfARDriverTable.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <Foundation/Standard/Standard_Type.hxx>
#include <OCAF/MDF/MDF_DriverListOfARDriverTable.hxx>
#include <Foundation/TColStd/TColStd_MapTransientHasher.hxx>
#include <OCAF/MDF/MDF_TypeDriverListMapOfARDriverTable.hxx>
#include <OCAF/MDF/MDF_DataMapIteratorOfTypeDriverListMapOfARDriverTable.hxx>

 


IMPLEMENT_STANDARD_TYPE(MDF_DataMapNodeOfTypeDriverListMapOfARDriverTable)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(MDF_DataMapNodeOfTypeDriverListMapOfARDriverTable)


IMPLEMENT_DOWNCAST(MDF_DataMapNodeOfTypeDriverListMapOfARDriverTable,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(MDF_DataMapNodeOfTypeDriverListMapOfARDriverTable)


#define TheKey Handle(Standard_Type)
#define TheKey_hxx <Foundation/Standard/Standard_Type.hxx>
#define TheItem MDF_DriverListOfARDriverTable
#define TheItem_hxx <OCAF/MDF/MDF_DriverListOfARDriverTable.hxx>
#define Hasher TColStd_MapTransientHasher
#define Hasher_hxx <Foundation/TColStd/TColStd_MapTransientHasher.hxx>
#define TCollection_DataMapNode MDF_DataMapNodeOfTypeDriverListMapOfARDriverTable
#define TCollection_DataMapNode_hxx <OCAF/MDF/MDF_DataMapNodeOfTypeDriverListMapOfARDriverTable.hxx>
#define TCollection_DataMapIterator MDF_DataMapIteratorOfTypeDriverListMapOfARDriverTable
#define TCollection_DataMapIterator_hxx <OCAF/MDF/MDF_DataMapIteratorOfTypeDriverListMapOfARDriverTable.hxx>
#define Handle_TCollection_DataMapNode Handle_MDF_DataMapNodeOfTypeDriverListMapOfARDriverTable
#define TCollection_DataMapNode_Type_() MDF_DataMapNodeOfTypeDriverListMapOfARDriverTable_Type_()
#define TCollection_DataMap MDF_TypeDriverListMapOfARDriverTable
#define TCollection_DataMap_hxx <OCAF/MDF/MDF_TypeDriverListMapOfARDriverTable.hxx>
#include <Foundation/TCollection/TCollection_DataMapNode.gxx>

