// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <MDF_TypeARDriverMap.hxx>

#include <Foundation/Standard/Standard_DomainError.hxx>
#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <Foundation/Standard/Standard_Type.hxx>
#include <MDF_ARDriver.hxx>
#include <Foundation/TColStd/TColStd_MapTransientHasher.hxx>
#include <MDF_DataMapNodeOfTypeARDriverMap.hxx>
#include <MDF_DataMapIteratorOfTypeARDriverMap.hxx>
 

#define TheKey Handle(Standard_Type)
#define TheKey_hxx <Foundation/Standard/Standard_Type.hxx>
#define TheItem Handle(MDF_ARDriver)
#define TheItem_hxx <MDF_ARDriver.hxx>
#define Hasher TColStd_MapTransientHasher
#define Hasher_hxx <Foundation/TColStd/TColStd_MapTransientHasher.hxx>
#define TCollection_DataMapNode MDF_DataMapNodeOfTypeARDriverMap
#define TCollection_DataMapNode_hxx <MDF_DataMapNodeOfTypeARDriverMap.hxx>
#define TCollection_DataMapIterator MDF_DataMapIteratorOfTypeARDriverMap
#define TCollection_DataMapIterator_hxx <MDF_DataMapIteratorOfTypeARDriverMap.hxx>
#define Handle_TCollection_DataMapNode Handle_MDF_DataMapNodeOfTypeARDriverMap
#define TCollection_DataMapNode_Type_() MDF_DataMapNodeOfTypeARDriverMap_Type_()
#define TCollection_DataMap MDF_TypeARDriverMap
#define TCollection_DataMap_hxx <MDF_TypeARDriverMap.hxx>
#include <Foundation/TCollection/TCollection_DataMap.gxx>

