// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <DataExchange/StepToTopoDS/StepToTopoDS_DataMapNodeOfDataMapOfRINames.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <Foundation/TCollection/TCollection_AsciiString.hxx>
#include <ModelingData/TopoDS/TopoDS_Shape.hxx>
#include <DataExchange/StepToTopoDS/StepToTopoDS_DataMapOfRINames.hxx>
#include <DataExchange/StepToTopoDS/StepToTopoDS_DataMapIteratorOfDataMapOfRINames.hxx>

 


IMPLEMENT_STANDARD_TYPE(StepToTopoDS_DataMapNodeOfDataMapOfRINames)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(StepToTopoDS_DataMapNodeOfDataMapOfRINames)


IMPLEMENT_DOWNCAST(StepToTopoDS_DataMapNodeOfDataMapOfRINames,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(StepToTopoDS_DataMapNodeOfDataMapOfRINames)


#define TheKey TCollection_AsciiString
#define TheKey_hxx <Foundation/TCollection/TCollection_AsciiString.hxx>
#define TheItem TopoDS_Shape
#define TheItem_hxx <ModelingData/TopoDS/TopoDS_Shape.hxx>
#define Hasher TCollection_AsciiString
#define Hasher_hxx <Foundation/TCollection/TCollection_AsciiString.hxx>
#define TCollection_DataMapNode StepToTopoDS_DataMapNodeOfDataMapOfRINames
#define TCollection_DataMapNode_hxx <DataExchange/StepToTopoDS/StepToTopoDS_DataMapNodeOfDataMapOfRINames.hxx>
#define TCollection_DataMapIterator StepToTopoDS_DataMapIteratorOfDataMapOfRINames
#define TCollection_DataMapIterator_hxx <DataExchange/StepToTopoDS/StepToTopoDS_DataMapIteratorOfDataMapOfRINames.hxx>
#define Handle_TCollection_DataMapNode Handle_StepToTopoDS_DataMapNodeOfDataMapOfRINames
#define TCollection_DataMapNode_Type_() StepToTopoDS_DataMapNodeOfDataMapOfRINames_Type_()
#define TCollection_DataMap StepToTopoDS_DataMapOfRINames
#define TCollection_DataMap_hxx <DataExchange/StepToTopoDS/StepToTopoDS_DataMapOfRINames.hxx>
#include <Foundation/TCollection/TCollection_DataMapNode.gxx>

