// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Draft_DataMapIteratorOfDataMapOfFaceFaceInfo.hxx>

#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <ModelingData/TopoDS/TopoDS_Face.hxx>
#include <Draft_FaceInfo.hxx>
#include <ModelingData/TopTools/TopTools_ShapeMapHasher.hxx>
#include <Draft_DataMapOfFaceFaceInfo.hxx>
#include <Draft_DataMapNodeOfDataMapOfFaceFaceInfo.hxx>
 

#define TheKey TopoDS_Face
#define TheKey_hxx <ModelingData/TopoDS/TopoDS_Face.hxx>
#define TheItem Draft_FaceInfo
#define TheItem_hxx <Draft_FaceInfo.hxx>
#define Hasher TopTools_ShapeMapHasher
#define Hasher_hxx <ModelingData/TopTools/TopTools_ShapeMapHasher.hxx>
#define TCollection_DataMapNode Draft_DataMapNodeOfDataMapOfFaceFaceInfo
#define TCollection_DataMapNode_hxx <Draft_DataMapNodeOfDataMapOfFaceFaceInfo.hxx>
#define TCollection_DataMapIterator Draft_DataMapIteratorOfDataMapOfFaceFaceInfo
#define TCollection_DataMapIterator_hxx <Draft_DataMapIteratorOfDataMapOfFaceFaceInfo.hxx>
#define Handle_TCollection_DataMapNode Handle_Draft_DataMapNodeOfDataMapOfFaceFaceInfo
#define TCollection_DataMapNode_Type_() Draft_DataMapNodeOfDataMapOfFaceFaceInfo_Type_()
#define TCollection_DataMap Draft_DataMapOfFaceFaceInfo
#define TCollection_DataMap_hxx <Draft_DataMapOfFaceFaceInfo.hxx>
#include <Foundation/TCollection/TCollection_DataMapIterator.gxx>

