// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <OCAF/TDataStd/TDataStd_DataMapOfStringReal.hxx>

#include <Foundation/Standard/Standard_DomainError.hxx>
#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <Foundation/TCollection/TCollection_ExtendedString.hxx>
#include <OCAF/TDataStd/TDataStd_DataMapNodeOfDataMapOfStringReal.hxx>
#include <OCAF/TDataStd/TDataStd_DataMapIteratorOfDataMapOfStringReal.hxx>
 

#define TheKey TCollection_ExtendedString
#define TheKey_hxx <Foundation/TCollection/TCollection_ExtendedString.hxx>
#define TheItem Standard_Real
#define TheItem_hxx <Foundation/Standard/Standard_Real.hxx>
#define Hasher TCollection_ExtendedString
#define Hasher_hxx <Foundation/TCollection/TCollection_ExtendedString.hxx>
#define TCollection_DataMapNode TDataStd_DataMapNodeOfDataMapOfStringReal
#define TCollection_DataMapNode_hxx <OCAF/TDataStd/TDataStd_DataMapNodeOfDataMapOfStringReal.hxx>
#define TCollection_DataMapIterator TDataStd_DataMapIteratorOfDataMapOfStringReal
#define TCollection_DataMapIterator_hxx <OCAF/TDataStd/TDataStd_DataMapIteratorOfDataMapOfStringReal.hxx>
#define Handle_TCollection_DataMapNode Handle_TDataStd_DataMapNodeOfDataMapOfStringReal
#define TCollection_DataMapNode_Type_() TDataStd_DataMapNodeOfDataMapOfStringReal_Type_()
#define TCollection_DataMap TDataStd_DataMapOfStringReal
#define TCollection_DataMap_hxx <OCAF/TDataStd/TDataStd_DataMapOfStringReal.hxx>
#include <Foundation/TCollection/TCollection_DataMap.gxx>

