// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _DBRep_ListNodeOfListOfHideData_HeaderFile
#define _DBRep_ListNodeOfListOfHideData_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <Viewer/DBRep/Handle_DBRep_ListNodeOfListOfHideData.hxx>

#include <Viewer/DBRep/DBRep_HideData.hxx>
#include <Foundation/TCollection/TCollection_MapNode.hxx>
#include <Foundation/TCollection/TCollection_MapNodePtr.hxx>
class DBRep_HideData;
class DBRep_ListOfHideData;
class DBRep_ListIteratorOfListOfHideData;



class DBRep_ListNodeOfListOfHideData : public TCollection_MapNode
{

public:

  
    DBRep_ListNodeOfListOfHideData(const DBRep_HideData& I, const TCollection_MapNodePtr& n);
  
      DBRep_HideData& Value()  const;




  DEFINE_STANDARD_RTTI(DBRep_ListNodeOfListOfHideData)

protected:




private: 


  DBRep_HideData myValue;


};

#define Item DBRep_HideData
#define Item_hxx <Viewer/DBRep/DBRep_HideData.hxx>
#define TCollection_ListNode DBRep_ListNodeOfListOfHideData
#define TCollection_ListNode_hxx <Viewer/DBRep/DBRep_ListNodeOfListOfHideData.hxx>
#define TCollection_ListIterator DBRep_ListIteratorOfListOfHideData
#define TCollection_ListIterator_hxx <Viewer/DBRep/DBRep_ListIteratorOfListOfHideData.hxx>
#define Handle_TCollection_ListNode Handle_DBRep_ListNodeOfListOfHideData
#define TCollection_ListNode_Type_() DBRep_ListNodeOfListOfHideData_Type_()
#define TCollection_List DBRep_ListOfHideData
#define TCollection_List_hxx <Viewer/DBRep/DBRep_ListOfHideData.hxx>

#include <Foundation/TCollection/TCollection_ListNode.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_ListNode
#undef TCollection_ListNode_hxx
#undef TCollection_ListIterator
#undef TCollection_ListIterator_hxx
#undef Handle_TCollection_ListNode
#undef TCollection_ListNode_Type_
#undef TCollection_List
#undef TCollection_List_hxx




#endif // _DBRep_ListNodeOfListOfHideData_HeaderFile
