// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_Adaptor3d_HSurfaceOfRevolution_HeaderFile
#define _Handle_Adaptor3d_HSurfaceOfRevolution_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <Geometry/Adaptor3d/Handle_Adaptor3d_HSurface.hxx>

class Standard_Transient;
class Handle(Standard_Type);
class Handle(Adaptor3d_HSurface);
class Adaptor3d_HSurfaceOfRevolution;

DEFINE_STANDARD_HANDLE(Adaptor3d_HSurfaceOfRevolution, Adaptor3d_HSurface)

#endif // _Handle_Adaptor3d_HSurfaceOfRevolution_HeaderFile
