// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Geometry/AppParCurves/AppParCurves_Array1OfMultiBSpCurve.hxx>

#include <Foundation/Standard/Standard_RangeError.hxx>
#include <Foundation/Standard/Standard_DimensionMismatch.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_OutOfMemory.hxx>
#include <Geometry/AppParCurves/AppParCurves_MultiBSpCurve.hxx>
 

#define Array1Item AppParCurves_MultiBSpCurve
#define Array1Item_hxx <Geometry/AppParCurves/AppParCurves_MultiBSpCurve.hxx>
#define TCollection_Array1 AppParCurves_Array1OfMultiBSpCurve
#define TCollection_Array1_hxx <Geometry/AppParCurves/AppParCurves_Array1OfMultiBSpCurve.hxx>
#include <Foundation/TCollection/TCollection_Array1.gxx>

