// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <gp_Lin.hxx>
#include <TopoDS_Face.hxx>
#include <IntCurveSurface_IntersectionPoint.hxx>
#include <TopClass_Intersection3d.hxx>

 


