// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <OCAF/PColgp/PColgp_VArrayNodeOfFieldOfHArray1OfVec.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <Mathematics/Primitives/gp_Vec.hxx>
#include <OCAF/PColgp/PColgp_FieldOfHArray1OfVec.hxx>
#include <OCAF/PColgp/PColgp_VArrayTNodeOfFieldOfHArray1OfVec.hxx>

 


IMPLEMENT_STANDARD_TYPE(PColgp_VArrayNodeOfFieldOfHArray1OfVec)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(PStandard_ArrayNode),
  STANDARD_TYPE(Standard_Persistent),
  STANDARD_TYPE(Standard_Storable),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(PColgp_VArrayNodeOfFieldOfHArray1OfVec)


IMPLEMENT_DOWNCAST(PColgp_VArrayNodeOfFieldOfHArray1OfVec,Standard_Persistent)
IMPLEMENT_STANDARD_RTTI(PColgp_VArrayNodeOfFieldOfHArray1OfVec)


#define Item gp_Vec
#define Item_hxx <Mathematics/Primitives/gp_Vec.hxx>
#define DBC_VArrayNode PColgp_VArrayNodeOfFieldOfHArray1OfVec
#define DBC_VArrayNode_hxx <OCAF/PColgp/PColgp_VArrayNodeOfFieldOfHArray1OfVec.hxx>
#define DBC_VArrayTNode PColgp_VArrayTNodeOfFieldOfHArray1OfVec
#define DBC_VArrayTNode_hxx <OCAF/PColgp/PColgp_VArrayTNodeOfFieldOfHArray1OfVec.hxx>
#define Handle_DBC_VArrayNode Handle_PColgp_VArrayNodeOfFieldOfHArray1OfVec
#define DBC_VArrayNode_Type_() PColgp_VArrayNodeOfFieldOfHArray1OfVec_Type_()
#define DBC_VArray PColgp_FieldOfHArray1OfVec
#define DBC_VArray_hxx <OCAF/PColgp/PColgp_FieldOfHArray1OfVec.hxx>
#include <OCAF/DBC/DBC_VArrayNode.gxx>

