// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <OCAF/PColgp/PColgp_VArrayNodeOfFieldOfHArray2OfCirc2d.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <Mathematics/Primitives/gp_Circ2d.hxx>
#include <OCAF/PColgp/PColgp_FieldOfHArray2OfCirc2d.hxx>
#include <OCAF/PColgp/PColgp_VArrayTNodeOfFieldOfHArray2OfCirc2d.hxx>

 


IMPLEMENT_STANDARD_TYPE(PColgp_VArrayNodeOfFieldOfHArray2OfCirc2d)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(PStandard_ArrayNode),
  STANDARD_TYPE(Standard_Persistent),
  STANDARD_TYPE(Standard_Storable),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(PColgp_VArrayNodeOfFieldOfHArray2OfCirc2d)


IMPLEMENT_DOWNCAST(PColgp_VArrayNodeOfFieldOfHArray2OfCirc2d,Standard_Persistent)
IMPLEMENT_STANDARD_RTTI(PColgp_VArrayNodeOfFieldOfHArray2OfCirc2d)


#define Item gp_Circ2d
#define Item_hxx <Mathematics/Primitives/gp_Circ2d.hxx>
#define DBC_VArrayNode PColgp_VArrayNodeOfFieldOfHArray2OfCirc2d
#define DBC_VArrayNode_hxx <OCAF/PColgp/PColgp_VArrayNodeOfFieldOfHArray2OfCirc2d.hxx>
#define DBC_VArrayTNode PColgp_VArrayTNodeOfFieldOfHArray2OfCirc2d
#define DBC_VArrayTNode_hxx <OCAF/PColgp/PColgp_VArrayTNodeOfFieldOfHArray2OfCirc2d.hxx>
#define Handle_DBC_VArrayNode Handle_PColgp_VArrayNodeOfFieldOfHArray2OfCirc2d
#define DBC_VArrayNode_Type_() PColgp_VArrayNodeOfFieldOfHArray2OfCirc2d_Type_()
#define DBC_VArray PColgp_FieldOfHArray2OfCirc2d
#define DBC_VArray_hxx <OCAF/PColgp/PColgp_FieldOfHArray2OfCirc2d.hxx>
#include <OCAF/DBC/DBC_VArrayNode.gxx>

