// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _BRepCheck_Vertex_HeaderFile
#define _BRepCheck_Vertex_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <Handle_BRepCheck_Vertex.hxx>

#include <ModelingAlgorithms/BRepCheck/BRepCheck_Result.hxx>
#include <Foundation/Standard/Standard_Real.hxx>
class TopoDS_Vertex;
class TopoDS_Shape;



class BRepCheck_Vertex : public BRepCheck_Result
{

public:

  
  Standard_EXPORT BRepCheck_Vertex(const TopoDS_Vertex& V);
  
  Standard_EXPORT   void InContext (const TopoDS_Shape& ContextShape) ;
  
  Standard_EXPORT   void Minimum() ;
  
  Standard_EXPORT   void Blind() ;
  
  Standard_EXPORT   Standard_Real Tolerance() ;




  DEFINE_STANDARD_RTTI(BRepCheck_Vertex)

protected:




private: 




};







#endif // _BRepCheck_Vertex_HeaderFile
