// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_PColgp_HArray1OfPnt_HeaderFile
#define _Handle_PColgp_HArray1OfPnt_HeaderFile

#include <Foundation/Standard/Standard_Macro.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Handle_Standard_Persistent.hxx>

class Standard_Persistent;
class Handle(Standard_Type);
class Handle(Standard_Persistent);
class PColgp_HArray1OfPnt;

DEFINE_STANDARD_PHANDLE(PColgp_HArray1OfPnt,Standard_Persistent)

#endif
