// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_AppDef_LinearCriteria_HeaderFile
#define _Handle_AppDef_LinearCriteria_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <Geometry/AppDef/Handle_AppDef_SmoothCriterion.hxx>

class Standard_Transient;
class Handle(Standard_Type);
class Handle(AppDef_SmoothCriterion);
class AppDef_LinearCriteria;

DEFINE_STANDARD_HANDLE(AppDef_LinearCriteria, AppDef_SmoothCriterion)

#endif // _Handle_AppDef_LinearCriteria_HeaderFile
