// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _PDataXtd_Shape_HeaderFile
#define _PDataXtd_Shape_HeaderFile

#include <Foundation/Standard/Standard_Macro.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <Foundation/Standard/Standard.hxx>
#include <Handle_PDataXtd_Shape.hxx>

#include <OCAF/PDF/PDF_Attribute.hxx>


class PDataXtd_Shape : public PDF_Attribute
{

public:

  
  Standard_EXPORT PDataXtd_Shape();

PDataXtd_Shape(const Storage_stCONSTclCOM& a) : PDF_Attribute(a)
{
  
}



  DEFINE_STANDARD_RTTI(PDataXtd_Shape)

protected:




private: 




};







#endif // _PDataXtd_Shape_HeaderFile
