// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Geometry/Extrema/Extrema_PCFOfEPCOfELPCOfLocateExtPC2d.hxx>

#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_TypeMismatch.hxx>
#include <Geometry/Adaptor2d/Adaptor2d_Curve2d.hxx>
#include <Geometry/Extrema/Extrema_Curve2dTool.hxx>
#include <Geometry/Extrema/Extrema_POnCurv2d.hxx>
#include <Mathematics/Primitives/gp_Pnt2d.hxx>
#include <Mathematics/Primitives/gp_Vec2d.hxx>
#include <Geometry/Extrema/Extrema_SeqPCOfPCFOfEPCOfELPCOfLocateExtPC2d.hxx>
#include <Geometry/Extrema/Extrema_SequenceNodeOfSeqPCOfPCFOfEPCOfELPCOfLocateExtPC2d.hxx>
 

#define Curve Adaptor2d_Curve2d
#define Curve_hxx <Geometry/Adaptor2d/Adaptor2d_Curve2d.hxx>
#define Tool Extrema_Curve2dTool
#define Tool_hxx <Geometry/Extrema/Extrema_Curve2dTool.hxx>
#define POnC Extrema_POnCurv2d
#define POnC_hxx <Geometry/Extrema/Extrema_POnCurv2d.hxx>
#define Pnt gp_Pnt2d
#define Pnt_hxx <Mathematics/Primitives/gp_Pnt2d.hxx>
#define Vec gp_Vec2d
#define Vec_hxx <Mathematics/Primitives/gp_Vec2d.hxx>
#define Extrema_SeqPC Extrema_SeqPCOfPCFOfEPCOfELPCOfLocateExtPC2d
#define Extrema_SeqPC_hxx <Geometry/Extrema/Extrema_SeqPCOfPCFOfEPCOfELPCOfLocateExtPC2d.hxx>
#define Extrema_SequenceNodeOfSeqPC Extrema_SequenceNodeOfSeqPCOfPCFOfEPCOfELPCOfLocateExtPC2d
#define Extrema_SequenceNodeOfSeqPC_hxx <Geometry/Extrema/Extrema_SequenceNodeOfSeqPCOfPCFOfEPCOfELPCOfLocateExtPC2d.hxx>
#define Extrema_SequenceNodeOfSeqPC Extrema_SequenceNodeOfSeqPCOfPCFOfEPCOfELPCOfLocateExtPC2d
#define Extrema_SequenceNodeOfSeqPC_hxx <Geometry/Extrema/Extrema_SequenceNodeOfSeqPCOfPCFOfEPCOfELPCOfLocateExtPC2d.hxx>
#define Handle_Extrema_SequenceNodeOfSeqPC Handle_Extrema_SequenceNodeOfSeqPCOfPCFOfEPCOfELPCOfLocateExtPC2d
#define Extrema_SequenceNodeOfSeqPC_Type_() Extrema_SequenceNodeOfSeqPCOfPCFOfEPCOfELPCOfLocateExtPC2d_Type_()
#define Handle_Extrema_SequenceNodeOfSeqPC Handle_Extrema_SequenceNodeOfSeqPCOfPCFOfEPCOfELPCOfLocateExtPC2d
#define Extrema_SequenceNodeOfSeqPC_Type_() Extrema_SequenceNodeOfSeqPCOfPCFOfEPCOfELPCOfLocateExtPC2d_Type_()
#define Extrema_FuncExtPC Extrema_PCFOfEPCOfELPCOfLocateExtPC2d
#define Extrema_FuncExtPC_hxx <Geometry/Extrema/Extrema_PCFOfEPCOfELPCOfLocateExtPC2d.hxx>
#include <Geometry/Extrema/Extrema_FuncExtPC.gxx>

