// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Extrema_ELCC2d.hxx>

#include <Foundation/StdFail/StdFail_InfiniteSolutions.hxx>
#include <Foundation/StdFail/StdFail_NotDone.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Geometry/Adaptor2d/Adaptor2d_Curve2d.hxx>
#include <Extrema_Curve2dTool.hxx>
#include <Mathematics/Collections/TColgp_HArray1OfPnt2d.hxx>
#include <Extrema_POnCurv2d.hxx>
#include <Mathematics/Primitives/gp_Pnt2d.hxx>
#include <Mathematics/Primitives/gp_Vec2d.hxx>
 

#define Curve1 Adaptor2d_Curve2d
#define Curve1_hxx <Geometry/Adaptor2d/Adaptor2d_Curve2d.hxx>
#define Tool1 Extrema_Curve2dTool
#define Tool1_hxx <Extrema_Curve2dTool.hxx>
#define Curve2 Adaptor2d_Curve2d
#define Curve2_hxx <Geometry/Adaptor2d/Adaptor2d_Curve2d.hxx>
#define Tool2 Extrema_Curve2dTool
#define Tool2_hxx <Extrema_Curve2dTool.hxx>
#define Handle_ArrayOfPnt Handle_TColgp_HArray1OfPnt2d
#define ArrayOfPnt TColgp_HArray1OfPnt2d
#define ArrayOfPnt_hxx <Mathematics/Collections/TColgp_HArray1OfPnt2d.hxx>
#define POnC Extrema_POnCurv2d
#define POnC_hxx <Extrema_POnCurv2d.hxx>
#define Pnt gp_Pnt2d
#define Pnt_hxx <Mathematics/Primitives/gp_Pnt2d.hxx>
#define Vec gp_Vec2d
#define Vec_hxx <Mathematics/Primitives/gp_Vec2d.hxx>
#define Extrema_GenExtCC Extrema_ELCC2d
#define Extrema_GenExtCC_hxx <Extrema_ELCC2d.hxx>
#include <Extrema_GenExtCC.gxx>

