// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Geometry/Extrema/Extrema_SeqPCOfPCFOfEPCOfExtPC.hxx>

#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Geometry/Extrema/Extrema_POnCurv.hxx>
#include <Geometry/Extrema/Extrema_SequenceNodeOfSeqPCOfPCFOfEPCOfExtPC.hxx>
 

#define SeqItem Extrema_POnCurv
#define SeqItem_hxx <Geometry/Extrema/Extrema_POnCurv.hxx>
#define TCollection_SequenceNode Extrema_SequenceNodeOfSeqPCOfPCFOfEPCOfExtPC
#define TCollection_SequenceNode_hxx <Geometry/Extrema/Extrema_SequenceNodeOfSeqPCOfPCFOfEPCOfExtPC.hxx>
#define Handle_TCollection_SequenceNode Handle_Extrema_SequenceNodeOfSeqPCOfPCFOfEPCOfExtPC
#define TCollection_SequenceNode_Type_() Extrema_SequenceNodeOfSeqPCOfPCFOfEPCOfExtPC_Type_()
#define TCollection_Sequence Extrema_SeqPCOfPCFOfEPCOfExtPC
#define TCollection_Sequence_hxx <Geometry/Extrema/Extrema_SeqPCOfPCFOfEPCOfExtPC.hxx>
#include <Foundation/TCollection/TCollection_Sequence.gxx>

