// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Geometry/Extrema/Extrema_LocateExtPC2d.hxx>

#include <Foundation/Standard/Standard_DomainError.hxx>
#include <Foundation/StdFail/StdFail_NotDone.hxx>
#include <Geometry/Adaptor2d/Adaptor2d_Curve2d.hxx>
#include <Geometry/Extrema/Extrema_Curve2dTool.hxx>
#include <Geometry/Extrema/Extrema_ExtPElC2d.hxx>
#include <Mathematics/Primitives/gp_Pnt2d.hxx>
#include <Mathematics/Primitives/gp_Vec2d.hxx>
#include <Geometry/Extrema/Extrema_POnCurv2d.hxx>
#include <Geometry/Extrema/Extrema_SequenceOfPOnCurv2d.hxx>
#include <Geometry/Extrema/Extrema_ELPCOfLocateExtPC2d.hxx>
#include <Geometry/Extrema/Extrema_EPCOfELPCOfLocateExtPC2d.hxx>
#include <Geometry/Extrema/Extrema_LocEPCOfLocateExtPC2d.hxx>
#include <Geometry/Extrema/Extrema_PCLocFOfLocEPCOfLocateExtPC2d.hxx>
 

#define TheCurve Adaptor2d_Curve2d
#define TheCurve_hxx <Geometry/Adaptor2d/Adaptor2d_Curve2d.hxx>
#define TheCurveTool Extrema_Curve2dTool
#define TheCurveTool_hxx <Geometry/Extrema/Extrema_Curve2dTool.hxx>
#define TheExtPElC Extrema_ExtPElC2d
#define TheExtPElC_hxx <Geometry/Extrema/Extrema_ExtPElC2d.hxx>
#define ThePoint gp_Pnt2d
#define ThePoint_hxx <Mathematics/Primitives/gp_Pnt2d.hxx>
#define TheVector gp_Vec2d
#define TheVector_hxx <Mathematics/Primitives/gp_Vec2d.hxx>
#define ThePOnC Extrema_POnCurv2d
#define ThePOnC_hxx <Geometry/Extrema/Extrema_POnCurv2d.hxx>
#define TheSequenceOfPOnC Extrema_SequenceOfPOnCurv2d
#define TheSequenceOfPOnC_hxx <Geometry/Extrema/Extrema_SequenceOfPOnCurv2d.hxx>
#define Extrema_ELPC Extrema_ELPCOfLocateExtPC2d
#define Extrema_ELPC_hxx <Geometry/Extrema/Extrema_ELPCOfLocateExtPC2d.hxx>
#define Extrema_EPCOfELPC Extrema_EPCOfELPCOfLocateExtPC2d
#define Extrema_EPCOfELPC_hxx <Geometry/Extrema/Extrema_EPCOfELPCOfLocateExtPC2d.hxx>
#define Extrema_EPCOfELPC Extrema_EPCOfELPCOfLocateExtPC2d
#define Extrema_EPCOfELPC_hxx <Geometry/Extrema/Extrema_EPCOfELPCOfLocateExtPC2d.hxx>
#define Extrema_LocEPC Extrema_LocEPCOfLocateExtPC2d
#define Extrema_LocEPC_hxx <Geometry/Extrema/Extrema_LocEPCOfLocateExtPC2d.hxx>
#define Extrema_PCLocFOfLocEPC Extrema_PCLocFOfLocEPCOfLocateExtPC2d
#define Extrema_PCLocFOfLocEPC_hxx <Geometry/Extrema/Extrema_PCLocFOfLocEPCOfLocateExtPC2d.hxx>
#define Extrema_PCLocFOfLocEPC Extrema_PCLocFOfLocEPCOfLocateExtPC2d
#define Extrema_PCLocFOfLocEPC_hxx <Geometry/Extrema/Extrema_PCLocFOfLocEPCOfLocateExtPC2d.hxx>
#define Extrema_GLocateExtPC Extrema_LocateExtPC2d
#define Extrema_GLocateExtPC_hxx <Geometry/Extrema/Extrema_LocateExtPC2d.hxx>
#include <Geometry/Extrema/Extrema_GLocateExtPC.gxx>

