// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Geometry/Extrema/Extrema_HArray1OfPOnCurv.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <Foundation/Standard/Standard_RangeError.hxx>
#include <Foundation/Standard/Standard_DimensionMismatch.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_OutOfMemory.hxx>
#include <Geometry/Extrema/Extrema_POnCurv.hxx>
#include <Geometry/Extrema/Extrema_Array1OfPOnCurv.hxx>

 


IMPLEMENT_STANDARD_TYPE(Extrema_HArray1OfPOnCurv)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(Extrema_HArray1OfPOnCurv)


IMPLEMENT_DOWNCAST(Extrema_HArray1OfPOnCurv,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(Extrema_HArray1OfPOnCurv)


#define ItemHArray1 Extrema_POnCurv
#define ItemHArray1_hxx <Geometry/Extrema/Extrema_POnCurv.hxx>
#define TheArray1 Extrema_Array1OfPOnCurv
#define TheArray1_hxx <Geometry/Extrema/Extrema_Array1OfPOnCurv.hxx>
#define TCollection_HArray1 Extrema_HArray1OfPOnCurv
#define TCollection_HArray1_hxx <Geometry/Extrema/Extrema_HArray1OfPOnCurv.hxx>
#define Handle_TCollection_HArray1 Handle_Extrema_HArray1OfPOnCurv
#define TCollection_HArray1_Type_() Extrema_HArray1OfPOnCurv_Type_()
#include <Foundation/TCollection/TCollection_HArray1.gxx>

