// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Geometry/Extrema/Extrema_EPCOfExtPC2d.hxx>

#include <Foundation/StdFail/StdFail_NotDone.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_TypeMismatch.hxx>
#include <Geometry/Adaptor2d/Adaptor2d_Curve2d.hxx>
#include <Geometry/Extrema/Extrema_Curve2dTool.hxx>
#include <Geometry/Extrema/Extrema_POnCurv2d.hxx>
#include <Mathematics/Primitives/gp_Pnt2d.hxx>
#include <Mathematics/Primitives/gp_Vec2d.hxx>
#include <Geometry/Extrema/Extrema_PCFOfEPCOfExtPC2d.hxx>
#include <Geometry/Extrema/Extrema_SeqPCOfPCFOfEPCOfExtPC2d.hxx>
 

#define Curve Adaptor2d_Curve2d
#define Curve_hxx <Geometry/Adaptor2d/Adaptor2d_Curve2d.hxx>
#define Tool Extrema_Curve2dTool
#define Tool_hxx <Geometry/Extrema/Extrema_Curve2dTool.hxx>
#define POnC Extrema_POnCurv2d
#define POnC_hxx <Geometry/Extrema/Extrema_POnCurv2d.hxx>
#define Pnt gp_Pnt2d
#define Pnt_hxx <Mathematics/Primitives/gp_Pnt2d.hxx>
#define Vec gp_Vec2d
#define Vec_hxx <Mathematics/Primitives/gp_Vec2d.hxx>
#define Extrema_PCF Extrema_PCFOfEPCOfExtPC2d
#define Extrema_PCF_hxx <Geometry/Extrema/Extrema_PCFOfEPCOfExtPC2d.hxx>
#define Extrema_SeqPCOfPCF Extrema_SeqPCOfPCFOfEPCOfExtPC2d
#define Extrema_SeqPCOfPCF_hxx <Geometry/Extrema/Extrema_SeqPCOfPCFOfEPCOfExtPC2d.hxx>
#define Extrema_SeqPCOfPCF Extrema_SeqPCOfPCFOfEPCOfExtPC2d
#define Extrema_SeqPCOfPCF_hxx <Geometry/Extrema/Extrema_SeqPCOfPCFOfEPCOfExtPC2d.hxx>
#define Extrema_GenExtPC Extrema_EPCOfExtPC2d
#define Extrema_GenExtPC_hxx <Geometry/Extrema/Extrema_EPCOfExtPC2d.hxx>
#include <Geometry/Extrema/Extrema_GenExtPC.gxx>

