// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _HLRAlgo_PolyInternalSegment_HeaderFile
#define _HLRAlgo_PolyInternalSegment_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineAlloc.hxx>
#include <Foundation/Standard/Standard_Macro.hxx>

#include <Foundation/Standard/Standard_Integer.hxx>
#include <Foundation/Standard/Standard_Address.hxx>


//! to Update OutLines.
class HLRAlgo_PolyInternalSegment 
{
public:

  DEFINE_STANDARD_ALLOC

  
    HLRAlgo_PolyInternalSegment();
  
      Standard_Address Indices()  const;




protected:





private:



  Standard_Integer myIndices[6];


};


#include <ModelingAlgorithms/HLRAlgo/HLRAlgo_PolyInternalSegment.lxx>





#endif // _HLRAlgo_PolyInternalSegment_HeaderFile
