// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _HLRAlgo_InterferenceList_HeaderFile
#define _HLRAlgo_InterferenceList_HeaderFile

#include <ModelingAlgorithms/HLRAlgo/HLRAlgo_Interference.hxx>

#include <list>

typedef std::list<HLRAlgo_Interference> HLRAlgo_InterferenceList;

#endif // _HLRAlgo_InterferenceList_HeaderFile
