// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _HLRAlgo_ListIteratorOfListOfBPoint_HeaderFile
#define _HLRAlgo_ListIteratorOfListOfBPoint_HeaderFile

#include <ModelingAlgorithms/HLRAlgo/HLRAlgo_ListOfBPoint.hxx>

typedef HLRAlgo_ListOfBPoint::iterator HLRAlgo_ListIteratorOfListOfBPoint;

#endif // _HLRAlgo_ListIteratorOfListOfBPoint_HeaderFile
