// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ModelingAlgorithms/HatchGen/HatchGen_PointsOnElement.hxx>

#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <ModelingAlgorithms/HatchGen/HatchGen_PointOnElement.hxx>
#include <ModelingAlgorithms/HatchGen/HatchGen_SequenceNodeOfPointsOnElement.hxx>
 

#define SeqItem HatchGen_PointOnElement
#define SeqItem_hxx <ModelingAlgorithms/HatchGen/HatchGen_PointOnElement.hxx>
#define TCollection_SequenceNode HatchGen_SequenceNodeOfPointsOnElement
#define TCollection_SequenceNode_hxx <ModelingAlgorithms/HatchGen/HatchGen_SequenceNodeOfPointsOnElement.hxx>
#define Handle_TCollection_SequenceNode Handle_HatchGen_SequenceNodeOfPointsOnElement
#define TCollection_SequenceNode_Type_() HatchGen_SequenceNodeOfPointsOnElement_Type_()
#define TCollection_Sequence HatchGen_PointsOnElement
#define TCollection_Sequence_hxx <ModelingAlgorithms/HatchGen/HatchGen_PointsOnElement.hxx>
#include <Foundation/TCollection/TCollection_Sequence.gxx>

