// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ModelingAlgorithms/HatchGen/HatchGen_SequenceNodeOfPointsOnElement.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <ModelingAlgorithms/HatchGen/HatchGen_PointOnElement.hxx>
#include <ModelingAlgorithms/HatchGen/HatchGen_PointsOnElement.hxx>

 


IMPLEMENT_STANDARD_TYPE(HatchGen_SequenceNodeOfPointsOnElement)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(HatchGen_SequenceNodeOfPointsOnElement)


IMPLEMENT_DOWNCAST(HatchGen_SequenceNodeOfPointsOnElement,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(HatchGen_SequenceNodeOfPointsOnElement)


#define SeqItem HatchGen_PointOnElement
#define SeqItem_hxx <ModelingAlgorithms/HatchGen/HatchGen_PointOnElement.hxx>
#define TCollection_SequenceNode HatchGen_SequenceNodeOfPointsOnElement
#define TCollection_SequenceNode_hxx <ModelingAlgorithms/HatchGen/HatchGen_SequenceNodeOfPointsOnElement.hxx>
#define Handle_TCollection_SequenceNode Handle_HatchGen_SequenceNodeOfPointsOnElement
#define TCollection_SequenceNode_Type_() HatchGen_SequenceNodeOfPointsOnElement_Type_()
#define TCollection_Sequence HatchGen_PointsOnElement
#define TCollection_Sequence_hxx <ModelingAlgorithms/HatchGen/HatchGen_PointsOnElement.hxx>
#include <Foundation/TCollection/TCollection_SequenceNode.gxx>

