// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <StepElement_Array1OfCurveElementEndReleasePacket.hxx>

#include <Foundation/Standard/Standard_RangeError.hxx>
#include <Foundation/Standard/Standard_DimensionMismatch.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_OutOfMemory.hxx>
#include <StepElement_CurveElementEndReleasePacket.hxx>
 

#define Array1Item Handle(StepElement_CurveElementEndReleasePacket)
#define Array1Item_hxx <StepElement_CurveElementEndReleasePacket.hxx>
#define TCollection_Array1 StepElement_Array1OfCurveElementEndReleasePacket
#define TCollection_Array1_hxx <StepElement_Array1OfCurveElementEndReleasePacket.hxx>
#include <Foundation/TCollection/TCollection_Array1.gxx>

