// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <DataExchange/StepElement/StepElement_HSequenceOfElementMaterial.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <DataExchange/StepElement/StepElement_ElementMaterial.hxx>
#include <DataExchange/StepElement/StepElement_SequenceOfElementMaterial.hxx>

 


IMPLEMENT_STANDARD_TYPE(StepElement_HSequenceOfElementMaterial)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(StepElement_HSequenceOfElementMaterial)


IMPLEMENT_DOWNCAST(StepElement_HSequenceOfElementMaterial,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(StepElement_HSequenceOfElementMaterial)


#define Item Handle(StepElement_ElementMaterial)
#define Item_hxx <DataExchange/StepElement/StepElement_ElementMaterial.hxx>
#define TheSequence StepElement_SequenceOfElementMaterial
#define TheSequence_hxx <DataExchange/StepElement/StepElement_SequenceOfElementMaterial.hxx>
#define TCollection_HSequence StepElement_HSequenceOfElementMaterial
#define TCollection_HSequence_hxx <DataExchange/StepElement/StepElement_HSequenceOfElementMaterial.hxx>
#define Handle_TCollection_HSequence Handle_StepElement_HSequenceOfElementMaterial
#define TCollection_HSequence_Type_() StepElement_HSequenceOfElementMaterial_Type_()
#include <Foundation/TCollection/TCollection_HSequence.gxx>

