// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <DataExchange/StepElement/StepElement_HArray1OfVolumeElementPurposeMember.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <Foundation/Standard/Standard_RangeError.hxx>
#include <Foundation/Standard/Standard_DimensionMismatch.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_OutOfMemory.hxx>
#include <DataExchange/StepElement/StepElement_VolumeElementPurposeMember.hxx>
#include <DataExchange/StepElement/StepElement_Array1OfVolumeElementPurposeMember.hxx>

 


IMPLEMENT_STANDARD_TYPE(StepElement_HArray1OfVolumeElementPurposeMember)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(StepElement_HArray1OfVolumeElementPurposeMember)


IMPLEMENT_DOWNCAST(StepElement_HArray1OfVolumeElementPurposeMember,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(StepElement_HArray1OfVolumeElementPurposeMember)


#define ItemHArray1 Handle(StepElement_VolumeElementPurposeMember)
#define ItemHArray1_hxx <DataExchange/StepElement/StepElement_VolumeElementPurposeMember.hxx>
#define TheArray1 StepElement_Array1OfVolumeElementPurposeMember
#define TheArray1_hxx <DataExchange/StepElement/StepElement_Array1OfVolumeElementPurposeMember.hxx>
#define TCollection_HArray1 StepElement_HArray1OfVolumeElementPurposeMember
#define TCollection_HArray1_hxx <DataExchange/StepElement/StepElement_HArray1OfVolumeElementPurposeMember.hxx>
#define Handle_TCollection_HArray1 Handle_StepElement_HArray1OfVolumeElementPurposeMember
#define TCollection_HArray1_Type_() StepElement_HArray1OfVolumeElementPurposeMember_Type_()
#include <Foundation/TCollection/TCollection_HArray1.gxx>

