// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Mathematics/TopLoc/TopLoc_IndexedMapOfLocation.hxx>

#include <Foundation/Standard/Standard_DomainError.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Mathematics/TopLoc/TopLoc_Location.hxx>
#include <Mathematics/TopLoc/TopLoc_MapLocationHasher.hxx>
#include <Mathematics/TopLoc/TopLoc_IndexedMapNodeOfIndexedMapOfLocation.hxx>
 

#define TheKey TopLoc_Location
#define TheKey_hxx <Mathematics/TopLoc/TopLoc_Location.hxx>
#define Hasher TopLoc_MapLocationHasher
#define Hasher_hxx <Mathematics/TopLoc/TopLoc_MapLocationHasher.hxx>
#define TCollection_IndexedMapNode TopLoc_IndexedMapNodeOfIndexedMapOfLocation
#define TCollection_IndexedMapNode_hxx <Mathematics/TopLoc/TopLoc_IndexedMapNodeOfIndexedMapOfLocation.hxx>
#define Handle_TCollection_IndexedMapNode Handle_TopLoc_IndexedMapNodeOfIndexedMapOfLocation
#define TCollection_IndexedMapNode_Type_() TopLoc_IndexedMapNodeOfIndexedMapOfLocation_Type_()
#define TCollection_IndexedMap TopLoc_IndexedMapOfLocation
#define TCollection_IndexedMap_hxx <Mathematics/TopLoc/TopLoc_IndexedMapOfLocation.hxx>
#include <Foundation/TCollection/TCollection_IndexedMap.gxx>

