// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <OCAF/PColStd/PColStd_VArrayNodeOfFieldOfHArray2OfReal.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <OCAF/PColStd/PColStd_FieldOfHArray2OfReal.hxx>
#include <OCAF/PColStd/PColStd_VArrayTNodeOfFieldOfHArray2OfReal.hxx>

 


IMPLEMENT_STANDARD_TYPE(PColStd_VArrayNodeOfFieldOfHArray2OfReal)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(PStandard_ArrayNode),
  STANDARD_TYPE(Standard_Persistent),
  STANDARD_TYPE(Standard_Storable),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(PColStd_VArrayNodeOfFieldOfHArray2OfReal)


IMPLEMENT_DOWNCAST(PColStd_VArrayNodeOfFieldOfHArray2OfReal,Standard_Persistent)
IMPLEMENT_STANDARD_RTTI(PColStd_VArrayNodeOfFieldOfHArray2OfReal)


#define Item Standard_Real
#define Item_hxx <Foundation/Standard/Standard_Real.hxx>
#define DBC_VArrayNode PColStd_VArrayNodeOfFieldOfHArray2OfReal
#define DBC_VArrayNode_hxx <OCAF/PColStd/PColStd_VArrayNodeOfFieldOfHArray2OfReal.hxx>
#define DBC_VArrayTNode PColStd_VArrayTNodeOfFieldOfHArray2OfReal
#define DBC_VArrayTNode_hxx <OCAF/PColStd/PColStd_VArrayTNodeOfFieldOfHArray2OfReal.hxx>
#define Handle_DBC_VArrayNode Handle_PColStd_VArrayNodeOfFieldOfHArray2OfReal
#define DBC_VArrayNode_Type_() PColStd_VArrayNodeOfFieldOfHArray2OfReal_Type_()
#define DBC_VArray PColStd_FieldOfHArray2OfReal
#define DBC_VArray_hxx <OCAF/PColStd/PColStd_FieldOfHArray2OfReal.hxx>
#include <OCAF/DBC/DBC_VArrayNode.gxx>

