// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <PColStd_FieldOfHArray2OfPersistent.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <Foundation/Standard/Standard_NegativeValue.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_DimensionMismatch.hxx>
#include <Foundation/Standard/Standard_NullObject.hxx>
#include <Foundation/Standard/Standard_Persistent.hxx>
#include <PColStd_VArrayNodeOfFieldOfHArray2OfPersistent.hxx>
#include <PColStd_VArrayTNodeOfFieldOfHArray2OfPersistent.hxx>

IMPLEMENT_STANDARD_TYPE(PColStd_FieldOfHArray2OfPersistent)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(DBC_BaseArray),
  STANDARD_TYPE(Standard_Storable),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(PColStd_FieldOfHArray2OfPersistent)
 

#define Item Handle(Standard_Persistent)
#define Item_hxx <Foundation/Standard/Standard_Persistent.hxx>
#define DBC_VArrayNode PColStd_VArrayNodeOfFieldOfHArray2OfPersistent
#define DBC_VArrayNode_hxx <PColStd_VArrayNodeOfFieldOfHArray2OfPersistent.hxx>
#define DBC_VArrayTNode PColStd_VArrayTNodeOfFieldOfHArray2OfPersistent
#define DBC_VArrayTNode_hxx <PColStd_VArrayTNodeOfFieldOfHArray2OfPersistent.hxx>
#define Handle_DBC_VArrayNode Handle_PColStd_VArrayNodeOfFieldOfHArray2OfPersistent
#define DBC_VArrayNode_Type_() PColStd_VArrayNodeOfFieldOfHArray2OfPersistent_Type_()
#define DBC_VArray PColStd_FieldOfHArray2OfPersistent
#define DBC_VArray_hxx <PColStd_FieldOfHArray2OfPersistent.hxx>
#include <OCAF/DBC/DBC_VArray.gxx>

