// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ModelingAlgorithms/TopOpeBRep/TopOpeBRep_ListNodeOfListOfBipoint.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <ModelingAlgorithms/TopOpeBRep/TopOpeBRep_Bipoint.hxx>
#include <ModelingAlgorithms/TopOpeBRep/TopOpeBRep_ListOfBipoint.hxx>
#include <ModelingAlgorithms/TopOpeBRep/TopOpeBRep_ListIteratorOfListOfBipoint.hxx>

 


IMPLEMENT_STANDARD_TYPE(TopOpeBRep_ListNodeOfListOfBipoint)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(TopOpeBRep_ListNodeOfListOfBipoint)


IMPLEMENT_DOWNCAST(TopOpeBRep_ListNodeOfListOfBipoint,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(TopOpeBRep_ListNodeOfListOfBipoint)


#define Item TopOpeBRep_Bipoint
#define Item_hxx <ModelingAlgorithms/TopOpeBRep/TopOpeBRep_Bipoint.hxx>
#define TCollection_ListNode TopOpeBRep_ListNodeOfListOfBipoint
#define TCollection_ListNode_hxx <ModelingAlgorithms/TopOpeBRep/TopOpeBRep_ListNodeOfListOfBipoint.hxx>
#define TCollection_ListIterator TopOpeBRep_ListIteratorOfListOfBipoint
#define TCollection_ListIterator_hxx <ModelingAlgorithms/TopOpeBRep/TopOpeBRep_ListIteratorOfListOfBipoint.hxx>
#define Handle_TCollection_ListNode Handle_TopOpeBRep_ListNodeOfListOfBipoint
#define TCollection_ListNode_Type_() TopOpeBRep_ListNodeOfListOfBipoint_Type_()
#define TCollection_List TopOpeBRep_ListOfBipoint
#define TCollection_List_hxx <ModelingAlgorithms/TopOpeBRep/TopOpeBRep_ListOfBipoint.hxx>
#include <Foundation/TCollection/TCollection_ListNode.gxx>

