// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Foundation/Storage/Storage_SeqOfRoot.hxx>

#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Storage/Storage_Root.hxx>
#include <Foundation/Storage/Storage_SequenceNodeOfSeqOfRoot.hxx>
 

#define SeqItem Handle(Storage_Root)
#define SeqItem_hxx <Foundation/Storage/Storage_Root.hxx>
#define TCollection_SequenceNode Storage_SequenceNodeOfSeqOfRoot
#define TCollection_SequenceNode_hxx <Foundation/Storage/Storage_SequenceNodeOfSeqOfRoot.hxx>
#define Handle_TCollection_SequenceNode Handle_Storage_SequenceNodeOfSeqOfRoot
#define TCollection_SequenceNode_Type_() Storage_SequenceNodeOfSeqOfRoot_Type_()
#define TCollection_Sequence Storage_SeqOfRoot
#define TCollection_Sequence_hxx <Foundation/Storage/Storage_SeqOfRoot.hxx>
#include <TCollection_Sequence.gxx>

