// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <OCAF/CDM/CDM_DataMapIteratorOfPresentationDirectory.hxx>

#include <Foundation/Standard/Standard_NoSuchObject.hxx>
#include <Foundation/TCollection/TCollection_ExtendedString.hxx>
#include <OCAF/CDM/CDM_Document.hxx>
#include <OCAF/CDM/CDM_PresentationDirectory.hxx>
#include <OCAF/CDM/CDM_DataMapNodeOfPresentationDirectory.hxx>
 

#define TheKey TCollection_ExtendedString
#define TheKey_hxx <Foundation/TCollection/TCollection_ExtendedString.hxx>
#define TheItem Handle(CDM_Document)
#define TheItem_hxx <OCAF/CDM/CDM_Document.hxx>
#define Hasher TCollection_ExtendedString
#define Hasher_hxx <Foundation/TCollection/TCollection_ExtendedString.hxx>
#define TCollection_DataMapNode CDM_DataMapNodeOfPresentationDirectory
#define TCollection_DataMapNode_hxx <OCAF/CDM/CDM_DataMapNodeOfPresentationDirectory.hxx>
#define TCollection_DataMapIterator CDM_DataMapIteratorOfPresentationDirectory
#define TCollection_DataMapIterator_hxx <OCAF/CDM/CDM_DataMapIteratorOfPresentationDirectory.hxx>
#define Handle_TCollection_DataMapNode Handle_CDM_DataMapNodeOfPresentationDirectory
#define TCollection_DataMapNode_Type_() CDM_DataMapNodeOfPresentationDirectory_Type_()
#define TCollection_DataMap CDM_PresentationDirectory
#define TCollection_DataMap_hxx <OCAF/CDM/CDM_PresentationDirectory.hxx>
#include <Foundation/TCollection/TCollection_DataMapIterator.gxx>

