// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_StepAP214_AutoDesignActualDateAndTimeAssignment_HeaderFile
#define _Handle_StepAP214_AutoDesignActualDateAndTimeAssignment_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <DataExchange/StepBasic/Handle_StepBasic_DateAndTimeAssignment.hxx>

class Standard_Transient;
class Handle(Standard_Type);
class Handle(StepBasic_DateAndTimeAssignment);
class StepAP214_AutoDesignActualDateAndTimeAssignment;

DEFINE_STANDARD_HANDLE(StepAP214_AutoDesignActualDateAndTimeAssignment, StepBasic_DateAndTimeAssignment)

#endif // _Handle_StepAP214_AutoDesignActualDateAndTimeAssignment_HeaderFile
