// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <DataExchange/IGESAppli/IGESAppli_HArray1OfFiniteElement.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <Foundation/Standard/Standard_RangeError.hxx>
#include <Foundation/Standard/Standard_DimensionMismatch.hxx>
#include <Foundation/Standard/Standard_OutOfRange.hxx>
#include <Foundation/Standard/Standard_OutOfMemory.hxx>
#include <DataExchange/IGESAppli/IGESAppli_FiniteElement.hxx>
#include <DataExchange/IGESAppli/IGESAppli_Array1OfFiniteElement.hxx>

 


IMPLEMENT_STANDARD_TYPE(IGESAppli_HArray1OfFiniteElement)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(IGESAppli_HArray1OfFiniteElement)


IMPLEMENT_DOWNCAST(IGESAppli_HArray1OfFiniteElement,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(IGESAppli_HArray1OfFiniteElement)


#define ItemHArray1 Handle(IGESAppli_FiniteElement)
#define ItemHArray1_hxx <DataExchange/IGESAppli/IGESAppli_FiniteElement.hxx>
#define TheArray1 IGESAppli_Array1OfFiniteElement
#define TheArray1_hxx <DataExchange/IGESAppli/IGESAppli_Array1OfFiniteElement.hxx>
#define TCollection_HArray1 IGESAppli_HArray1OfFiniteElement
#define TCollection_HArray1_hxx <DataExchange/IGESAppli/IGESAppli_HArray1OfFiniteElement.hxx>
#define Handle_TCollection_HArray1 Handle_IGESAppli_HArray1OfFiniteElement
#define TCollection_HArray1_Type_() IGESAppli_HArray1OfFiniteElement_Type_()
#include <Foundation/TCollection/TCollection_HArray1.gxx>

