// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _IntTools_ListIteratorOfListOfSurfaceRangeSample_HeaderFile
#define _IntTools_ListIteratorOfListOfSurfaceRangeSample_HeaderFile

#include <ModelingAlgorithms/IntTools/IntTools_ListOfSurfaceRangeSample.hxx>

typedef IntTools_ListOfSurfaceRangeSample::iterator IntTools_ListIteratorOfListOfSurfaceRangeSample;

#endif // _IntTools_ListIteratorOfListOfSurfaceRangeSample_HeaderFile
