// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _STEPCAFControl_DataMapIteratorOfDataMapOfSDRExternFile_HeaderFile
#define _STEPCAFControl_DataMapIteratorOfDataMapOfSDRExternFile_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineAlloc.hxx>
#include <Foundation/Standard/Standard_Macro.hxx>

#include <Foundation/TCollection/TCollection_BasicMapIterator.hxx>
#include <DataExchange/StepShape/Handle_StepShape_ShapeDefinitionRepresentation.hxx>
#include <DataExchange/STEPCAFControl/Handle_STEPCAFControl_ExternFile.hxx>
#include <DataExchange/STEPCAFControl/Handle_STEPCAFControl_DataMapNodeOfDataMapOfSDRExternFile.hxx>
class Standard_NoSuchObject;
class StepShape_ShapeDefinitionRepresentation;
class STEPCAFControl_ExternFile;
class TColStd_MapTransientHasher;
class STEPCAFControl_DataMapOfSDRExternFile;
class STEPCAFControl_DataMapNodeOfDataMapOfSDRExternFile;



class STEPCAFControl_DataMapIteratorOfDataMapOfSDRExternFile  : public TCollection_BasicMapIterator
{
public:

  DEFINE_STANDARD_ALLOC

  
  Standard_EXPORT STEPCAFControl_DataMapIteratorOfDataMapOfSDRExternFile();
  
  Standard_EXPORT STEPCAFControl_DataMapIteratorOfDataMapOfSDRExternFile(const STEPCAFControl_DataMapOfSDRExternFile& aMap);
  
  Standard_EXPORT   void Initialize (const STEPCAFControl_DataMapOfSDRExternFile& aMap) ;
  
  Standard_EXPORT  const  Handle(StepShape_ShapeDefinitionRepresentation)& Key()  const;
  
  Standard_EXPORT  const  Handle(STEPCAFControl_ExternFile)& Value()  const;




protected:





private:





};







#endif // _STEPCAFControl_DataMapIteratorOfDataMapOfSDRExternFile_HeaderFile
