// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Visualization/AIS/AIS_SequenceNodeOfSequenceOfDimension.hxx>

#include <Foundation/Standard/Standard_Type.hxx>

#include <Visualization/AIS/AIS_Relation.hxx>
#include <Visualization/AIS/AIS_SequenceOfDimension.hxx>

 


IMPLEMENT_STANDARD_TYPE(AIS_SequenceNodeOfSequenceOfDimension)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(AIS_SequenceNodeOfSequenceOfDimension)


IMPLEMENT_DOWNCAST(AIS_SequenceNodeOfSequenceOfDimension,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(AIS_SequenceNodeOfSequenceOfDimension)


#define SeqItem Handle(AIS_Relation)
#define SeqItem_hxx <Visualization/AIS/AIS_Relation.hxx>
#define TCollection_SequenceNode AIS_SequenceNodeOfSequenceOfDimension
#define TCollection_SequenceNode_hxx <Visualization/AIS/AIS_SequenceNodeOfSequenceOfDimension.hxx>
#define Handle_TCollection_SequenceNode Handle_AIS_SequenceNodeOfSequenceOfDimension
#define TCollection_SequenceNode_Type_() AIS_SequenceNodeOfSequenceOfDimension_Type_()
#define TCollection_Sequence AIS_SequenceOfDimension
#define TCollection_Sequence_hxx <Visualization/AIS/AIS_SequenceOfDimension.hxx>
#include <Foundation/TCollection/TCollection_SequenceNode.gxx>

