// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _FairCurve_DistributionOfTension_HeaderFile
#define _FairCurve_DistributionOfTension_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineAlloc.hxx>
#include <Foundation/Standard/Standard_Macro.hxx>

#include <Foundation/Standard/Standard_Real.hxx>
#include <ModelingAlgorithms/FairCurve/FairCurve_BattenLaw.hxx>
#include <ModelingAlgorithms/FairCurve/FairCurve_DistributionOfEnergy.hxx>
#include <Foundation/Standard/Standard_Integer.hxx>
#include <Foundation/TColStd/Handle_TColStd_HArray1OfReal.hxx>
#include <Mathematics/Collections/Handle_TColgp_HArray1OfPnt2d.hxx>
#include <Foundation/Standard/Standard_Boolean.hxx>
#include <Mathematics/Optimization/math_Vector.hxx>
class TColStd_HArray1OfReal;
class TColgp_HArray1OfPnt2d;
class FairCurve_BattenLaw;


//! Compute the Tension Distribution
class FairCurve_DistributionOfTension  : public FairCurve_DistributionOfEnergy
{
public:

  DEFINE_STANDARD_ALLOC

  
  Standard_EXPORT FairCurve_DistributionOfTension(const Standard_Integer BSplOrder, const Handle(TColStd_HArray1OfReal)& FlatKnots, const Handle(TColgp_HArray1OfPnt2d)& Poles, const Standard_Integer DerivativeOrder, const Standard_Real LengthSliding, const FairCurve_BattenLaw& Law, const Standard_Integer NbValAux = 0, const Standard_Boolean Uniform = Standard_False);
  
  //! change the length sliding
      void SetLengthSliding (const Standard_Real LengthSliding) ;
  
  //! computes the values <F> of the functions for the
  //! variable <X>.
  //! returns True if the computation was done successfully,
  //! False otherwise.
  Standard_EXPORT virtual   Standard_Boolean Value (const math_Vector& X, math_Vector& F) ;




protected:





private:



  Standard_Real MyLengthSliding;
  FairCurve_BattenLaw MyLaw;
  Standard_Real MyHeight;


};


#include <ModelingAlgorithms/FairCurve/FairCurve_DistributionOfTension.lxx>





#endif // _FairCurve_DistributionOfTension_HeaderFile
