// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _CDM_ListOfDocument_HeaderFile
#define _CDM_ListOfDocument_HeaderFile

#include <list>

#include <OCAF/CDM/Handle_CDM_Document.hxx>

typedef std::list<Handle(CDM_Document)> CDM_ListOfDocument;

#endif // _CDM_ListOfDocument_HeaderFile
