// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _StepShape_ShapeDefinitionRepresentation_HeaderFile
#define _StepShape_ShapeDefinitionRepresentation_HeaderFile

#include <Foundation/Standard/Standard.hxx>
#include <Foundation/Standard/Standard_DefineHandle.hxx>
#include <Handle_StepShape_ShapeDefinitionRepresentation.hxx>

#include <DataExchange/StepRepr/StepRepr_PropertyDefinitionRepresentation.hxx>


//! Representation of STEP entity ShapeDefinitionRepresentation
class StepShape_ShapeDefinitionRepresentation : public StepRepr_PropertyDefinitionRepresentation
{

public:

  
  //! Empty constructor
  Standard_EXPORT StepShape_ShapeDefinitionRepresentation();




  DEFINE_STANDARD_RTTI(StepShape_ShapeDefinitionRepresentation)

protected:




private: 




};







#endif // _StepShape_ShapeDefinitionRepresentation_HeaderFile
