// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _HLRBRep_ListOfBPnt2D_HeaderFile
#define _HLRBRep_ListOfBPnt2D_HeaderFile

#include <vector>

#include <ModelingAlgorithms/HLRBRep/HLRBRep_BiPnt2D.hxx>

typedef std::list<HLRBRep_BiPnt2D> HLRBRep_ListOfBPnt2D;

#endif // _HLRBRep_ListOfBPnt2D_HeaderFile
